/* @layer tests @kind test */
/**
 * The multiworld client's DeathLink both ways, with the slot data deciding over the profile flag,
 * and its refusal of a slot from another world package version. Split from ap-protocol.keep.test.ts;
 * the shared room and boot are in ap-protocol-harness.ts.
 */
import { describe, expect, it, vi } from 'vitest';
import { parseSlotData } from '@shared/randomizer/archipelago/parse-slot-data';
import { AP_WORLD_VERSION } from '@shared/randomizer/archipelago/ap-game';
import { boot, installClientHarness, makeRoom, settle } from './ap-protocol-harness';
import type { FakeRoom, FakeServer } from './ap-fake-server';

// The real bus installs window error handlers on import; node has no window.
vi.mock('@app/lib/log-bus', () => {
  const quiet = (): void => undefined;
  return { log: { core: quiet, app: quiet, randomizer: quiet, wasm: quiet, ipc: quiet, sim: quiet, error: quiet } };
});

installClientHarness();

const withDeathLink = (deathLink: boolean): FakeRoom => {
  const room = makeRoom();
  room.slotData = { ...(room.slotData as Record<string, unknown>), deathLink };
  return room;
};

/** The DeathLink bounces only: the network ping is a Bounce too. */
const deathLinkBounces = (server: FakeServer) => server.of('Bounce').filter((packet) => packet.tags?.includes('DeathLink'));

describe('DeathLink', () => {
  it('kills on a room death, sends our own, and guards both ways for 5 s', async () => {
    const { server, core } = await boot(withDeathLink(true), { deathLink: true });
    const bounce = (source: string) => server.push([{ cmd: 'Bounced', tags: ['DeathLink'], data: { source, time: 0, cause: `${source} fell` } }]);
    bounce('Zelda');
    await settle();
    expect(core.kills).toBe(1);
    core.die('killed by the room');
    expect(deathLinkBounces(server)).toHaveLength(0);
    await vi.advanceTimersByTimeAsync(6000);
    core.die('fell in a pit');
    expect(deathLinkBounces(server)).toEqual([{
      cmd: 'Bounce', tags: ['DeathLink'], data: { time: Date.now() / 1000, source: 'Link', cause: 'fell in a pit' },
    }]);
    bounce('Link');
    bounce('Zelda');
    await settle();
    expect(core.kills).toBe(1);
    await vi.advanceTimersByTimeAsync(6000);
    bounce('Zelda');
    await settle();
    expect(core.kills).toBe(2);
    expect([server.of('ConnectUpdate'), core.deathLinkBits]).toEqual([[], [true]]);
  });

  it('a death the room caused (core cause 1) is never sent, however late it commits', async () => {
    const { server, core } = await boot(withDeathLink(true), { deathLink: true });
    server.push([{ cmd: 'Bounced', tags: ['DeathLink'], data: { source: 'Zelda', time: 0, cause: 'fell' } }]);
    await settle();
    expect(core.kills).toBe(1);
    await vi.advanceTimersByTimeAsync(6000);
    core.die(1);
    expect(deathLinkBounces(server)).toHaveLength(0);
  });

  it('a genuine death after a room kill a fairy undid (core cause 0) is sent', async () => {
    const { server, core } = await boot(withDeathLink(true), { deathLink: true });
    server.push([{ cmd: 'Bounced', tags: ['DeathLink'], data: { source: 'Zelda', time: 0, cause: 'fell' } }]);
    await settle();
    expect(core.kills).toBe(1);
    // The fairy revived Link, so the core reported nothing and cleared its room-kill flag.
    await vi.advanceTimersByTimeAsync(6000);
    core.die(0);
    expect(deathLinkBounces(server)).toEqual([{
      cmd: 'Bounce', tags: ['DeathLink'], data: { time: Date.now() / 1000, source: 'Link', cause: 'Link died' },
    }]);
  });

  it('the slot data decides once Connected, and a ConnectUpdate corrects the tags', async () => {
    const off = await boot(withDeathLink(false), { deathLink: true });
    expect(off.server.of('Connect')[0].tags).toEqual(['DeathLink']);
    expect(off.server.of('ConnectUpdate')).toEqual([{ cmd: 'ConnectUpdate', items_handling: 0b111, tags: [] }]);
    expect(off.core.deathLinkBits).toEqual([true, false]);
    off.server.push([{ cmd: 'Bounced', tags: ['DeathLink'], data: { source: 'Zelda', time: 0, cause: 'fell' } }]);
    await settle();
    off.core.die('fell in a pit');
    expect([off.core.kills, deathLinkBounces(off.server).length]).toEqual([0, 0]);

    const on = await boot(withDeathLink(true));
    expect(on.server.of('Connect')[0].tags).toEqual([]);
    expect(on.server.of('ConnectUpdate')).toEqual([{ cmd: 'ConnectUpdate', items_handling: 0b111, tags: ['DeathLink'] }]);
    on.server.push([{ cmd: 'Bounced', tags: ['DeathLink'], data: { source: 'Zelda', time: 0, cause: 'fell' } }]);
    await settle();
    expect(on.core.kills).toBe(1);
  });
});

describe('the world package version', () => {
  it('a slot generated by another package version ends the session and says why', async () => {
    const room = makeRoom();
    room.slotData = { ...(room.slotData as Record<string, unknown>), worldVersion: '0.0.9' };
    const { session, core, server } = await boot(room);
    expect(session.status).toBe('error');
    expect(core.disarms).toBeGreaterThan(0);
    expect(server.of('LocationScouts')).toHaveLength(0);
    expect(parseSlotData(room.slotData)).toEqual({
      kind: 'version',
      message: `World package version 0.0.9 does not match this app (${AP_WORLD_VERSION}). `
        + 'Regenerate the game with the package this app saves.',
    });
  });
});
