/* @layer tests @kind test */
/**
 * The world package plays the same game as the local generator (plan step 4).
 *
 * Always, with no Archipelago install needed:
 *   - every location and exit keeps ONE tree shape under any options and any seed, so the
 *     widest world's trees the package ships are every world's trees (settings are `option`
 *     leaves, rolled values `seed` leaves);
 *   - a profile's world model balances: every present location is an event, a prize, a locked
 *     spot, a dungeon-item spot or a pool item's spot, one item each.
 *
 * With C:\ProgramData\Archipelago (or ROTP_AP_DIR) present, skipped with a notice otherwise:
 *   - forward: 20 seeds generated by ArchipelagoGenerate.exe from the package, each spoiler's
 *     placement replayed through our rules sphere by sphere, then swept: beaten, fully reachable;
 *   - reverse: 20 of our own placements handed to the generator with every location locked,
 *     so its own beatability and accessibility checks judge them with the package's Python rules.
 * The built package is copied into the install's custom_worlds when it differs; the install's
 * Players/ and output/ folders are never touched.
 */
import { describe, expect, it } from 'vitest';
import { generateFromSnapshot } from '@shared/randomizer/generate';
import { widestRuledWorld } from '@shared/randomizer/archipelago/export/widest-world';
import { preRolledOfFillWorld, profileFillWorld } from '@shared/randomizer/archipelago/pre-rolled';
import { renderPlayerYaml } from '@shared/randomizer/archipelago/player-yaml';
import { buildFillWorld } from '@shared/randomizer/world/fill/fill-world';
import { fillOptionsFromSnapshot } from '@shared/randomizer/world/fill/fill-options-from-snapshot';
import { EVENT_ITEMS } from '@shared/randomizer/world/pool/event-items.data';
import { snapshotOf, worldOfSnapshot } from './rule-parity-harness';
import { parseApSpoiler } from './ap-spoiler';
import { generate, hasArchipelago, installWorldPackage } from './apworld-rig';
import { replayForward, reversePlayerYaml } from './apworld-replay';
import type { OptionValue } from '@shared/randomizer/world/options.type';

const SHAPE_CASES: readonly Record<string, OptionValue>[] = [
  {},
  { include_npc_checks: false, include_world_items: false },
  { key_drop_shuffle: false },
  {
    capacity_explosives_mode: 'vanilla', capacity_projectiles_mode: 'vanilla', capacity_meter_mode: 'vanilla',
    capacity_wallet_mode: 'vanilla', pond_capacity_mode: 'capacity',
  },
  { pond_capacity_mode: 'capacity', pond_wishing_mode: 'vanilla-cost', pond_cursed_mode: 'vanilla-cost', shop_item_slots: 12 },
  { retro_bow: true, shop_item_slots: 6 },
  { story_pedestal_gate: 'anyThreeDungeons', crystals_needed_for_gt: 4, dark_room_light_lamp: false },
];

const SEEDS = 20;
/** Event locations, which a spoiler's Locations section may leave out. */
const EVENTS = EVENT_ITEMS.size;
const FORWARD_SEED = 'apworld-oracle';

describe('the exported trees and model', () => {
  it('keep one tree shape per location and exit under every option set', () => {
    const widest = widestRuledWorld();
    for (const over of SHAPE_CASES) {
      const { world } = worldOfSnapshot(over);
      const differ = [...world.locationRules, ...world.rules]
        .filter(([name, rule]) => {
          const wide = widest.locationRules.get(name as never) ?? widest.rules.get(name);
          return JSON.stringify(wide?.node) !== JSON.stringify(rule.node);
        })
        .map(([name]) => name);
      expect(differ, JSON.stringify(over)).toEqual([]);
    }
  }, 600_000);

  it('balances every present location against one item', () => {
    for (const over of SHAPE_CASES) {
      const model = preRolledOfFillWorld(profileFillWorld(FORWARD_SEED, snapshotOf(over)), snapshotOf(over)).world;
      const pooled = Object.values(model.pool).reduce((sum, count) => sum + count, 0);
      const spoken = pooled + model.dungeonItems.length + Object.keys(model.locked).length
        + Object.keys(model.events).length + Object.keys(model.prizes.vanilla).length;
      expect(spoken, JSON.stringify(over)).toBe(model.present.length);
    }
  }, 600_000);
});

const describeAp = hasArchipelago() ? describe : describe.skip;
if (!hasArchipelago()) console.log('apworld oracle: ArchipelagoGenerate.exe not found, the generator half is skipped');

describeAp('the world package against Archipelago', () => {
  it('installs the built package', () => {
    console.log(`apworld oracle: ${installWorldPackage()}`);
  }, 600_000);

  it(`generates ${SEEDS} seeds our rules beat sphere by sphere`, async () => {
    const snapshot = snapshotOf({});
    const yaml = renderPlayerYaml({ slotName: 'Oracle', options: snapshot, seedText: FORWARD_SEED });
    for (let seed = 1; seed <= SEEDS; seed += 1) {
      const run = await generate(yaml, seed);
      expect(run.ok && run.spoiler !== null, run.log.slice(-2000)).toBe(true);
      const spoiler = parseApSpoiler(run.spoiler ?? '');
      const fillWorld = profileFillWorld(FORWARD_SEED, snapshot);
      expect(spoiler.placements.size, `seed ${seed}`).toBeGreaterThanOrEqual(fillWorld.world.locationsByKey.size - EVENTS);
      const verdict = replayForward(fillWorld, spoiler);
      expect(verdict, `seed ${seed}`).toEqual({ unknown: [], sphereMisses: [], unreachable: [], beaten: true });
    }
  }, 1_800_000);

  it(`accepts ${SEEDS} of our placements under its own rules`, async () => {
    const snapshot = snapshotOf({});
    for (let index = 0; index < SEEDS; index += 1) {
      const seed = `apworld-reverse-${index}`;
      const placement = generateFromSnapshot(seed, snapshot);
      const fillWorld = buildFillWorld({
        ...fillOptionsFromSnapshot(snapshot, {}, {}, seed),
        shopPrices: placement.shopPrices ?? {},
        ...(placement.pondDemands === undefined ? {} : { pondDemands: placement.pondDemands }),
      });
      const run = await generate(reversePlayerYaml(seed, snapshot, fillWorld, placement), index + 1,
        ['--skip_prog_balancing']);
      expect(run.ok, `${seed}: ${run.log.slice(-2000)}`).toBe(true);
      expect(run.log, seed).not.toMatch(/Could not access required locations|not fulfilled|unbeatable/i);
      expect(run.spoiler ?? '', seed).not.toMatch(/^Unreachable Items:/m);
    }
  }, 1_800_000);
});
