/* @layer shared-game @kind data */
/**
 * Names the reference generator leaves without any access rule — the
 * explicit always-open lists. Everything the graph evaluates must appear
 * either in a rule table or here; the registration pass registers anything
 * else as blocked and reports it, so a forgotten rule can never silently
 * open. Derived by elimination against tests/fixtures/ap-source/Rules.py
 * (no set_rule/add_rule row targets these under the baseline options) and
 * pinned by tests/randomizer/ap-world-rules.test.ts.
 */
import { POND_EXTRA_LOCATIONS } from '../../pond/pond-locations.data';

const ALWAYS_OPEN_EXITS: readonly string[] = [
  'Agahnims Tower Exit',
  'Aginahs Cave',
  'Archery Game',
  'Bat Cave Cave',
  'Bat Cave Door',
  'Bat Cave Drop',
  'Bat Cave Exit',
  'Big Bomb Shop',
  'Blacksmiths Hut',
  'Blinds Hideout',
  'Bumper Cave (Bottom)',
  'Bumper Cave (Top)',
  'Bumper Cave Entrance Drop',
  'Bumper Cave Ledge Drop',
  'Bush Covered House',
  'C-Shaped House',
  'Capacity Upgrade',
  'Cave 45',
  'Cave Shop (Dark Death Mountain)',
  'Cave Shop (Lake Hylia)',
  'Chest Game',
  'Chicken House',
  'Chris Houlihan Room Exit',
  'Dam',
  'Dark Death Mountain Drop (East)',
  'Dark Death Mountain Drop (West)',
  'Dark Death Mountain Fairy',
  'Dark Death Mountain Ledge (East)',
  'Dark Death Mountain Ledge (West)',
  'Dark Desert Fairy',
  'Dark Desert Hint',
  'Dark Lake Hylia Fairy',
  'Dark Lake Hylia Ledge',
  'Dark Lake Hylia Ledge Hint',
  'Dark Lake Hylia Shop',
  'Dark Sanctuary Hint',
  'Dark World Lumberjack Shop',
  'Dark World Potion Shop',
  'Death Mountain Drop',
  'Death Mountain Entrance Drop',
  'Death Mountain Return Cave (East)',
  'Death Mountain Return Cave (West)',
  'Death Mountain Return Ledge Drop',
  'Death Mountain Teleporter',
  'Desert Fairy',
  'Desert Palace Entrance (East)',
  'Desert Palace Entrance (North)',
  'Desert Palace Entrance (South)',
  'Desert Palace Entrance (West)',
  'Desert Palace Exit (East)',
  'Desert Palace Exit (North)',
  'Desert Palace Exit (South)',
  'Desert Palace Exit (West)',
  'Desert Palace Pots (Inner)',
  'Desert Palace Pots (Outer)',
  'Desert Palace Stairs Drop',
  'East Dark World Hint',
  'East Dark World Pier',
  'East Death Mountain Drop',
  'Eastern Palace',
  'Eastern Palace Exit',
  'Elder House (East)',
  'Elder House (West)',
  'Elder House Exit (East)',
  'Elder House Exit (West)',
  'Fairy Ascension Cave (Bottom)',
  'Fairy Ascension Cave (Top)',
  'Fairy Ascension Cave Climb',
  'Fairy Ascension Cave Drop',
  'Fairy Ascension Cave Exit (Bottom)',
  'Fairy Ascension Cave Exit (Top)',
  'Fairy Ascension Cave Pots',
  'Fairy Ascension Drop',
  'Fairy Ascension Ledge',
  'Fairy Ascension Ledge Drop',
  'Floating Island Drop',
  'Fortune Teller (Dark)',
  'Fortune Teller (Light)',
  'Ganons Tower (Bottom) (West)',
  'Ganons Tower Exit',
  'Good Bee Cave',
  'Graveyard Cave',
  'Hookshot Cave Back Entrance',
  'Hookshot Cave Exit (North)',
  'Hookshot Fairy',
  'Hyrule Castle Entrance (East)',
  'Hyrule Castle Entrance (South)',
  'Hyrule Castle Entrance (West)',
  'Hyrule Castle Exit (South)',
  'Hyrule Castle Ledge Courtyard Drop',
  'Hyrule Castle Secret Entrance Drop',
  'Hyrule Castle Secret Entrance Exit',
  'Hyrule Castle Secret Entrance Stairs',
  'Ice Palace',
  'Ice Palace Exit',
  'Kakariko Gamble Game',
  'Kakariko Shop',
  'Kakariko Well (top to bottom)',
  'Kakariko Well Cave',
  'Kakariko Well Drop',
  'Kakariko Well Exit',
  'Lake Hylia Fairy',
  'Lake Hylia Fortune Teller',
  'Library',
  'Links House',
  'Links House Exit',
  'Long Fairy Cave',
  'Lost Woods Gamble',
  'Lost Woods Hideout (top to bottom)',
  'Lost Woods Hideout Drop',
  'Lost Woods Hideout Exit',
  'Lost Woods Hideout Stump',
  'Lumberjack House',
  'Lumberjack Tree (top to bottom)',
  'Lumberjack Tree Cave',
  'Lumberjack Tree Exit',
  'Master Sword Meadow',
  'Mimic Cave',
  'Mire Shed',
  'Misery Mire Exit',
  'North Fairy Cave',
  'North Fairy Cave Drop',
  'North Fairy Cave Exit',
  'Old Man Cave (East)',
  'Old Man Cave (West)',
  'Old Man House (Bottom)',
  'Old Man House (Top)',
  'Old Man House Exit (Bottom)',
  'Old Man House Exit (Top)',
  'Palace of Darkness Exit',
  'Palace of Darkness Hint',
  'Paradox Cave (Bottom)',
  'Paradox Cave (Middle)',
  'Paradox Cave (Top)',
  'Paradox Cave Drop',
  'Paradox Cave Exit (Bottom)',
  'Paradox Cave Exit (Middle)',
  'Paradox Cave Exit (Top)',
  'Paradox Cave Push Block',
  'Potion Shop',
  'Pyramid Drop',
  'Pyramid Entrance',
  'Pyramid Exit',
  'Red Shield Shop',
  'Sahasrahlas Hut',
  'Sanctuary',
  'Sanctuary Exit',
  'Sanctuary Push Door',
  'Sewer Drop',
  'Sick Kids House',
  'Skull Woods Final Section Exit',
  'Skull Woods First Section Door',
  'Skull Woods First Section Exit',
  'Skull Woods First Section Hole (East)',
  'Skull Woods First Section Hole (West)',
  'Skull Woods Forest',
  'Skull Woods Second Section Door (East)',
  'Skull Woods Second Section Door (West)',
  'Skull Woods Second Section Exit (East)',
  'Skull Woods Second Section Exit (West)',
  'Snitch Lady (East)',
  'Snitch Lady (West)',
  'Spectacle Rock Cave',
  'Spectacle Rock Cave (Bottom)',
  'Spectacle Rock Cave Drop',
  'Spectacle Rock Cave Exit',
  'Spectacle Rock Cave Exit (Peak)',
  'Spectacle Rock Cave Exit (Top)',
  'Spectacle Rock Cave Peak',
  'Spectacle Rock Cave Peak Drop',
  'Spectacle Rock Drop',
  'Spike Cave',
  'Spiral Cave',
  'Spiral Cave (Bottom)',
  'Spiral Cave (top to bottom)',
  'Spiral Cave Exit',
  'Spiral Cave Exit (Top)',
  'Spiral Cave Ledge Access',
  'Spiral Cave Ledge Drop',
  'Superbunny Cave (Bottom)',
  'Superbunny Cave (Top)',
  'Superbunny Cave Climb',
  'Superbunny Cave Exit (Top)',
  'Swamp Palace',
  'Swamp Palace Exit',
  'Tavern (Front)',
  'Tavern North',
  'Thieves Town Exit',
  'Tower of Hera',
  'Tower of Hera Exit',
  'Turtle Rock Big Key Door Reverse',
  'Turtle Rock Drop',
  'Turtle Rock Isolated Ledge Entrance',
  'Turtle Rock Isolated Ledge Exit',
  'Turtle Rock Ledge Exit (West)',
  'Two Brothers House (East)',
  'Two Brothers House (West)',
  'Uncle S&Q',
  'Village of Outcasts Drop',
  'Village of Outcasts Shop',
];

const ALWAYS_OPEN_LOCATIONS: readonly string[] = [
  'Blind\'s Hideout - Far Left',
  'Blind\'s Hideout - Far Right',
  'Blind\'s Hideout - Left',
  'Blind\'s Hideout - Right',
  'Bonk Rock Cave',
  'Bottle Merchant',
  'Bumper Cave Ledge',
  'Capacity Upgrade Left',
  // The pond's own prize slots (pond/pond-locations.data.ts) — reachable
  // exactly when the pond is, so the wallet overlay is their only gate.
  ...POND_EXTRA_LOCATIONS,
  'Capacity Upgrade Right',
  'Capacity Upgrade Shop',
  'Cave 45',
  'Checkerboard Cave',
  'Desert Ledge',
  'Desert Palace - Compass Chest',
  'Desert Palace - Desert Tiles 1 Pot Key',
  'Desert Palace - Map Chest',
  'Eastern Palace - Cannonball Chest',
  'Eastern Palace - Compass Chest',
  'Eastern Palace - Map Chest',
  'Floating Island',
  'Floodgate',
  'Floodgate Chest',
  'Hobo',
  'Hype Cave - Generous Guy',
  'Hyrule Castle - Map Chest',
  'Ice Rod Cave',
  'Kakariko Tavern',
  'Kakariko Well - Bottom',
  'Kakariko Well - Left',
  'Kakariko Well - Middle',
  'Kakariko Well - Right',
  'King Zora',
  'King\'s Tomb',
  'Lake Hylia Island',
  'Link\'s House',
  'Link\'s Uncle',
  'Lost Woods Hideout',
  'Lumberjack Tree',
  'Maze Race',
  'Mushroom',
  'Peg Cave',
  'Pyramid',
  'Sanctuary',
  'Secret Passage',
  'Sewers - Secret Room - Left',
  'Sewers - Secret Room - Middle',
  'Sewers - Secret Room - Right',
  'Spectacle Rock',
  'Spectacle Rock Cave',
  'Spiral Cave',
  'Tower of Hera - Compass Chest',
  'Waterfall Fairy - Left',
  'Waterfall Fairy - Right',
];

export { ALWAYS_OPEN_EXITS, ALWAYS_OPEN_LOCATIONS };
