/* @layer shared-game @kind generated */
/**
 * GENERATED by core/wasm-build/layout-probe.mjs. Do not edit by hand.
 *
 * The save state layout this build produces, as the ordered sequence of snapshot region
 * lengths and the id derived from it. Committed on purpose: it is what lets typecheck and
 * the release gate see the layout without building wasm, and it makes a layout change show
 * up as a reviewable diff.
 */
const CURRENT_STATE_FORMAT = {
  id: '6895039d1993',
  regions: [27, 65536, 40, 3025, 15, 188, 65536, 10, 512, 556, 520, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 123, 8192, 58, 131072, 4],
  totalBytes: 275462,
} as const;

export { CURRENT_STATE_FORMAT };
