/* @layer shared @kind data */

/** Read-only catalogue of everything the Game Boy Advance release changes. This is
  * @kind data, which is why the game's own proper names are allowed here while code,
  * labels and comments elsewhere must stay neutral. */

import type { GbaDifference } from './gba-difference.type';

const GBA_DIFFERENCES: GbaDifference[] = [
  {
    id: 'extra-dungeon',
    group: 'Extra content',
    label: 'Extra Dungeon',
    detail: 'Post-game dungeon entered from the east side of the Pyramid. 12 room ids, headers, three baked 64×64 layers each, collision, graphics and palettes all extracted.',
    evidence: 'extracted',
  },
  {
    id: 'four-shard-mini-bosses',
    group: 'Extra content',
    label: 'Four shard mini-bosses',
    detail: 'Palette-swapped, strengthened versions of the first four Dark World bosses, one behind each door of the main chamber. Entity ids 0x92, 0x8c/0x8d, 0x88, 0xce.',
    evidence: 'extracted',
  },
  {
    id: 'four-dark-links',
    group: 'Extra content',
    label: 'Four Dark Links',
    detail: 'Final fight, one at a time: green (sword + dash), red (adds the spin technique), blue (adds downthrust + cape), purple (adds sword fire). Each keeps the previous one\'s moves.',
    evidence: 'documented',
  },
  {
    id: 'dungeon-gatekeeper',
    group: 'Extra content',
    label: 'Dungeon gatekeeper',
    detail: 'Entity type 0xF5, handler at 0x080E5570. A second marker type 0xF8 has no dispatch entry at all and is still unexplained.',
    evidence: 'extracted',
  },
  {
    id: 'dungeon-only-room-tags',
    group: 'Extra content',
    label: 'Dungeon-only room tags',
    detail: 'Tags 0x40, 0x41, 0x42 appended to a 67-entry handler table at 0x08152AC4; effects traced down to sound ids and room-state writes.',
    evidence: 'extracted',
  },
  {
    id: 'riddle-quest',
    group: 'Extra content',
    label: 'Riddle quest',
    detail: 'Ten-riddle sidequest from the lumberjack, gated on the bug net plus ten medals from the linked multiplayer game. Dialogue occupies message ids 0x1A8–0x1C6.',
    evidence: 'extracted',
  },
  {
    id: 'riddle-answers',
    group: 'Extra content',
    label: 'Riddle answers',
    detail: 'Cucco, sand crab, red rupee, fish, small octoballoon, slime, squirrel, decoy sword, apple, cukeman. Each caught with the net into a basket that replaces the "?" inventory slot.',
    evidence: 'documented',
  },
  {
    id: 'spin-technique-reward',
    group: 'Extra content',
    label: 'Spin technique reward',
    detail: 'Granted for all ten riddles. Stored as bit 0x02 of byte 0 of each 0x500-byte save slot from SRAM offset 0x580.',
    evidence: 'extracted',
  },
  {
    id: 'sword-beam-power-bit',
    group: 'Extra content',
    label: 'Sword-beam power bit',
    detail: 'Bit 0x01 of the same save byte, tracked separately from the spin technique.',
    evidence: 'extracted',
  },
  {
    id: 'three-wooden-carvings',
    group: 'Extra content',
    label: 'Three wooden carvings',
    detail: 'Placed in the player\'s house after the first, fourth and seventh riddle.',
    evidence: 'documented',
  },
  {
    id: 'bee-and-fairy-shop',
    group: 'Extra content',
    label: 'Bee and fairy shop',
    detail: 'New shop in the Village of Outcasts selling bees, fairies and golden bees.',
    evidence: 'documented',
  },
  {
    id: 'shield-shop',
    group: 'Extra content',
    label: 'Shield shop',
    detail: 'New shop west of the Pyramid replacing the old one, stocking all three shields.',
    evidence: 'documented',
  },
  {
    id: 'ninth-flute-warp',
    group: 'Extra content',
    label: 'Ninth flute warp',
    detail: 'Extra warp point at the uncovered Turtle Rock portal.',
    evidence: 'documented',
  },
  {
    id: 'extra-light-world-cave',
    group: 'Extra content',
    label: 'Extra Light World cave',
    detail: 'Reached by mirror from the ledge outside Turtle Rock; contains Eyegores where the original had Goriyas.',
    evidence: 'documented',
  },
  {
    id: 'quest-record',
    group: 'Extra content',
    label: 'Quest record',
    detail: 'End credits gain a record of item usage, plus dungeon levels and Dark World bosses.',
    evidence: 'documented',
  },
  {
    id: 'level-4-sword-breaks-pots',
    group: 'Combat & items',
    label: 'Level-4 sword breaks pots',
    detail: 'The golden sword smashes pots and skulls; lower swords do not.',
    evidence: 'documented',
  },
  {
    id: 'swords-cut-signs',
    group: 'Combat & items',
    label: 'Swords cut signs',
    detail: 'Master, tempered and golden swords cut signposts, with a new sound and graphic.',
    evidence: 'documented',
  },
  {
    id: 'arrows-break-pots',
    group: 'Combat & items',
    label: 'Arrows break pots',
    detail: 'Regular arrows break one pot; silver arrows pass through several.',
    evidence: 'documented',
  },
  {
    id: 'magic-powder-breaks-pots',
    group: 'Combat & items',
    label: 'Magic powder breaks pots',
    detail: 'Powder now destroys breakable objects.',
    evidence: 'documented',
  },
  {
    id: 'hammer-clears-rocks-and-bushes',
    group: 'Combat & items',
    label: 'Hammer clears rocks and bushes',
    detail: 'The magic hammer breaks light-coloured stones and bushes.',
    evidence: 'documented',
  },
  {
    id: 'lamp-damages-enemies',
    group: 'Combat & items',
    label: 'Lamp damages enemies',
    detail: 'The lantern flame itself deals damage.',
    evidence: 'documented',
  },
  {
    id: 'fire-rod-burns-a-row',
    group: 'Combat & items',
    label: 'Fire rod burns a row',
    detail: 'The beam clears a whole row of bushes, stopping at enemies.',
    evidence: 'documented',
  },
  {
    id: 'red-boomerang-cuts',
    group: 'Combat & items',
    label: 'Red boomerang cuts',
    detail: 'Cuts signs, grass and bushes.',
    evidence: 'documented',
  },
  {
    id: 'sword-picks-up-items',
    group: 'Combat & items',
    label: 'Sword picks up items',
    detail: 'Rupees and drops can be collected with a sword swing.',
    evidence: 'documented',
  },
  {
    id: 'magic-refills-on-pickup',
    group: 'Combat & items',
    label: 'Magic refills on pickup',
    detail: 'Obtaining a magic-consuming item tops the meter up.',
    evidence: 'documented',
  },
  {
    id: 'four-direction-shovel',
    group: 'Combat & items',
    label: 'Four-direction shovel',
    detail: 'Digs in all four directions instead of only left and right.',
    evidence: 'documented',
  },
  {
    id: 'shovel-and-flute-both-kept',
    group: 'Combat & items',
    label: 'Shovel and flute both kept',
    detail: 'The flute no longer replaces the shovel in the inventory.',
    evidence: 'documented',
  },
  {
    id: 'diving',
    group: 'Combat & items',
    label: 'Diving',
    detail: 'The flippers allow a brief dive underwater.',
    evidence: 'documented',
  },
  {
    id: 'spin-slash-cuts-nine-tiles',
    group: 'Combat & items',
    label: 'Spin slash cuts nine tiles',
    detail: 'The 3×3 spin now also cuts the tile the player is standing on.',
    evidence: 'documented',
  },
  {
    id: 'sparkling-rocks',
    group: 'World & exploration',
    label: 'Sparkling rocks',
    detail: 'Small white overworld rocks glitter; slashing yields rupees and then bombs, once per save file.',
    evidence: 'documented',
  },
  {
    id: 'broken-bridge-marker',
    group: 'World & exploration',
    label: 'Broken bridge marker',
    detail: 'A visible broken bridge added in the north-west Dark World where the hookshot is required.',
    evidence: 'documented',
  },
  {
    id: 'ice-palace-puzzle-redesigned',
    group: 'World & exploration',
    label: 'Ice Palace puzzle redesigned',
    detail: 'The cane puzzle is reworked to block a sequence break.',
    evidence: 'documented',
  },
  {
    id: 'desert-enemies',
    group: 'World & exploration',
    label: 'Desert enemies',
    detail: 'More frequent and faster than the original.',
    evidence: 'documented',
  },
  {
    id: 'cemetery-jumping',
    group: 'World & exploration',
    label: 'Cemetery jumping',
    detail: 'The player can jump from the gravestones.',
    evidence: 'documented',
  },
  {
    id: 'treasure-field-simplified',
    group: 'World & exploration',
    label: 'Treasure field simplified',
    detail: 'The heart-piece digging game is made easier.',
    evidence: 'documented',
  },
  {
    id: 'talking-trees-reordered',
    group: 'World & exploration',
    label: 'Talking trees reordered',
    detail: 'Angry Dark World trees speak before spitting bombs rather than after.',
    evidence: 'documented',
  },
  {
    id: 'land-mines-need-contact',
    group: 'World & exploration',
    label: 'Land mines need contact',
    detail: 'Dashing past no longer sets them off.',
    evidence: 'documented',
  },
  {
    id: 'more-fairies',
    group: 'World & exploration',
    label: 'More fairies',
    detail: 'Fairies spawn more often.',
    evidence: 'documented',
  },
  {
    id: 'modified-secret-lists',
    group: 'World & exploration',
    label: 'Modified secret lists',
    detail: 'Of 320 rooms, 316 secret lists are byte-identical to the original; only 0x9E, 0xBD, 0xBE and 0xFC differ.',
    evidence: 'extracted',
  },
  {
    id: 'modified-spawn-lists',
    group: 'World & exploration',
    label: 'Modified spawn lists',
    detail: '284 of 320 shared rooms have identical spawn lists; 36 differ, and the table carries 64 extra room ids for 384 total.',
    evidence: 'extracted',
  },
  {
    id: 'white-flash-on-hit',
    group: 'Enemies & bosses',
    label: 'White flash on hit',
    detail: 'Enemies and bosses flash white and shake instead of cycling through colours.',
    evidence: 'documented',
  },
  {
    id: 'shield-eating-like-like',
    group: 'Enemies & bosses',
    label: 'Shield-eating Like Like',
    detail: 'New one near the Dark World shield shop; it can swallow even the mirror shield and fly off with it.',
    evidence: 'documented',
  },
  {
    id: 'dark-room-flames',
    group: 'Enemies & bosses',
    label: 'Dark room flames',
    detail: 'In the dark Palace of Darkness room, fire-breathers\' flames are only visible inside the lantern cone.',
    evidence: 'documented',
  },
  {
    id: 'floating-enemy-bombs',
    group: 'Enemies & bosses',
    label: 'Floating enemy bombs',
    detail: 'Bombs dropped in water float instead of sinking, and lose their ripple.',
    evidence: 'documented',
  },
  {
    id: 'viewport-240x160',
    group: 'Presentation',
    label: 'Viewport 240×160',
    detail: 'Against 256×224 on the original, so the view is cropped rather than scaled.',
    evidence: 'documented',
  },
  {
    id: 'cartridge-select-title-screen',
    group: 'Presentation',
    label: 'Cartridge-select title screen',
    detail: 'A new screen chooses between the two games on the cartridge.',
    evidence: 'documented',
  },
  {
    id: 'retouched-logo-and-palette',
    group: 'Presentation',
    label: 'Retouched logo and palette',
    detail: 'Altered logo and sword art, different text colours, a lighter overall palette, and a "Press Start" prompt.',
    evidence: 'documented',
  },
  {
    id: 'skippable-opening',
    group: 'Presentation',
    label: 'Skippable opening',
    detail: 'The opening relic sequence is skippable on existing files, with a single white flash instead of colour cycling.',
    evidence: 'documented',
  },
  {
    id: 'unskippable-new-game-intro',
    group: 'Presentation',
    label: 'Unskippable new-game intro',
    detail: 'The story moves from the attract loop to the start of a new game and cannot be skipped.',
    evidence: 'documented',
  },
  {
    id: 'dungeon-name-on-entry',
    group: 'Presentation',
    label: 'Dungeon name on entry',
    detail: 'Name and, in the Dark World, level number appear when entering.',
    evidence: 'documented',
  },
  {
    id: 'secondary-item-relocated',
    group: 'Presentation',
    label: 'Secondary item relocated',
    detail: 'Moved to the opposite side of the HUD, next to the heart meter.',
    evidence: 'documented',
  },
  {
    id: 'life-removed',
    group: 'Presentation',
    label: '"- Life -" removed',
    detail: 'The label above the heart meter is gone.',
    evidence: 'documented',
  },
  {
    id: 'maxed-counters-turn-yellow',
    group: 'Presentation',
    label: 'Maxed counters turn yellow',
    detail: 'Rupees, arrows and bombs go yellow at maximum, and lose the italic slant.',
    evidence: 'documented',
  },
  {
    id: 'compacted-inventory',
    group: 'Presentation',
    label: 'Compacted inventory',
    detail: 'No gaps between menu blocks, and a single font where the original used three.',
    evidence: 'documented',
  },
  {
    id: 'bottles-listed-individually',
    group: 'Presentation',
    label: 'Bottles listed individually',
    detail: 'Four separate slots instead of one icon opening a sub-menu.',
    evidence: 'documented',
  },
  {
    id: 'parenthesis-cursor',
    group: 'Presentation',
    label: 'Parenthesis cursor',
    detail: 'The green circle selector becomes green parentheses.',
    evidence: 'documented',
  },
  {
    id: 'running-file-select-sprite',
    group: 'Presentation',
    label: 'Running file-select sprite',
    detail: 'The player character runs on the file-select screen instead of standing.',
    evidence: 'documented',
  },
  {
    id: 'maiden-text-clears-per-paragraph',
    group: 'Presentation',
    label: 'Maiden text clears per paragraph',
    detail: 'Matches the original Japanese release rather than scrolling.',
    evidence: 'documented',
  },
  {
    id: 'witch\'s-assistant-redesigned',
    group: 'Presentation',
    label: "Witch's assistant redesigned",
    detail: 'Redrawn to match the character from the Oracle games.',
    evidence: 'documented',
  },
  {
    id: 'glove-no-longer-recolours-hands',
    group: 'Presentation',
    label: 'Glove no longer recolours hands',
    detail: 'The power glove and its upgrade leave the player\'s hand colour alone.',
    evidence: 'documented',
  },
  {
    id: 'eastern-palace-floor-tile-redrawn',
    group: 'Presentation',
    label: 'Eastern Palace floor tile redrawn',
    detail: 'A distinctive floor tile is redesigned, differing from every earlier release.',
    evidence: 'documented',
  },
  {
    id: 'pulsating-big-bomb',
    group: 'Presentation',
    label: 'Pulsating big bomb',
    detail: 'Animates while being dragged, with a new timer font.',
    evidence: 'documented',
  },
  {
    id: 'bobbing-fountain-items',
    group: 'Presentation',
    label: 'Bobbing fountain items',
    detail: 'Items in the Great Fairy fountain float up and down.',
    evidence: 'documented',
  },
  {
    id: 'bunny-beam-keeps-mail-colour',
    group: 'Presentation',
    label: 'Bunny beam keeps mail colour',
    detail: 'Previously always green regardless of the mail worn.',
    evidence: 'documented',
  },
  {
    id: 'no-dust-when-bombing-walls',
    group: 'Presentation',
    label: 'No dust when bombing walls',
    detail: 'The falling dust effect is gone.',
    evidence: 'documented',
  },
  {
    id: 'lamp-cone-persists',
    group: 'Presentation',
    label: 'Lamp cone persists',
    detail: 'The light cone stays visible after torches are lit.',
    evidence: 'documented',
  },
  {
    id: 'spear-carrying-prologue-soldiers',
    group: 'Presentation',
    label: 'Spear-carrying prologue soldiers',
    detail: 'The blue soldiers in the prologue carry spears rather than swords.',
    evidence: 'documented',
  },
  {
    id: 'adjusted-item-palettes',
    group: 'Presentation',
    label: 'Adjusted item palettes',
    detail: 'Arrows, magic powder, hammer, golden sword and the boots are recoloured.',
    evidence: 'documented',
  },
  {
    id: 'voice-clips',
    group: 'Audio & voice',
    label: 'Voice clips',
    detail: 'The player character gains grunts and shouts, reusing the young voice from the 1998 3D entry.',
    evidence: 'documented',
  },
  {
    id: 'reduced-sample-quality',
    group: 'Audio & voice',
    label: 'Reduced sample quality',
    detail: 'Music and effects are resampled for the handheld\'s audio hardware.',
    evidence: 'documented',
  },
  {
    id: 'save-menu-sound',
    group: 'Audio & voice',
    label: 'Save menu sound',
    detail: 'New effect when the save menu opens and closes.',
    evidence: 'documented',
  },
  {
    id: 'pit-fall-sound',
    group: 'Audio & voice',
    label: 'Pit-fall sound',
    detail: 'New effect when a bomb or cane block drops into a pit.',
    evidence: 'documented',
  },
  {
    id: 'misery-mire-footsteps',
    group: 'Audio & voice',
    label: 'Misery Mire footsteps',
    detail: 'Changed to the standard water sound.',
    evidence: 'documented',
  },
  {
    id: 'great-fairy-harp-once',
    group: 'Audio & voice',
    label: 'Great Fairy harp once',
    detail: 'The opening chords play only on the first appearance.',
    evidence: 'documented',
  },
  {
    id: 'new-dungeon-sound-ids',
    group: 'Audio & voice',
    label: 'New dungeon sound ids',
    detail: 'The extra dungeon\'s room tags emit sounds 0x7B and 0x3B.',
    evidence: 'extracted',
  },
  {
    id: 'full-message-corpus',
    group: 'Text & naming',
    label: 'Full message corpus',
    detail: '455 messages, ids 0x000–0x1C6, behind obfuscated big-endian relative pointers with a rolling decoder at 0x08129E0C. All decoded and re-encoded through our own dialogue encoder.',
    evidence: 'extracted',
  },
  {
    id: 'retranslation',
    group: 'Text & naming',
    label: 'Retranslation',
    detail: 'Many lines rewritten to fix weak translations in the original localisation.',
    evidence: 'documented',
  },
  {
    id: 'corrected-dungeon-names',
    group: 'Text & naming',
    label: 'Corrected dungeon names',
    detail: 'Several dungeons take their official names for the first time.',
    evidence: 'documented',
  },
  {
    id: 'terminology-fixes',
    group: 'Text & naming',
    label: 'Terminology fixes',
    detail: '"good bee" becomes "golden bee", "faerie" becomes "fairy", "wise men" becomes "sages", "smithery" becomes "smithy".',
    evidence: 'documented',
  },
  {
    id: 'footwear-renamed',
    group: 'Text & naming',
    label: 'Footwear renamed',
    detail: 'The dash footwear is renamed. Sources disagree on the direction, so this one gets settled against our own extracted corpus rather than a wiki.',
    evidence: 'documented',
  },
  {
    id: 'softened-ending-line',
    group: 'Text & naming',
    label: 'Softened ending line',
    detail: 'The villain is no longer described as "totally destroyed".',
    evidence: 'documented',
  },
  {
    id: 'faster-ending-speech',
    group: 'Text & naming',
    label: 'Faster ending speech',
    detail: 'The closing wish text can be sped up.',
    evidence: 'documented',
  },
  {
    id: 'gatekeeper-dialogue',
    group: 'Text & naming',
    label: 'Gatekeeper dialogue',
    detail: 'Message ids 0x1A5–0x1A6.',
    evidence: 'extracted',
  },
  {
    id: 'save-slot-layout',
    group: 'Save & meta',
    label: 'Save slot layout',
    detail: '0x500-byte slots beginning at SRAM offset 0x580, byte 0 holding the power bitmap.',
    evidence: 'extracted',
  },
  {
    id: 'byte-reversed-sram-blocks',
    group: 'Save & meta',
    label: 'Byte-reversed SRAM blocks',
    detail: 'Some save files store eight-byte blocks reversed; the decoder accepts both and ignores erased slots.',
    evidence: 'extracted',
  },
  {
    id: 'resume-at-last-save',
    group: 'Save & meta',
    label: 'Resume at last save',
    detail: 'Loading offers the last save location rather than only the mountain cave.',
    evidence: 'documented',
  },
  {
    id: 'save-and-quit-is-free',
    group: 'Save & meta',
    label: 'Save-and-quit is free',
    detail: 'The file counter only advances on death.',
    evidence: 'documented',
  },
  {
    id: 'credits-counter-renamed',
    group: 'Save & meta',
    label: 'Credits counter renamed',
    detail: '"Total Games Played" becomes "Total Lives Used".',
    evidence: 'documented',
  },
  {
    id: 'sleep-mode',
    group: 'Save & meta',
    label: 'Sleep mode',
    detail: 'L + R + Select suspends the handheld.',
    evidence: 'documented',
  },
  {
    id: 'new-game-offer-after-clearing',
    group: 'Save & meta',
    label: 'New-game offer after clearing',
    detail: 'Finishing the extra dungeon offers a fresh start from the title screen.',
    evidence: 'documented',
  },
  {
    id: 'mothula-sword-immunity',
    group: 'Fixes',
    label: 'Mothula sword immunity',
    detail: 'Immunity to the golden sword and to the tempered spin attack is fixed.',
    evidence: 'documented',
  },
  {
    id: 'mothula-spike-immunity',
    group: 'Fixes',
    label: 'Mothula spike immunity',
    detail: 'Damage immunity when knocked into spikes is fixed.',
    evidence: 'documented',
  },
  {
    id: 'death-mountain-bomb-clouds',
    group: 'Fixes',
    label: 'Death Mountain bomb clouds',
    detail: 'The bridge exploit is closed.',
    evidence: 'documented',
  },
  {
    id: 'tower-stairs-animation',
    group: 'Fixes',
    label: 'Tower stairs animation',
    detail: 'The jump animation under the balcony is corrected to a normal walk.',
    evidence: 'documented',
  },
  {
    id: 'developer\'s-hidden-room',
    group: 'Removed',
    label: "Developer's hidden room",
    detail: 'Renamed "Top Secret Room", its telepathic tile removed, and no longer reachable by the original method.',
    evidence: 'documented',
  },
  {
    id: 'multiplayer-half',
    group: 'Removed',
    label: 'Multiplayer half',
    detail: 'The second game on the cartridge is explicitly out of scope for this port and contributes no assets.',
    evidence: 'extracted',
  },
];

export { GBA_DIFFERENCES };
