import type { RegionDefinition } from '../../../types';

export const EASTERN_PALACE_DUNGEON: RegionDefinition[] = [
  {
    id: 'ep-0x89',
    name: 'Eyegore Key Room',
    type: 'dungeon',
    inGameIndex: 0x89,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '2F North',
    gridX: 9,
    gridY: 8,
    floor: 1,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:puzzle',
    ],
  },
  {
    id: 'ep-0x99',
    name: 'Stalfos Spawn',
    type: 'dungeon',
    inGameIndex: 0x99,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '2F',
    gridX: 9,
    gridY: 9,
    floor: 1,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:connector',
    ],
  },
  {
    id: 'ep-0xa8',
    name: 'Big Chest Room',
    type: 'dungeon',
    inGameIndex: 0xA8,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F West',
    gridX: 8,
    gridY: 10,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:treasure',
    ],
  },
  {
    id: 'ep-0xa9',
    name: 'Big Key Room',
    type: 'dungeon',
    inGameIndex: 0xA9,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F Center',
    gridX: 9,
    gridY: 10,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:treasure',
    ],
  },
  {
    id: 'ep-0xaa',
    name: 'Dark Eyegore Room',
    type: 'dungeon',
    inGameIndex: 0xAA,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F East',
    gridX: 10,
    gridY: 10,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:dark_room',
    ],
  },
  {
    id: 'ep-0xb8',
    name: 'West Cannonball',
    type: 'dungeon',
    inGameIndex: 0xB8,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F West',
    gridX: 8,
    gridY: 11,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:puzzle',
    ],
  },
  {
    id: 'ep-0xb9',
    name: 'Lobby',
    type: 'dungeon',
    inGameIndex: 0xB9,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F Center',
    gridX: 9,
    gridY: 11,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:hub',
    ],
  },
  {
    id: 'ep-0xba',
    name: 'East Cannonball',
    type: 'dungeon',
    inGameIndex: 0xBA,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F East',
    gridX: 10,
    gridY: 11,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:puzzle',
    ],
  },
  {
    id: 'ep-0xc8',
    name: 'Map Chest Room',
    type: 'dungeon',
    inGameIndex: 0xC8,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F West',
    gridX: 8,
    gridY: 12,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:treasure',
    ],
  },
  {
    id: 'ep-0xc9',
    name: 'Entrance Hall',
    type: 'dungeon',
    inGameIndex: 0xC9,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F Center',
    gridX: 9,
    gridY: 12,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:entrance',
    ],
  },
  {
    id: 'ep-0xd8',
    name: 'Compass Room',
    type: 'dungeon',
    inGameIndex: 0xD8,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F SW',
    gridX: 8,
    gridY: 13,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:treasure',
    ],
  },
  {
    id: 'ep-0xd9',
    name: 'Armos Knights',
    type: 'dungeon',
    inGameIndex: 0xD9,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: 'Boss Room',
    gridX: 9,
    gridY: 13,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:boss_room',
    ],
  },
  {
    id: 'ep-0xda',
    name: 'Boss Reward',
    type: 'dungeon',
    inGameIndex: 0xDA,
    dungeon: 'Eastern Palace',
    displayName: 'Eastern Palace',
    subtitle: '1F SE',
    gridX: 10,
    gridY: 13,
    floor: 0,
    tags: [
      'world:light',
      'env:underground',
      'type:dungeon',
      'area:east_hyrule',
      'dungeon:eastern_palace',
      'role:boss_reward',
    ],
  },
];
