import type { RegionConnection } from '../../../types';
import { LW_OVERWORLD_CENTRAL_CONNECTIONS } from './central-hyrule';
import { LW_OVERWORLD_DEATH_MOUNTAIN_CONNECTIONS } from './death-mountain';
import { LW_OVERWORLD_DESERT_CONNECTIONS } from './desert';
import { LW_OVERWORLD_EAST_HYRULE_CONNECTIONS } from './east-hyrule';
import { LW_OVERWORLD_HYRULE_CASTLE_CONNECTIONS } from './hyrule-castle';
import { LW_OVERWORLD_KAKARIKO_CONNECTIONS } from './kakariko';
import { LW_OVERWORLD_LAKE_HYLIA_CONNECTIONS } from './lake-hylia';
import { LW_OVERWORLD_LOST_WOODS_CONNECTIONS } from './lost-woods';
import { LW_OVERWORLD_SOUTH_HYRULE_CONNECTIONS } from './south-hyrule';

export const LW_OVERWORLD_CONNECTIONS: RegionConnection[] = [
  ...LW_OVERWORLD_CENTRAL_CONNECTIONS,
  ...LW_OVERWORLD_DEATH_MOUNTAIN_CONNECTIONS,
  ...LW_OVERWORLD_DESERT_CONNECTIONS,
  ...LW_OVERWORLD_EAST_HYRULE_CONNECTIONS,
  ...LW_OVERWORLD_HYRULE_CASTLE_CONNECTIONS,
  ...LW_OVERWORLD_KAKARIKO_CONNECTIONS,
  ...LW_OVERWORLD_LAKE_HYLIA_CONNECTIONS,
  ...LW_OVERWORLD_LOST_WOODS_CONNECTIONS,
  ...LW_OVERWORLD_SOUTH_HYRULE_CONNECTIONS,
];
