import type { RegionConnection } from '../../../types';

/**
 * Light World overworld screen-to-screen adjacency connections.
 * Auto-generated from grid layout. Every adjacent screen pair is connected.
 */
export const LW_SCREEN_ADJACENCY_CONNECTIONS: RegionConnection[] = [
  { from: 'lw-00', to: 'lw-01', entrance: 'Lost Woods NW East to Lost Woods NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-00', to: 'lw-08', entrance: 'Lost Woods NW South to Lost Woods SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-01', to: 'lw-02', entrance: 'Lost Woods NE East to Lumberjack Estate', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-01', to: 'lw-09', entrance: 'Lost Woods NE South to Lost Woods SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-02', to: 'lw-03', entrance: 'Lumberjack Estate East to Tower of Hera NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-02', to: 'lw-0a', entrance: 'Lumberjack Estate South to Death Mountain Gateway', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-03', to: 'lw-04', entrance: 'Tower of Hera NW East to Tower of Hera NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-03', to: 'lw-0b', entrance: 'Tower of Hera NW South to Tower of Hera SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-04', to: 'lw-05', entrance: 'Tower of Hera NE East to Death Mountain Bridge NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-04', to: 'lw-0c', entrance: 'Tower of Hera NE South to Tower of Hera SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-05', to: 'lw-06', entrance: 'Death Mountain Bridge NW East to Death Mountain Bridge NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-05', to: 'lw-0d', entrance: 'Death Mountain Bridge NW South to Mountain Bridge SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-06', to: 'lw-07', entrance: 'Death Mountain Bridge NE East to Turtle Rock', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-06', to: 'lw-0e', entrance: 'Death Mountain Bridge NE South to Mountain Bridge SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-07', to: 'lw-0f', entrance: 'Turtle Rock South to Zora Falls Outskirts', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-08', to: 'lw-09', entrance: 'Lost Woods SW East to Lost Woods SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-08', to: 'lw-10', entrance: 'Lost Woods SW South to Lost Woods Outskirts', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-09', to: 'lw-0a', entrance: 'Lost Woods SE East to Death Mountain Gateway', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-09', to: 'lw-11', entrance: 'Lost Woods SE South to Kakariko Psychics', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0a', to: 'lw-0b', entrance: 'Death Mountain Gateway East to Tower of Hera SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0a', to: 'lw-12', entrance: 'Death Mountain Gateway South to Northern Pond', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0b', to: 'lw-0c', entrance: 'Tower of Hera SW East to Tower of Hera SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0b', to: 'lw-13', entrance: 'Tower of Hera SW South to Sanctuary Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0c', to: 'lw-0d', entrance: 'Tower of Hera SE East to Mountain Bridge SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0c', to: 'lw-14', entrance: 'Tower of Hera SE South to Graveyard', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0d', to: 'lw-0e', entrance: 'Mountain Bridge SW East to Mountain Bridge SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0d', to: 'lw-15', entrance: 'Mountain Bridge SW South to South Bend', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0e', to: 'lw-0f', entrance: 'Mountain Bridge SE East to Zora Falls Outskirts', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0e', to: 'lw-16', entrance: 'Mountain Bridge SE South to Coven of Commerce', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-0f', to: 'lw-17', entrance: 'Zora Falls Outskirts South to Zora Ridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-10', to: 'lw-11', entrance: 'Lost Woods Outskirts East to Kakariko Psychics', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-10', to: 'lw-18', entrance: 'Lost Woods Outskirts South to Kakariko NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-11', to: 'lw-12', entrance: 'Kakariko Psychics East to Northern Pond', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-11', to: 'lw-19', entrance: 'Kakariko Psychics South to Kakariko NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-12', to: 'lw-13', entrance: 'Northern Pond East to Sanctuary Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-12', to: 'lw-1a', entrance: 'Northern Pond South to West Woods', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-13', to: 'lw-14', entrance: 'Sanctuary Grounds East to Graveyard', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-13', to: 'lw-1b', entrance: 'Sanctuary Grounds South to Hyrule Castle NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-14', to: 'lw-15', entrance: 'Graveyard East to South Bend', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-14', to: 'lw-1c', entrance: 'Graveyard South to Hyrule Castle NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-15', to: 'lw-16', entrance: 'South Bend East to Coven of Commerce', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-15', to: 'lw-1d', entrance: 'South Bend South to Castle East Bridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-16', to: 'lw-17', entrance: 'Coven of Commerce East to Zora Ridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-16', to: 'lw-1e', entrance: 'Coven of Commerce South to Eastern Ruins NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-17', to: 'lw-1f', entrance: 'Zora Ridge South to Eastern Ruins NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-18', to: 'lw-19', entrance: 'Kakariko NW East to Kakariko NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-18', to: 'lw-20', entrance: 'Kakariko NW South to Kakariko SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-19', to: 'lw-1a', entrance: 'Kakariko NE East to West Woods', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-19', to: 'lw-21', entrance: 'Kakariko NE South to Kakariko SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1a', to: 'lw-1b', entrance: 'West Woods East to Hyrule Castle NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1a', to: 'lw-22', entrance: 'West Woods South to Smithy Estate', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1b', to: 'lw-1c', entrance: 'Hyrule Castle NW East to Hyrule Castle NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1b', to: 'lw-23', entrance: 'Hyrule Castle NW South to Hyrule Castle SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1c', to: 'lw-1d', entrance: 'Hyrule Castle NE East to Castle East Bridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1c', to: 'lw-24', entrance: 'Hyrule Castle NE South to Hyrule Castle SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1d', to: 'lw-1e', entrance: 'Castle East Bridge East to Eastern Ruins NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1d', to: 'lw-25', entrance: 'Castle East Bridge South to Moundlands', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1e', to: 'lw-1f', entrance: 'Eastern Ruins NW East to Eastern Ruins NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1e', to: 'lw-26', entrance: 'Eastern Ruins NW South to Eastern Ruins SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-1f', to: 'lw-27', entrance: 'Eastern Ruins NE South to Eastern Ruins SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-20', to: 'lw-21', entrance: 'Kakariko SW East to Kakariko SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-20', to: 'lw-28', entrance: 'Kakariko SW South to Kakariko Maze', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-21', to: 'lw-22', entrance: 'Kakariko SE East to Smithy Estate', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-21', to: 'lw-29', entrance: 'Kakariko SE South to Kakariko South Annex', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-22', to: 'lw-23', entrance: 'Smithy Estate East to Hyrule Castle SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-22', to: 'lw-2a', entrance: 'Smithy Estate South to Haunted Grove', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-23', to: 'lw-24', entrance: 'Hyrule Castle SW East to Hyrule Castle SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-23', to: 'lw-2b', entrance: 'Hyrule Castle SW South to Uncle\'s Estate West', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-24', to: 'lw-25', entrance: 'Hyrule Castle SE East to Moundlands', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-24', to: 'lw-2c', entrance: 'Hyrule Castle SE South to Uncle\'s Estate East', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-25', to: 'lw-26', entrance: 'Moundlands East to Eastern Ruins SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-25', to: 'lw-2d', entrance: 'Moundlands South to Eastern Ruins Bridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-26', to: 'lw-27', entrance: 'Eastern Ruins SW East to Eastern Ruins SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-26', to: 'lw-2e', entrance: 'Eastern Ruins SW South to Eastern Ruins Ridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-27', to: 'lw-2f', entrance: 'Eastern Ruins SE South to Eastern Cul-de-sac', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-28', to: 'lw-29', entrance: 'Kakariko Maze East to Kakariko South Annex', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-29', to: 'lw-2a', entrance: 'Kakariko South Annex East to Haunted Grove', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-29', to: 'lw-31', entrance: 'Kakariko South Annex South to Desert of Mystery NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2a', to: 'lw-2b', entrance: 'Haunted Grove East to Uncle\'s Estate West', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2a', to: 'lw-32', entrance: 'Haunted Grove South to Haunted Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2b', to: 'lw-2c', entrance: 'Uncle\'s Estate West East to Uncle\'s Estate East', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2b', to: 'lw-33', entrance: 'Uncle\'s Estate West South to Hyrule Wetlands NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2c', to: 'lw-2d', entrance: 'Uncle\'s Estate East East to Eastern Ruins Bridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2c', to: 'lw-34', entrance: 'Uncle\'s Estate East South to Hyrule Wetlands NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2d', to: 'lw-2e', entrance: 'Eastern Ruins Bridge East to Eastern Ruins Ridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2d', to: 'lw-35', entrance: 'Eastern Ruins Bridge South to Lake Hylia NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2e', to: 'lw-2f', entrance: 'Eastern Ruins Ridge East to Eastern Cul-de-sac', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2e', to: 'lw-36', entrance: 'Eastern Ruins Ridge South to Lake Hylia NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-2f', to: 'lw-37', entrance: 'Eastern Cul-de-sac South to Frosty Caves', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-30', to: 'lw-31', entrance: 'Desert of Mystery NW East to Desert of Mystery NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-30', to: 'lw-38', entrance: 'Desert of Mystery NW South to Desert of Mystery SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-31', to: 'lw-32', entrance: 'Desert of Mystery NE East to Haunted Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-31', to: 'lw-39', entrance: 'Desert of Mystery NE South to Desert of Mystery SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-32', to: 'lw-33', entrance: 'Haunted Terrace East to Hyrule Wetlands NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-32', to: 'lw-3a', entrance: 'Haunted Terrace South to Via of Mystery', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-33', to: 'lw-34', entrance: 'Hyrule Wetlands NW East to Hyrule Wetlands NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-33', to: 'lw-3b', entrance: 'Hyrule Wetlands NW South to Watergate Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-34', to: 'lw-35', entrance: 'Hyrule Wetlands NE East to Lake Hylia NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-34', to: 'lw-3c', entrance: 'Hyrule Wetlands NE South to Hyrule Wetlands Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-35', to: 'lw-36', entrance: 'Lake Hylia NW East to Lake Hylia NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-35', to: 'lw-3d', entrance: 'Lake Hylia NW South to Lake Hylia SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-36', to: 'lw-37', entrance: 'Lake Hylia NE East to Frosty Caves', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-36', to: 'lw-3e', entrance: 'Lake Hylia NE South to Lake Hylia SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-37', to: 'lw-3f', entrance: 'Frosty Caves South to Octorock Nesting Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-38', to: 'lw-39', entrance: 'Desert of Mystery SW East to Desert of Mystery SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-39', to: 'lw-3a', entrance: 'Desert of Mystery SE East to Via of Mystery', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-3a', to: 'lw-3b', entrance: 'Via of Mystery East to Watergate Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-3b', to: 'lw-3c', entrance: 'Watergate Grounds East to Hyrule Wetlands Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-3c', to: 'lw-3d', entrance: 'Hyrule Wetlands Terrace East to Lake Hylia SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-3d', to: 'lw-3e', entrance: 'Lake Hylia SW East to Lake Hylia SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'lw-3e', to: 'lw-3f', entrance: 'Lake Hylia SE East to Octorock Nesting Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
];
