/* @layer shared-game @kind data */
/**
 * What a check asks for beyond reaching its screen, in a vanilla game, as the reference
 * randomizer names the check. Applied as overrides on the checks that carry the same name.
 * Small-key counts inside a dungeon are not carried: a dungeon is one place in the tracker's
 * graph and its keys are its own; big keys, weapons and light are.
 */
import type { Requirement } from '@shared/game/data/types';
import { R } from './rule-words';

const BK = {
  eastern: R.bigKey('item-094'), desert: R.bigKey('item-093'), hera: R.bigKey('item-087'), darkness: R.bigKey('item-091'),
  swamp: R.bigKey('item-092'), skull: R.bigKey('item-089'), thieves: R.bigKey('item-086'), ice: R.bigKey('item-088'),
  mire: R.bigKey('item-090'), turtle: R.bigKey('item-085'), ganon: R.bigKey('item-084'),
};
const paradoxLower = R.any(R.bombs, R.beamSword, R.bow, R.fireRod, R.somaria);
const eyeBridge = R.any(R.byrna, R.cape);

const LOCATION_RULES: Readonly<Record<string, Requirement>> = {
  "Aginah's Cave": R.bombs,
  'Blacksmith': R.smithsReunited,
  'Missing Smith': R.frogFound,
  "Blind's Hideout - Top": R.bombs,
  'Bombos Tablet': R.all(R.book, R.beamSword),
  'Ether Tablet': R.all(R.book, R.beamSword),
  'Chicken House': R.bombs,
  'Dark Blacksmith Ruins': R.smithsReunited,
  'Purple Chest': R.purpleChestFound,
  'Flute Activation Spot': R.flute,
  'Flute Spot': R.shovel,
  'Frog': R.mitt,
  'Graveyard Cave': R.bombs,
  'Hookshot Cave - Bottom Left': R.hookshot,
  'Hookshot Cave - Bottom Right': R.any(R.hookshot, R.boots),
  'Hookshot Cave - Top Left': R.hookshot,
  'Hookshot Cave - Top Right': R.hookshot,
  'Hype Cave - Bottom': R.bombs,
  'Hype Cave - Middle Left': R.bombs,
  'Hype Cave - Middle Right': R.bombs,
  'Hype Cave - Top': R.bombs,
  'Kakariko Well - Top': R.bombs,
  'Library': R.boots,
  'Magic Bat': R.powder,
  'Master Sword Pedestal': R.pendants3,
  'Mimic Cave': R.all(R.hammer, R.any(R.bombs, R.bow, R.somaria, R.beamSword)),
  'Mini Moldorm Cave - Far Left': R.kill,
  'Mini Moldorm Cave - Far Right': R.kill,
  'Mini Moldorm Cave - Generous Guy': R.kill,
  'Mini Moldorm Cave - Left': R.kill,
  'Mini Moldorm Cave - Right': R.kill,
  'Old Man': R.lamp,
  'Paradox Cave Lower - Far Left': paradoxLower,
  'Paradox Cave Lower - Far Right': paradoxLower,
  'Paradox Cave Lower - Left': paradoxLower,
  'Paradox Cave Lower - Middle': paradoxLower,
  'Paradox Cave Lower - Right': paradoxLower,
  'Paradox Cave Upper - Left': R.bombs,
  'Paradox Cave Upper - Right': R.bombs,
  'Potion Shop': R.mushroom,
  'Sahasrahla': R.greenPendant,
  "Sahasrahla's Hut - Left": R.bombsOrBoots,
  "Sahasrahla's Hut - Middle": R.bombsOrBoots,
  "Sahasrahla's Hut - Right": R.bombsOrBoots,
  'Sick Kid': R.bottle,
  'Spike Cave': R.all(R.hammer, R.gloves, R.any(R.cape, R.byrna)),
  'Sunken Treasure': R.floodgate,
  "Zora's Ledge": R.flippers,
  'King Zora': R.any(R.flippers, R.gloves),
  'Hobo': R.flippers,
  "King's Tomb": R.boots,
  'Ganon': R.all(R.agahnim2, R.crystals7, R.beamSword, R.fireSource, R.silverBow),
  // The passage's own rupees lie past the uncle; nothing is taken there before he is met.
  'Secret Passage': R.uncleMet,
  // Dungeon chests: what they ask for beyond the door.
  'Hyrule Castle - Boomerang Chest': R.kill,
  'Hyrule Castle - Map Guard Key Drop': R.kill,
  'Hyrule Castle - Boomerang Guard Key Drop': R.kill,
  'Sewers - Key Rat Key Drop': R.kill,
  'Sewers - Secret Room - Left': R.bombsOrBoots,
  'Sewers - Secret Room - Middle': R.bombsOrBoots,
  'Sewers - Secret Room - Right': R.bombsOrBoots,
  'Castle Tower - Room 03': R.kill,
  'Castle Tower - Dark Maze': R.all(R.kill, R.lamp),
  'Castle Tower - Dark Archer Key Drop': R.all(R.kill, R.lamp),
  'Castle Tower - Circle of Pots Key Drop': R.all(R.kill, R.lamp),
  'Eastern Palace - Big Chest': BK.eastern,
  'Eastern Palace - Big Key Chest': R.all(R.kill, R.lamp),
  'Eastern Palace - Dark Square Pot Key': R.lamp,
  'Eastern Palace - Dark Eyegore Key Drop': R.all(BK.eastern, R.kill, R.lamp),
  'Eastern Palace - Boss': R.all(BK.eastern, R.bow, R.lamp),
  'Eastern Palace - Prize': R.all(BK.eastern, R.bow, R.lamp),
  'Desert Palace - Big Chest': BK.desert,
  'Desert Palace - Torch': R.boots,
  'Desert Palace - Big Key Chest': R.kill,
  'Desert Palace - Beamos Hall Pot Key': R.kill,
  'Desert Palace - Desert Tiles 2 Pot Key': R.kill,
  'Desert Palace - Boss': R.all(BK.desert, R.fireSource, R.kill),
  'Desert Palace - Prize': R.all(BK.desert, R.fireSource, R.kill),
  'Tower of Hera - Basement Cage': R.hitSwitch,
  'Tower of Hera - Map Chest': R.hitSwitch,
  'Tower of Hera - Big Key Chest': R.all(R.hitSwitch, R.fireSource),
  'Tower of Hera - Big Chest': R.all(R.hitSwitch, BK.hera),
  'Tower of Hera - Boss': R.all(R.hitSwitch, BK.hera, R.melee),
  'Tower of Hera - Prize': R.all(R.hitSwitch, BK.hera, R.melee),
  'Palace of Darkness - The Arena - Ledge': R.bombs,
  'Palace of Darkness - Dark Basement - Left': R.lamp,
  'Palace of Darkness - Dark Basement - Right': R.lamp,
  'Palace of Darkness - Big Chest': R.all(R.bombs, BK.darkness, R.lamp),
  'Palace of Darkness - Boss': R.all(BK.darkness, R.hammer, R.bow, R.lamp),
  'Palace of Darkness - Prize': R.all(BK.darkness, R.hammer, R.bow, R.lamp),
  'Swamp Palace - Map Chest': R.all(R.flippers, R.floodgate, R.mirror, R.bombs),
  'Swamp Palace - Big Chest': R.all(R.flippers, R.floodgate, R.mirror, R.hammer, BK.swamp),
  'Swamp Palace - Hookshot Pot Key': R.all(R.flippers, R.floodgate, R.mirror, R.hammer, R.hookshot),
  'Swamp Palace - Boss': R.all(R.flippers, R.floodgate, R.mirror, R.hammer, R.hookshot),
  'Swamp Palace - Prize': R.all(R.flippers, R.floodgate, R.mirror, R.hammer, R.hookshot),
  'Skull Woods - Big Chest': R.all(BK.skull, R.bombs),
  'Skull Woods - Boss': R.all(R.fireRod, R.sword),
  'Skull Woods - Prize': R.all(R.fireRod, R.sword),
  "Thieves' Town - Attic": BK.thieves,
  "Thieves' Town - Big Chest": R.all(BK.thieves, R.hammer),
  "Thieves' Town - Blind's Cell": BK.thieves,
  "Thieves' Town - Spike Switch Pot Key": BK.thieves,
  "Thieves' Town - Boss": R.all(BK.thieves, R.bombs, R.kill),
  "Thieves' Town - Prize": R.all(BK.thieves, R.bombs, R.kill),
  'Ice Palace - Jelly Key Drop': R.melt,
  'Ice Palace - Compass Chest': R.melt,
  'Ice Palace - Big Chest': R.all(R.melt, BK.ice),
  'Ice Palace - Boss': R.all(R.melt, R.gloves, R.hammer, BK.ice),
  'Ice Palace - Prize': R.all(R.melt, R.gloves, R.hammer, BK.ice),
  'Misery Mire - Big Chest': BK.mire,
  'Misery Mire - Big Key Chest': R.fireSource,
  'Misery Mire - Compass Chest': R.fireSource,
  'Misery Mire - Spike Chest': R.any(R.byrna, R.cape),
  'Misery Mire - Boss': R.all(BK.mire, R.somaria, R.bombs, R.lamp),
  'Misery Mire - Prize': R.all(BK.mire, R.somaria, R.bombs, R.lamp),
  'Turtle Rock - Compass Chest': R.somaria,
  'Turtle Rock - Roller Room - Left': R.all(R.somaria, R.fireRod),
  'Turtle Rock - Roller Room - Right': R.all(R.somaria, R.fireRod),
  'Turtle Rock - Chain Chomps': R.somaria,
  'Turtle Rock - Big Key Chest': R.somaria,
  'Turtle Rock - Big Chest': R.all(R.somaria, BK.turtle),
  'Turtle Rock - Eye Bridge - Bottom Left': R.all(R.somaria, R.lamp, eyeBridge),
  'Turtle Rock - Eye Bridge - Bottom Right': R.all(R.somaria, R.lamp, eyeBridge),
  'Turtle Rock - Eye Bridge - Top Left': R.all(R.somaria, R.lamp, eyeBridge),
  'Turtle Rock - Eye Bridge - Top Right': R.all(R.somaria, R.lamp, eyeBridge),
  'Turtle Rock - Boss': R.all(R.somaria, R.lamp, BK.turtle, R.fireRod, R.iceRod),
  'Turtle Rock - Prize': R.all(R.somaria, R.lamp, BK.turtle, R.fireRod, R.iceRod),
  "Ganons Tower - Bob's Torch": R.boots,
  'Ganons Tower - DMs Room - Top Left': R.all(R.hammer, R.hookshot),
  'Ganons Tower - DMs Room - Top Right': R.all(R.hammer, R.hookshot),
  'Ganons Tower - DMs Room - Bottom Left': R.all(R.hammer, R.hookshot),
  'Ganons Tower - DMs Room - Bottom Right': R.all(R.hammer, R.hookshot),
  'Ganons Tower - Big Chest': BK.ganon,
  'Ganons Tower - Big Key Chest': R.all(R.bombs, R.hammer, R.hookshot, R.somaria, R.fireRod),
  'Ganons Tower - Big Key Room - Left': R.all(R.bombs, R.hammer, R.hookshot, R.somaria, R.fireRod),
  'Ganons Tower - Big Key Room - Right': R.all(R.bombs, R.hammer, R.hookshot, R.somaria, R.fireRod),
  'Ganons Tower - Pre-Moldorm Chest': R.all(BK.ganon, R.bow, R.fireSource, R.bombs),
  'Ganons Tower - Moldorm Chest': R.all(BK.ganon, R.bow, R.fireSource, R.bombs, R.hookshot),
  'Agahnim 1': R.all(R.any(R.sword, R.hammer, R.net), R.lamp),
  'Agahnim 2': R.all(BK.ganon, R.bow, R.fireSource, R.bombs, R.hookshot, R.any(R.sword, R.hammer, R.net)),
};

export { LOCATION_RULES };
