/* @layer shared-game @kind data */
/**
 * The overworld of a vanilla game as the reference randomizer reasons about it: regions, the
 * caves and dungeon doors that open off them, and the rule that moves the player across each
 * edge. Names are the reference's own (Rules.py, Regions.py, EntranceShuffle.py, standard mode,
 * vanilla entrances, no glitches); screen-names.ts turns them into this dataset's screens.
 * Edges inside a dungeon are not listed: a dungeon is one place once its door is passed, and
 * what a chest asks for beyond the door is the chest's own rule (location-rules.data.ts).
 */
import type { Requirement } from '@shared/game/data/types';
import { R } from './rule-words';

interface RegionEdge {
  from: string;
  to: string;
  rule?: Requirement;
}

const e = (from: string, to: string, rule?: Requirement): RegionEdge => (rule ? { from, to, rule } : { from, to });

const LW = 'Light World';
const EDW = 'East Dark World';
const SDW = 'South Dark World';
const WDW = 'West Dark World';
const NEDW = 'Northeast Dark World';
const DM = 'Death Mountain';
const EDM_BOTTOM = 'East Death Mountain (Bottom)';
const EDM_TOP = 'East Death Mountain (Top)';
const DM_TOP = 'Death Mountain (Top)';
const DDM_WEST = 'Dark Death Mountain (West Bottom)';
const DDM_EAST = 'Dark Death Mountain (East Bottom)';
const DDM_TOP = 'Dark Death Mountain (Top)';

const REGION_EDGES: readonly RegionEdge[] = [
  // Around the lake and the river.
  e(LW, 'Lake Hylia Central Island', R.flippers),
  e('Lake Hylia Central Island', 'Dark Lake Hylia Central Island', R.mitt),
  e(LW, 'Zoras River', R.any(R.flippers, R.gloves)),
  e(LW, 'Hobo Bridge', R.flippers),
  e(LW, 'Waterfall of Wishing', R.flippers),
  // The graveyard and the castle.
  e(LW, 'Kings Grave Area', R.mitt),
  e('Kings Grave Area', LW, R.mitt),
  e(WDW, 'Kings Grave Area', R.all(R.pearl, R.mirror)),
  e('Kings Grave Area', 'Kings Grave', R.boots),
  e(LW, 'Sewer Drop', R.gloves),
  e(LW, 'Hyrule Castle Secret Entrance'),
  e('Hyrule Castle Courtyard', 'Hyrule Castle Secret Entrance'),
  e('Hyrule Castle Secret Entrance', 'Hyrule Castle Courtyard'),
  e(LW, 'Hyrule Castle Courtyard', R.mirror),
  e('Hyrule Castle Ledge', 'Hyrule Castle Courtyard'),
  e(EDW, 'Hyrule Castle Ledge', R.mirror),
  e('Hyrule Castle Courtyard', 'Hyrule Castle'),
  e('Hyrule Castle Ledge', 'Hyrule Castle'),
  e('Hyrule Castle', 'Hyrule Castle Courtyard'),
  e('Hyrule Castle', 'Hyrule Castle Ledge', R.princessSafe),
  e('Hyrule Castle Ledge', 'Agahnims Tower', R.any(R.cape, R.beamSword, R.agahnim1)),
  e('Agahnims Tower', 'Hyrule Castle Ledge'),
  e(LW, 'Sanctuary'),
  e('Sanctuary', LW, R.princessSafe),
  e(WDW, 'Graveyard Ledge', R.all(R.pearl, R.mirror)),
  e('Graveyard Ledge', 'Graveyard Cave'),
  // Kakariko and the west.
  e(LW, 'Master Sword Meadow'),
  e(LW, 'Bat Cave Drop Ledge', R.hammer),
  e('Hammer Peg Area', 'Bat Cave Drop Ledge', R.mirror),
  e('Bat Cave Drop Ledge', 'Bat Cave (right)'),
  e('Bat Cave (right)', 'Bat Cave (left)'),
  e(LW, 'Bat Cave (left)'),
  e(SDW, 'Maze Race Ledge', R.mirror),
  e('Maze Race Ledge', 'Two Brothers House'),
  e(LW, 'Two Brothers House'),
  e('Two Brothers House', LW, R.bombsOrBoots),
  e('Two Brothers House', 'Maze Race Ledge', R.bombsOrBoots),
  e(SDW, 'Cave 45 Ledge', R.mirror),
  e('Cave 45 Ledge', 'Cave 45'),
  // The desert.
  e(LW, 'Desert Palace Stairs', R.book),
  e('Dark Desert', 'Desert Palace Stairs', R.mirror),
  e('Desert Palace Lone Stairs', LW),
  e('Dark Desert', 'Desert Ledge', R.mirror),
  e('Dark Desert', 'Desert Ledge (Northeast)', R.mirror),
  e('Dark Desert', 'Desert Palace Entrance (North) Spot', R.mirror),
  e('Desert Ledge', 'Desert Palace Entrance (North) Spot', R.gloves),
  e('Desert Palace Entrance (North) Spot', 'Desert Ledge', R.gloves),
  e('Desert Ledge (Northeast)', 'Checkerboard Cave', R.gloves),
  e(SDW, 'Bombos Tablet Ledge', R.mirror),
  // The mountain.
  e(LW, DM, R.activatedFlute),
  e(LW, 'Death Mountain Entrance', R.gloves),
  e('Death Mountain Entrance', LW),
  e('Death Mountain Entrance', 'Old Man Cave'),
  e(DM, 'Old Man Cave'),
  e('Old Man Cave', DM, R.lamp),
  e(DM, 'Old Man House'),
  e('Old Man House', DM),
  e(DM, 'Old Man House Back'),
  e('Old Man House Back', DM),
  e('Old Man House', 'Old Man House Back', R.lamp),
  e('Old Man House Back', 'Old Man House', R.lamp),
  e(DM, 'Death Mountain Return Cave'),
  e('Death Mountain Return Ledge', 'Death Mountain Return Cave'),
  e('Death Mountain Return Cave', 'Death Mountain Return Ledge', R.lamp),
  e('Death Mountain Return Cave', DM, R.lamp),
  e('Death Mountain Return Ledge', LW),
  e(DM, 'Spectacle Rock Cave (Peak)'),
  e(DM, 'Spectacle Rock Cave (Bottom)'),
  e(DM, 'Spectacle Rock Cave (Top)'),
  e('Spectacle Rock Cave (Top)', 'Spectacle Rock Cave (Bottom)'),
  e('Spectacle Rock Cave (Peak)', 'Spectacle Rock Cave (Bottom)'),
  e('Spectacle Rock Cave (Bottom)', DM),
  e('Spectacle Rock Cave (Top)', DM),
  e('Spectacle Rock Cave (Peak)', DM),
  e(DM, EDM_BOTTOM, R.hookshot),
  e(EDM_BOTTOM, DM, R.hookshot),
  e(DM_TOP, DM),
  e(DM_TOP, EDM_TOP, R.hammer),
  e(EDM_TOP, DM_TOP, R.hammer),
  e('Spectacle Rock', DM_TOP),
  e(DDM_WEST, 'Spectacle Rock', R.mirror),
  e(DM_TOP, 'Tower of Hera (Bottom)'),
  e('Tower of Hera (Bottom)', DM_TOP),
  e(EDM_TOP, EDM_BOTTOM),
  e(EDM_TOP, 'Spiral Cave Ledge'),
  e('Spiral Cave Ledge', EDM_BOTTOM),
  e('Spiral Cave Ledge', 'Spiral Cave (Top)'),
  e('Spiral Cave (Top)', 'Spiral Cave (Bottom)'),
  e('Spiral Cave (Top)', 'Spiral Cave Ledge'),
  e(EDM_BOTTOM, 'Spiral Cave (Bottom)'),
  e('Spiral Cave (Bottom)', EDM_BOTTOM),
  e(EDM_BOTTOM, 'Paradox Cave Front'),
  e(EDM_BOTTOM, 'Paradox Cave'),
  e(EDM_TOP, 'Paradox Cave'),
  e('Paradox Cave Front', EDM_BOTTOM),
  e('Paradox Cave', EDM_BOTTOM),
  e('Paradox Cave', EDM_TOP),
  e('Paradox Cave', 'Paradox Cave Chest Area'),
  e('Paradox Cave Chest Area', 'Paradox Cave Front'),
  e('Paradox Cave Front', 'Light World Death Mountain Shop', R.bombs),
  e(EDM_BOTTOM, 'Hookshot Fairy'),
  e(EDM_BOTTOM, 'Fairy Ascension Plateau', R.mitt),
  e(DDM_EAST, 'Fairy Ascension Plateau', R.all(R.mirror, R.pearl)),
  e('Fairy Ascension Plateau', EDM_BOTTOM),
  e('Fairy Ascension Ledge', 'Fairy Ascension Plateau'),
  e(EDM_TOP, 'Fairy Ascension Ledge'),
  e('Fairy Ascension Plateau', 'Fairy Ascension Cave (Bottom)'),
  e('Fairy Ascension Ledge', 'Fairy Ascension Cave (Top)'),
  e('Fairy Ascension Cave (Bottom)', 'Fairy Ascension Cave (Top)'),
  e('Fairy Ascension Cave (Top)', 'Fairy Ascension Cave (Drop)'),
  e('Fairy Ascension Cave (Drop)', 'Fairy Ascension Cave (Bottom)'),
  e('Fairy Ascension Cave (Bottom)', 'Fairy Ascension Plateau'),
  e('Fairy Ascension Cave (Top)', 'Fairy Ascension Ledge'),
  e('Dark Death Mountain Isolated Ledge', 'Fairy Ascension Ledge', R.mirror),
  e('Dark Death Mountain Ledge', 'Spiral Cave Ledge', R.mirror),
  e('Dark Death Mountain Ledge', 'Mimic Cave Ledge', R.mirror),
  e('Mimic Cave Ledge', 'Mimic Cave'),
  e(DM, DDM_WEST),
  e(EDM_BOTTOM, DDM_EAST, R.mitt),
  e(EDM_TOP, 'Turtle Rock (Top)', R.all(R.mitt, R.hammer)),
  e('Turtle Rock (Top)', DDM_TOP),
  e(DDM_TOP, DDM_EAST),
  e(DDM_TOP, DDM_WEST),
  e(DDM_TOP, EDM_TOP, R.mirror),
  e('Death Mountain Floating Island (Dark World)', DDM_TOP),
  e('Death Mountain Floating Island (Dark World)', 'Death Mountain Floating Island (Light World)', R.mirror),
  e(DDM_WEST, 'Spike Cave'),
  e(DDM_TOP, 'Hookshot Cave', R.all(R.gloves, R.pearl)),
  e('Hookshot Cave', DDM_TOP),
  e('Hookshot Cave', 'Hookshot Cave (Upper)', R.bombs),
  e('Hookshot Cave (Upper)', 'Hookshot Cave', R.bombs),
  e('Hookshot Cave (Upper)', 'Death Mountain Floating Island (Dark World)'),
  e('Death Mountain Floating Island (Dark World)', 'Hookshot Cave (Upper)'),
  e(DDM_TOP, 'Superbunny Cave (Top)'),
  e('Superbunny Cave (Top)', DDM_TOP),
  e(DDM_EAST, 'Superbunny Cave (Bottom)'),
  e('Superbunny Cave (Bottom)', 'Superbunny Cave (Top)'),
  e(DDM_EAST, 'Cave Shop (Dark Death Mountain)'),
  e(DDM_WEST, 'Dark Death Mountain Healer Fairy'),
  e(DDM_TOP, 'Turtle Rock (Entrance)', R.all(R.pearl, R.sword, R.quake)),
  e('Turtle Rock (Entrance)', DDM_TOP),
  e(DDM_TOP, 'Ganons Tower (Entrance)', R.crystals7),
  e('Ganons Tower (Entrance)', DDM_TOP),
  // The dark world: the pyramid, the east and the south.
  e(LW, EDW, R.agahnim1),
  e(LW, EDW, R.all(R.hammer, R.gloves, R.pearl)),
  e(LW, SDW, R.all(R.hammer, R.gloves, R.pearl)),
  e(LW, WDW, R.all(R.any(R.all(R.hammer, R.gloves), R.mitt), R.pearl)),
  e(LW, 'Dark Desert', R.all(R.activatedFlute, R.mitt)),
  e(EDW, 'Dark Lake Hylia', R.all(R.pearl, R.flippers)),
  e(SDW, 'Dark Lake Hylia', R.all(R.pearl, R.flippers)),
  e(NEDW, 'Dark Lake Hylia', R.all(R.pearl, R.flippers)),
  e('Dark Lake Hylia', 'Dark Lake Hylia Ledge'),
  e('Dark Lake Hylia Ledge', 'Dark Lake Hylia', R.all(R.pearl, R.flippers)),
  e('Dark Lake Hylia', EDW),
  e('Dark Lake Hylia', 'Lake Hylia Island', R.all(R.pearl, R.mirror, R.flippers)),
  e('Dark Lake Hylia Central Island', 'Lake Hylia Central Island', R.mirror),
  e('Dark Lake Hylia Central Island', 'Ice Palace (Entrance)'),
  e('Ice Palace (Entrance)', 'Dark Lake Hylia Central Island'),
  e('Lake Hylia Central Island', 'Capacity Upgrade'),
  e(EDW, SDW, R.all(R.hammer, R.pearl)),
  e(SDW, EDW, R.all(R.pearl, R.hammer)),
  e(SDW, WDW, R.all(R.pearl, R.mitt)),
  e(WDW, SDW),
  e(WDW, 'Hammer Peg Area', R.all(R.pearl, R.mitt)),
  e(WDW, 'Dark Grassy Lawn', R.all(R.pearl, R.hammer)),
  e('Hammer Peg Area', WDW, R.all(R.pearl, R.mitt)),
  e('Dark Grassy Lawn', WDW, R.all(R.pearl, R.hammer)),
  e(WDW, EDW, R.all(R.pearl, R.flippers)),
  e(NEDW, WDW, R.all(R.pearl, R.hookshot)),
  e(NEDW, EDW, R.all(R.pearl, R.any(R.gloves, R.hammer))),
  e(EDW, NEDW, R.all(R.pearl, R.any(R.gloves, R.hammer, R.flippers))),
  e('Catfish', NEDW, R.gloves),
  e(NEDW, 'Catfish', R.gloves),
  e(WDW, 'Bumper Cave Entrance', R.all(R.pearl, R.gloves)),
  e('Bumper Cave Entrance', WDW),
  e('Bumper Cave Entrance', 'Death Mountain Entrance', R.mirror),
  e('Bumper Cave Ledge', WDW),
  e('Bumper Cave Ledge', 'Death Mountain Return Ledge', R.mirror),
  e('Bumper Cave Entrance', 'Bumper Cave'),
  e('Bumper Cave Ledge', 'Bumper Cave'),
  e('Bumper Cave', 'Bumper Cave Ledge', R.cape),
  e('Bumper Cave', WDW, R.any(R.cape, R.hookshot)),
  e(WDW, 'Skull Woods Forest'),
  e('Skull Woods Forest', 'Skull Woods Forest (West)', R.all(R.pearl, R.any(R.fireRod, R.hookshot))),
  e('Pyramid Ledge', EDW),
  e(EDW, 'Pyramid', R.agahnim2),
  e('Pyramid', 'Bottom of Pyramid', R.beamSword),
  e('Bottom of Pyramid', 'Pyramid Ledge'),
  e('Pyramid Ledge', 'Bottom of Pyramid'),
  e(EDW, 'Pyramid Fairy', R.all(R.crystal5, R.crystal6)),
  e(EDW, 'East Dark World Hint'),
  e(EDW, 'Palace of Darkness Hint'),
  e(EDW, 'Dark Lake Hylia Healer Fairy'),
  e('Dark Lake Hylia Ledge', 'Dark Lake Hylia Ledge Healer Fairy', R.all(R.pearl, R.bombs)),
  e('Dark Lake Hylia Ledge', 'Dark Lake Hylia Ledge Spike Cave', R.all(R.gloves, R.pearl)),
  e('Dark Lake Hylia Ledge', 'Dark Lake Hylia Ledge Hint'),
  e(SDW, 'Big Bomb Shop'),
  e(SDW, 'Dark Lake Hylia Shop'),
  e(SDW, 'Hype Cave', R.all(R.pearl, R.bombs)),
  e(SDW, 'Bonk Fairy (Dark)', R.all(R.pearl, R.boots)),
  e(SDW, 'Archery Game'),
  e(SDW, 'Swamp Palace (Entrance)'),
  e('Swamp Palace (Entrance)', SDW),
  e(WDW, 'Brewery', R.all(R.pearl, R.bombs)),
  e(WDW, 'C-Shaped House'),
  e(WDW, 'Chest Game'),
  e(WDW, 'Red Shield Shop'),
  e(WDW, 'Dark Sanctuary Hint'),
  e(WDW, 'Fortune Teller (Dark)'),
  e(WDW, 'Dark World Lumberjack Shop'),
  e(WDW, 'Thieves Town (Entrance)', R.pearl),
  e('Thieves Town (Entrance)', WDW),
  e('Dark Grassy Lawn', 'Village of Outcasts Shop'),
  e('Hammer Peg Area', 'Dark World Hammer Peg Cave', R.all(R.pearl, R.hammer)),
  e(NEDW, 'Dark World Potion Shop'),
  e('Dark Desert', 'Mire Shed'),
  e('Dark Desert', 'Dark Desert Hint'),
  e('Dark Desert', 'Dark Desert Healer Fairy'),
  e('Dark Desert', 'Misery Mire (Entrance)', R.all(R.pearl, R.sword, R.ether)),
  e('Misery Mire (Entrance)', 'Dark Desert'),
  e(EDW, 'Palace of Darkness (Entrance)', R.pearl),
  e('Palace of Darkness (Entrance)', EDW),
  e('Skull Woods Forest', 'Skull Woods First Section (Right)'),
  e('Skull Woods Forest', 'Skull Woods First Section (Left)'),
  e('Skull Woods Forest', 'Skull Woods First Section (Top)', R.pearl),
  e('Skull Woods Forest', 'Skull Woods First Section'),
  e('Skull Woods First Section', 'Skull Woods Forest'),
  e('Skull Woods Forest (West)', 'Skull Woods Second Section (Drop)', R.pearl),
  e('Skull Woods Forest', 'Skull Woods Second Section'),
  e('Skull Woods Forest (West)', 'Skull Woods Second Section'),
  e('Skull Woods Second Section', 'Skull Woods Forest'),
  e('Skull Woods Second Section', 'Skull Woods Forest (West)'),
  e('Skull Woods Forest (West)', 'Skull Woods Final Section (Entrance)', R.all(R.fireRod, R.pearl)),
  e('Skull Woods Final Section (Entrance)', 'Skull Woods Forest (West)'),
  // The light world's doors.
  e(LW, 'Links House'),
  e('Links House', LW),
  e(LW, 'Blinds Hideout'),
  e(LW, 'Dam'),
  e(LW, 'Lumberjack House'),
  e(LW, 'Bonk Fairy (Light)', R.boots),
  e(LW, 'Lake Hylia Healer Fairy'),
  e(LW, 'Lake Hylia Fortune Teller'),
  e(LW, 'Swamp Healer Fairy', R.bombs),
  e(LW, 'Desert Healer Fairy'),
  e(LW, 'Tavern'),
  e(LW, 'Chicken House'),
  e(LW, 'Aginahs Cave'),
  e(LW, 'Sahasrahlas Hut'),
  e(LW, 'Cave Shop (Lake Hylia)'),
  e(LW, 'Kakariko Well (top)'),
  e(LW, 'Kakariko Well (bottom)'),
  e('Kakariko Well (top)', 'Kakariko Well (bottom)'),
  e('Kakariko Well (bottom)', LW),
  e(LW, 'Blacksmiths Hut'),
  e(LW, 'Sick Kids House'),
  e(LW, 'Elder House'),
  e('Elder House', LW),
  e(LW, 'North Fairy Cave'),
  e('North Fairy Cave', LW),
  e(LW, 'Lost Woods Gamble'),
  e(LW, 'Fortune Teller (Light)'),
  e(LW, 'Snitch Lady (East)'),
  e(LW, 'Snitch Lady (West)'),
  e(LW, 'Bush Covered House'),
  e(LW, 'Tavern (Front)'),
  e(LW, 'Light World Bomb Hut', R.bombs),
  e(LW, 'Kakariko Shop'),
  e(LW, 'Lost Woods Hideout (top)'),
  e(LW, 'Lost Woods Hideout (bottom)'),
  e('Lost Woods Hideout (top)', 'Lost Woods Hideout (bottom)'),
  e('Lost Woods Hideout (bottom)', LW),
  e(LW, 'Lumberjack Tree (top)', R.all(R.boots, R.agahnim1)),
  e(LW, 'Lumberjack Tree (bottom)'),
  e('Lumberjack Tree (top)', 'Lumberjack Tree (bottom)'),
  e('Lumberjack Tree (bottom)', LW),
  e(LW, 'Mini Moldorm Cave', R.bombs),
  e(LW, 'Long Fairy Cave'),
  e(LW, 'Good Bee Cave'),
  e(LW, '20 Rupee Cave', R.gloves),
  e(LW, '50 Rupee Cave', R.gloves),
  e(LW, 'Ice Rod Cave', R.bombs),
  e(LW, 'Bonk Rock Cave', R.boots),
  e(LW, 'Library'),
  e(LW, 'Kakariko Gamble Game'),
  e(LW, 'Potion Shop'),
  e(LW, 'Eastern Palace'),
  e('Eastern Palace', LW),
  e('Desert Palace Stairs', 'Desert Palace Main (Inner)'),
  e('Desert Ledge', 'Desert Palace Main (Outer)'),
  e('Desert Palace Entrance (North) Spot', 'Desert Palace North'),
  e('Desert Palace Lone Stairs', 'Desert Palace Main (Outer)'),
  e('Desert Palace Main (Inner)', 'Desert Palace Stairs'),
  e('Desert Palace Main (Outer)', 'Desert Ledge'),
  e('Desert Palace Main (Outer)', 'Desert Palace Lone Stairs'),
  e('Desert Palace North', 'Desert Palace Entrance (North) Spot'),
  e('Turtle Rock (Second Section Bomb Wall)', 'Dark Death Mountain Ledge'),
  e('Turtle Rock (Big Chest)', 'Dark Death Mountain Ledge'),
  e('Dark Death Mountain Ledge', 'Turtle Rock (Second Section)'),
  e('Dark Death Mountain Ledge', 'Turtle Rock (Big Chest)'),
  e('Turtle Rock (Eye Bridge Bomb Wall)', 'Dark Death Mountain Isolated Ledge'),
  e('Dark Death Mountain Isolated Ledge', 'Turtle Rock (Eye Bridge)'),
];

export { REGION_EDGES };
export type { RegionEdge };
