import type { RegionDefinition } from '../../../types';

export const SKULL_WOODS_DUNGEON: RegionDefinition[] = [
  {
    id: 'sw-0x29',
    name: 'Mothula',
    type: 'dungeon',
    inGameIndex: 0x29,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'Boss Room',
    gridX: 9,
    gridY: 2,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:boss_room',
    ],
  },
  {
    id: 'sw-0x39',
    name: 'Gibdo Key Room',
    type: 'dungeon',
    inGameIndex: 0x39,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1',
    gridX: 9,
    gridY: 3,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:puzzle',
    ],
  },
  {
    id: 'sw-0x49',
    name: 'Compass Room',
    type: 'dungeon',
    inGameIndex: 0x49,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1',
    gridX: 9,
    gridY: 4,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:treasure',
    ],
  },
  {
    id: 'sw-0x56',
    name: 'Big Chest Room',
    type: 'dungeon',
    inGameIndex: 0x56,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1 West',
    gridX: 6,
    gridY: 5,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:treasure',
    ],
  },
  {
    id: 'sw-0x57',
    name: 'Big Key Room',
    type: 'dungeon',
    inGameIndex: 0x57,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1',
    gridX: 7,
    gridY: 5,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:treasure',
    ],
  },
  {
    id: 'sw-0x58',
    name: 'Map Room',
    type: 'dungeon',
    inGameIndex: 0x58,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1 Center',
    gridX: 8,
    gridY: 5,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:treasure',
      'role:hub',
    ],
  },
  {
    id: 'sw-0x59',
    name: 'Pot Prison',
    type: 'dungeon',
    inGameIndex: 0x59,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1 East',
    gridX: 9,
    gridY: 5,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:puzzle',
    ],
  },
  {
    id: 'sw-0x67',
    name: 'Pinball Room',
    type: 'dungeon',
    inGameIndex: 0x67,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1',
    gridX: 7,
    gridY: 6,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:puzzle',
    ],
  },
  {
    id: 'sw-0x68',
    name: 'Entrance Hall',
    type: 'dungeon',
    inGameIndex: 0x68,
    dungeon: 'Skull Woods',
    displayName: 'Skull Woods',
    subtitle: 'B1',
    gridX: 8,
    gridY: 6,
    floor: -1,
    tags: [
      'world:dark',
      'env:underground',
      'type:dungeon',
      'area:skull_woods_area',
      'dungeon:skull_woods',
      'role:entrance',
    ],
  },
];
