#ifndef ZELDA3_FEATURES_BUGFIXES_H_
#define ZELDA3_FEATURES_BUGFIXES_H_
// GENERATED by scripts/build/gen-bundle-flags.mjs, do not edit by hand.
// Source of truth: scripts/build/bundle-settings.json (Wave-1b catalog). Each was bundled under MiscBugFixes/GameChangingBugFixes/WidescreenVisualFixes upstream; split per the settings plan.

// Enum values for kRam_Features1
enum {
  kFeatures1_MedallionSpinAttackAbortFix = 1u,  // gameplay-affecting: Medallion cast vs spin attack
  kFeatures1_DoubleCameraDoorHandlingFix = 2u,  // bug-fix-cosmetic: Double indoor-camera nudge
  kFeatures1_TurboDashPitLevitationFix = 4u,    // gameplay-affecting: Turbo-dash pit levitation
  kFeatures1_WalkOnWaterPitStateFix = 8u,       // gameplay-affecting: Walk-on-water near-pit flag
  kFeatures1_PitLandingExplorationGlitchFix = 16u, // gameplay-affecting: Pit-landing exploration glitch
  kFeatures1_CapeMagicUnderflowFix = 32u,        // gameplay-affecting: Cape magic underflow
  kFeatures1_CapeDrainWhileGrabbingFix = 64u,    // gameplay-affecting: Cape drain while grabbing
  kFeatures1_SomariaNoMagicPowderFix = 128u,      // gameplay-affecting: Somaria empty-magic powder slip
  kFeatures1_SomariaMagicRefundExploitFix = 256u, // gameplay-affecting: Somaria free-magic refund
  kFeatures1_MagicRefundOverflowClampFix = 512u,  // gameplay-affecting: Magic refund overflow clamp
  kFeatures1_DashBufferingSlopeFlagFix = 1024u,    // gameplay-affecting: Dash-buffering slope flag
  kFeatures1_SlopeJudderOobReadFix = 2048u,        // bug-fix-cosmetic: Vertical-slope judder / OOB read
  kFeatures1_TempBunnyAnimationStepsFix = 4096u,   // visual-only: Temp-bunny walk animation
  kFeatures1_PotionModuleDoorTransitionFix = 8192u, // gameplay-affecting: Potion-module door transition guard
  kFeatures1_LinkInitGlitchStateReset = 16384u,     // gameplay-affecting: Link_Initialize leftover-state reset (bundles 6 fixes)
  kFeatures1_KikiDefuseBigBomb = 32768u,            // gameplay-affecting: Kiki big-bomb defuse
  kFeatures1_ZoraSpawnInShallowWater = 65536u,      // bug-fix-cosmetic: Zora shallow-water spawn
  kFeatures1_MushroomNoPickupDuringMirrorWarp = 131072u, // bug-fix-cosmetic: Mushroom pickup during mirror warp
  kFeatures1_GiantMoldormKnockbackSfx = 262144u,     // visual-only: Giant Moldorm knockback SFX
  kFeatures1_NoDoubleAbsorptionHandling = 524288u,   // bug-fix-cosmetic: Double heart/fairy absorption
  kFeatures1_SwamolaCorrectSegmentIndex = 1048576u,   // bug-fix-cosmetic: Swamola segment index
  kFeatures1_MothulaTakesL4AndSpinDamage = 2097152u,  // gameplay-affecting: Mothula L4/spin damage table
  kFeatures1_ReloadShieldPaletteAfterPikit = 4194304u, // visual-only: Shield palette after Pikit
  kFeatures1_CancelHookshotGrabOnHiddenAbsorbable = 8388608u, // bug-fix-cosmetic: Stale hookshot grab on hidden item
  kFeatures1_MothulaSpikeTileDamageClassFix = 16777216u, // gameplay-affecting: Mothula spike-tile damage class
  kFeatures1_GiantMoldormWeaponTinkSfxFix = 33554432u, // visual-only: Giant Moldorm weapon-tink SFX
  kFeatures1_BoomerangTerminateWhenEmptyHanded = 67108864u, // gameplay-affecting: Boomerang stuck on empty-hand release
  kFeatures1_BigBombPreserveFollowerIndicator = 134217728u, // gameplay-affecting: Big-bomb follower-indicator preserve
  kFeatures1_PermabunnyRestorePaletteOnRevive = 268435456u, // visual-only: Permabunny palette on revive
  kFeatures1_FixDeathCounterOvercount = 536870912u,     // gameplay-affecting: Death-counter overcount
  kFeatures1_FixResumeMosaicSanctuaryWarp = 1073741824u, // bug-fix-cosmetic: Resume-mosaic sanctuary warp
  kFeatures1_FixPermabunnyDeathPalette = 2147483648u,    // visual-only: Permabunny death palette
};

// Enum values for kRam_Features2
enum {
  kFeatures2_SkipRoomTagsDuringStaircaseTransition = 1u, // gameplay-affecting: Room tags during staircase race
  kFeatures2_SkipDungeonUpdateAfterModuleExit = 2u, // gameplay-affecting: Dungeon update after module exit
  kFeatures2_KholdstareShellPaletteRange = 4u,  // visual-only: Kholdstare shell palette range
  kFeatures2_PreserveGlovesColorOnGearReload = 8u, // visual-only: Glove color on gear reload
  kFeatures2_SuperBombClearFollowerOnExplode = 16u, // gameplay-affecting: Super-bomb follower snap-back
  kFeatures2_SuperBombPaletteOnFrameZero = 32u,  // visual-only: Super-bomb final-frame palette
  kFeatures2_FixPortalMusicRestart = 64u,        // bug-fix-cosmetic: Portal music restart
  kFeatures2_IcePortalRevealChime = 128u,         // bug-fix-cosmetic: Ice Temple portal reveal chime
  kFeatures2_WidescreenLinkHideViaOffscreenY = 256u, // visual-only: Widescreen Link hide
  kFeatures2_SaveMenuLockoutAfterMedallionFix = 512u, // gameplay-affecting: Fix save-menu lockout after medallion cast
};

#endif  // ZELDA3_FEATURES_BUGFIXES_H_
