/* @layer renderer-components @kind data */
// ─── ALttP MSU-1 Track Descriptions ───
// Standard tracks (1-36) + Deluxe tracks (37-112)
const MSU_TRACK_DESCRIPTIONS: Record<number, string> = {
  // Standard MSU-1
  1: 'Opening Theme',
  2: 'Light World',
  3: 'Rain State',
  4: 'Bunny',
  5: 'Lost Woods',
  6: 'Prologue',
  7: 'Kakariko Village',
  8: 'Mirror / Portal',
  9: 'Dark World',
  10: 'Master Sword',
  11: 'File Select',
  12: 'Guard Encounter',
  13: 'Dark Death Mountain',
  14: 'Fortune Teller',
  15: 'Skull Woods (OW)',
  16: 'Hyrule Castle',
  17: 'Pendant Dungeon',
  18: 'Crystal Dungeon',
  19: 'Boss Clear',
  20: 'Sanctuary',
  21: 'Boss Battle',
  22: 'Wizard Battle',
  23: 'Ganon Battle',
  24: 'Triforce Room',
  25: 'Ending Sequence',
  26: 'Credits',
  27: 'Eastern Palace',
  28: 'Desert Palace',
  29: "Wizard's Tower",
  30: 'Swamp Palace',
  31: 'Palace of Darkness',
  32: 'Misery Mire',
  33: 'Skull Woods (Dungeon)',
  34: 'Ice Palace',
  35: 'Tower of Hera',
  36: "Thieves' Town",
  // Deluxe — Overworld context
  37: 'LW: Hyrule Field',
  38: 'LW: Castle Grounds',
  39: 'LW: Kakariko Area',
  40: 'LW: Eastern Area',
  41: 'LW: Southern Shore',
  42: 'LW: Forest / Woods',
  43: 'DW: Dark Forest',
  44: 'DW: Mire Area',
  45: 'DW: Mountain',
  46: 'DW: Swamp',
  47: 'DW: Graveyard',
  48: 'DW: Sacred Grove',
  49: 'DW: Pyramid',
  50: 'DW: Village',
  51: 'DW: Dark Woods',
  52: 'DW: Death Mountain',
  53: 'DW: Ice Lake',
  54: 'DW: Skeleton Forest',
  55: 'DW: Bumper Area',
  56: 'DW: Dark Palace Area',
  57: 'DW: Dark Desert',
  58: 'DW: East Summit Area',
  // Deluxe — Dungeons / Interiors
  59: "Link's House",
  60: "Zelda's Cell",
  61: 'Castle Interior',
  62: 'Generic Interior',
  63: 'Castle Dungeon',
  64: 'Church Interior',
  65: 'Tavern',
  66: "Sahasrahla's Hut",
  67: 'Fairy Fountain',
  68: 'Cave',
  69: "Blind's Hideout",
  70: 'Desert Palace Interior',
  71: 'Swamp Palace Interior',
  72: 'Palace of Darkness Int.',
  73: 'Ice Palace Interior',
  74: 'Tower of Hera Interior',
  75: 'Misery Mire Interior',
  76: "Thieves' Town Interior",
  77: 'Skull Woods Interior',
  78: "Ganon's Tower Interior",
  79: 'East Summit Interior',
  80: 'Eastern Palace Interior',
  81: "Wizard's Tower Int.",
  82: 'Castle Tower',
  83: 'Mountain Cave',
  84: 'Checkerboard Cave',
  85: 'Hammer Peg Cave',
  86: 'Chest Game',
  87: 'Bumper Cave',
  88: 'Spike Cave',
  89: 'Hookshot Cave',
  90: 'Mimic Cave',
  91: 'Superbunny Cave',
  92: 'Paradox Cave',
  93: 'Spectacle Rock Cave',
  94: 'Waterfall of Wishing',
  95: 'Pyramid Fairy',
  96: 'Dark Chapel',
  97: "King's Tomb",
  98: 'Graveyard Cave',
  99: 'Dam',
  100: 'Sewers',
  102: 'Potion Shop',
  103: 'Witch Hut',
  104: 'Library',
  105: 'Treasure Chest Game',
  106: 'Archery Game',
  107: 'Digging Game',
  108: 'Lumberjack House',
  109: 'Fortune Teller (DW)',
  110: 'DW: Shop Area',
  112: 'LW: Desert',
  114: 'Bomb Shop',
};

export { MSU_TRACK_DESCRIPTIONS };
