/* @layer shared-game @kind data */
/**
 * The reachability graph of the dungeon interiors: one row per passage out of a region.
 *
 * A row is a RULE, not a place. The exit name is the key the rule tables hang their
 * requirement off, and `connectionId` names the crossing the map draws for it when exactly
 * one crossing of the record collection joins the same pair of regions. Where none does, or
 * where several do, the row carries none: a mirror spot, a retry from the menu and a wing
 * boundary inside one room cross no tile at all, and a pair joined by two doors cannot say
 * which of them this passage is.
 *
 * Folded from Archipelago worlds/alttp/Regions.py (create_regions, the exits of each region)
 * and EntranceShuffle.py (mandatory_connections, default_connections,
 * default_dungeon_connections), open mode with entrance shuffle off.
 */
import type { RegionGraphRow } from '../../region.type';

const DUNGEON_REGION_GRAPH: readonly RegionGraphRow[] = [
  { from: 'region-164', to: 'region-165', exit: 'Desert Palace Pots (Outer)' },
  { from: 'region-164', to: 'region-013', exit: 'Desert Palace Exit (West)' },
  { from: 'region-164', to: 'region-016', exit: 'Desert Palace Exit (East)' },
  { from: 'region-164', to: 'region-166', exit: 'Desert Palace East Wing', connectionId: 'connection-288' },
  { from: 'region-165', to: 'region-015', exit: 'Desert Palace Exit (South)' },
  { from: 'region-165', to: 'region-164', exit: 'Desert Palace Pots (Inner)' },
  { from: 'region-167', to: 'region-017', exit: 'Desert Palace Exit (North)' },
  { from: 'region-168', to: 'region-002', exit: 'Eastern Palace Exit', connectionId: 'connection-277' },
  { from: 'region-169', to: 'region-020', exit: 'Hyrule Castle Exit (East)' },
  { from: 'region-169', to: 'region-020', exit: 'Hyrule Castle Exit (West)' },
  { from: 'region-169', to: 'region-019', exit: 'Hyrule Castle Exit (South)' },
  { from: 'region-169', to: 'region-171', exit: 'Throne Room' },
  { from: 'region-170', to: 'region-172', exit: 'Sewer Drop' },
  { from: 'region-171', to: 'region-172', exit: 'Sewers Door' },
  { from: 'region-172', to: 'region-174', exit: 'Sanctuary Push Door' },
  { from: 'region-172', to: 'region-171', exit: 'Sewers Back Door' },
  { from: 'region-172', to: 'region-173', exit: 'Sewers Secret Room' },
  { from: 'region-174', to: 'region-002', exit: 'Sanctuary Exit', connectionId: 'connection-243' },
  { from: 'region-175', to: 'region-176', exit: 'Agahnim 1', connectionId: 'connection-1311' },
  { from: 'region-175', to: 'region-020', exit: 'Agahnims Tower Exit' },
  { from: 'region-177', to: 'region-178', exit: 'Tower of Hera Small Key Door' },
  { from: 'region-177', to: 'region-179', exit: 'Tower of Hera Big Key Door' },
  { from: 'region-177', to: 'region-028', exit: 'Tower of Hera Exit' },
  { from: 'region-180', to: 'region-181', exit: 'Swamp Palace Moat' },
  { from: 'region-180', to: 'region-037', exit: 'Swamp Palace Exit' },
  { from: 'region-181', to: 'region-182', exit: 'Swamp Palace Small Key Door' },
  { from: 'region-182', to: 'region-183', exit: 'Swamp Palace (Center)', connectionId: 'connection-1038' },
  { from: 'region-183', to: 'region-185', exit: 'Swamp Palace (North)' },
  { from: 'region-183', to: 'region-184', exit: 'Swamp Palace (West)', connectionId: 'connection-1037' },
  { from: 'region-186', to: 'region-187', exit: 'Thieves Town Big Key Door' },
  { from: 'region-186', to: 'region-041', exit: 'Thieves Town Exit', connectionId: 'connection-692' },
  { from: 'region-187', to: 'region-188', exit: 'Blind Fight' },
  { from: 'region-189', to: 'region-046', exit: 'Skull Woods First Section Exit', connectionId: 'connection-674' },
  { from: 'region-189', to: 'region-192', exit: 'Skull Woods First Section Bomb Jump' },
  { from: 'region-189', to: 'region-190', exit: 'Skull Woods First Section South Door', connectionId: 'connection-666' },
  { from: 'region-189', to: 'region-191', exit: 'Skull Woods First Section West Door' },
  { from: 'region-190', to: 'region-189', exit: 'Skull Woods First Section (Right) North Door', connectionId: 'connection-669' },
  { from: 'region-191', to: 'region-189', exit: 'Skull Woods First Section (Left) Door to Exit' },
  { from: 'region-191', to: 'region-190', exit: 'Skull Woods First Section (Left) Door to Right', connectionId: 'connection-668' },
  { from: 'region-192', to: 'region-189', exit: 'Skull Woods First Section (Top) One-Way Path' },
  { from: 'region-193', to: 'region-194', exit: 'Skull Woods Second Section (Drop)' },
  { from: 'region-194', to: 'region-046', exit: 'Skull Woods Second Section Exit (East)' },
  { from: 'region-194', to: 'region-047', exit: 'Skull Woods Second Section Exit (West)' },
  { from: 'region-195', to: 'region-196', exit: 'Skull Woods Torch Room' },
  { from: 'region-195', to: 'region-047', exit: 'Skull Woods Final Section Exit' },
  { from: 'region-197', to: 'region-198', exit: 'Ice Palace (Second Section)', connectionId: 'connection-698' },
  { from: 'region-197', to: 'region-039', exit: 'Ice Palace Exit' },
  { from: 'region-198', to: 'region-199', exit: 'Ice Palace (Main)', connectionId: 'connection-700' },
  { from: 'region-199', to: 'region-200', exit: 'Ice Palace (East)' },
  { from: 'region-199', to: 'region-202', exit: 'Ice Palace (Kholdstare)', connectionId: 'connection-722' },
  { from: 'region-200', to: 'region-201', exit: 'Ice Palace (East Top)' },
  { from: 'region-203', to: 'region-204', exit: 'Misery Mire Entrance Gap' },
  { from: 'region-203', to: 'region-048', exit: 'Misery Mire Exit' },
  { from: 'region-204', to: 'region-205', exit: 'Misery Mire (West)', connectionId: 'connection-748' },
  { from: 'region-204', to: 'region-206', exit: 'Misery Mire Big Key Door' },
  { from: 'region-206', to: 'region-207', exit: 'Misery Mire (Vitreous)' },
  { from: 'region-208', to: 'region-209', exit: 'Turtle Rock Entrance Gap', connectionId: 'connection-785' },
  { from: 'region-208', to: 'region-050', exit: 'Turtle Rock Exit (Front)' },
  { from: 'region-209', to: 'region-210', exit: 'Turtle Rock Entrance to Pokey Room' },
  { from: 'region-209', to: 'region-208', exit: 'Turtle Rock Entrance Gap Reverse', connectionId: 'connection-1064' },
  { from: 'region-210', to: 'region-211', exit: 'Turtle Rock (Pokey Room) (North)' },
  { from: 'region-210', to: 'region-209', exit: 'Turtle Rock (Pokey Room) (South)' },
  { from: 'region-211', to: 'region-212', exit: 'Turtle Rock (Chain Chomp Room) (North)' },
  { from: 'region-211', to: 'region-210', exit: 'Turtle Rock (Chain Chomp Room) (South)' },
  { from: 'region-212', to: 'region-211', exit: 'Turtle Rock Chain Chomp Staircase' },
  { from: 'region-212', to: 'region-215', exit: 'Turtle Rock Big Key Door', connectionId: 'connection-1074' },
  { from: 'region-212', to: 'region-213', exit: 'Turtle Rock Second Section Bomb Wall' },
  { from: 'region-213', to: 'region-051', exit: 'Turtle Rock Ledge Exit (West)' },
  { from: 'region-213', to: 'region-212', exit: 'Turtle Rock Second Section from Bomb Wall' },
  { from: 'region-214', to: 'region-212', exit: 'Turtle Rock (Big Chest) (North)', connectionId: 'connection-1077' },
  { from: 'region-214', to: 'region-051', exit: 'Turtle Rock Ledge Exit (East)' },
  { from: 'region-215', to: 'region-216', exit: 'Turtle Rock Dark Room Staircase' },
  { from: 'region-215', to: 'region-212', exit: 'Turtle Rock Big Key Door Reverse', connectionId: 'connection-765' },
  { from: 'region-216', to: 'region-215', exit: 'Turtle Rock (Dark Room) (North)' },
  { from: 'region-216', to: 'region-218', exit: 'Turtle Rock (Dark Room) (South)' },
  { from: 'region-217', to: 'region-052', exit: 'Turtle Rock Isolated Ledge Exit' },
  { from: 'region-217', to: 'region-218', exit: 'Turtle Rock Eye Bridge from Bomb Wall' },
  { from: 'region-218', to: 'region-216', exit: 'Turtle Rock Dark Room (South)' },
  { from: 'region-218', to: 'region-219', exit: 'Turtle Rock (Trinexx)' },
  { from: 'region-218', to: 'region-217', exit: 'Turtle Rock Eye Bridge Bomb Wall' },
  { from: 'region-220', to: 'region-221', exit: 'Palace of Darkness Bridge Room', connectionId: 'connection-610' },
  { from: 'region-220', to: 'region-223', exit: 'Palace of Darkness Bonk Wall' },
  { from: 'region-220', to: 'region-034', exit: 'Palace of Darkness Exit', connectionId: 'connection-633' },
  { from: 'region-221', to: 'region-222', exit: 'Palace of Darkness Big Key Chest Staircase' },
  { from: 'region-221', to: 'region-224', exit: 'Palace of Darkness (North)' },
  { from: 'region-221', to: 'region-227', exit: 'Palace of Darkness Big Key Door', connectionId: 'connection-1000' },
  { from: 'region-223', to: 'region-221', exit: 'Palace of Darkness Hammer Peg Drop', connectionId: 'connection-990' },
  { from: 'region-224', to: 'region-226', exit: 'Palace of Darkness Spike Statue Room Door' },
  { from: 'region-224', to: 'region-225', exit: 'Palace of Darkness Maze Door', connectionId: 'connection-1011' },
  { from: 'region-228', to: 'region-229', exit: 'Ganons Tower (Tile Room)', connectionId: 'connection-824' },
  { from: 'region-228', to: 'region-231', exit: 'Ganons Tower (Hookshot Room)', connectionId: 'connection-851' },
  { from: 'region-228', to: 'region-236', exit: 'Ganons Tower Big Key Door' },
  { from: 'region-228', to: 'region-050', exit: 'Ganons Tower Exit' },
  { from: 'region-229', to: 'region-230', exit: 'Ganons Tower (Tile Room) Key Door', connectionId: 'connection-826' },
  { from: 'region-230', to: 'region-235', exit: 'Ganons Tower (Bottom) (East)' },
  { from: 'region-231', to: 'region-232', exit: 'Ganons Tower (Map Room)' },
  { from: 'region-231', to: 'region-233', exit: 'Ganons Tower (Double Switch Room)' },
  { from: 'region-233', to: 'region-234', exit: 'Ganons Tower (Firesnake Room)', connectionId: 'connection-915' },
  { from: 'region-234', to: 'region-235', exit: 'Ganons Tower (Bottom) (West)' },
  { from: 'region-236', to: 'region-237', exit: 'Ganons Tower Torch Rooms' },
  { from: 'region-237', to: 'region-238', exit: 'Ganons Tower Moldorm Door' },
  { from: 'region-238', to: 'region-239', exit: 'Ganons Tower Moldorm Gap' },
];

export { DUNGEON_REGION_GRAPH };
