/* @layer shared-game @kind data */
/**
 * The reachability graph of the second world: one row per passage out of a region.
 *
 * A row is a RULE, not a place. The exit name is the key the rule tables hang their
 * requirement off, and `connectionId` names the crossing the map draws for it when exactly
 * one crossing of the record collection joins the same pair of regions. Where none does, or
 * where several do, the row carries none: a mirror spot, a retry from the menu and a wing
 * boundary inside one room cross no tile at all, and a pair joined by two doors cannot say
 * which of them this passage is.
 *
 * Folded from Archipelago worlds/alttp/Regions.py (create_regions, the exits of each region)
 * and EntranceShuffle.py (mandatory_connections, default_connections,
 * default_dungeon_connections), open mode with entrance shuffle off.
 */
import type { RegionGraphRow } from '../../region.type';

const DARK_REGION_GRAPH: readonly RegionGraphRow[] = [
  { from: 'region-034', to: 'region-147', exit: 'Pyramid Fairy', connectionId: 'connection-863' },
  { from: 'region-034', to: 'region-037', exit: 'South Dark World Bridge' },
  { from: 'region-034', to: 'region-220', exit: 'Palace of Darkness', connectionId: 'connection-606' },
  { from: 'region-034', to: 'region-038', exit: 'Dark Lake Hylia Drop (East)' },
  { from: 'region-034', to: 'region-020', exit: 'Hyrule Castle Ledge Mirror Spot', connectionId: 'connection-432' },
  { from: 'region-034', to: 'region-082', exit: 'Dark Lake Hylia Fairy', connectionId: 'connection-865' },
  { from: 'region-034', to: 'region-134', exit: 'Palace of Darkness Hint', connectionId: 'connection-874' },
  { from: 'region-034', to: 'region-135', exit: 'East Dark World Hint', connectionId: 'connection-875' },
  { from: 'region-034', to: 'region-162', exit: 'Pyramid Hole', connectionId: 'connection-428' },
  { from: 'region-034', to: 'region-036', exit: 'Northeast Dark World Broken Bridge Pass' },
  { from: 'region-035', to: 'region-036', exit: 'Catfish Exit Rock' },
  { from: 'region-036', to: 'region-041', exit: 'West Dark World Gap', connectionId: 'connection-1195' },
  { from: 'region-036', to: 'region-145', exit: 'Dark World Potion Shop', connectionId: 'connection-888' },
  { from: 'region-036', to: 'region-034', exit: 'East Dark World Broken Bridge Pass' },
  { from: 'region-036', to: 'region-035', exit: 'Catfish Entrance Rock' },
  { from: 'region-036', to: 'region-038', exit: 'Dark Lake Hylia Teleporter' },
  { from: 'region-037', to: 'region-038', exit: 'Dark Lake Hylia Drop (South)' },
  { from: 'region-037', to: 'region-140', exit: 'Hype Cave', connectionId: 'connection-855' },
  { from: 'region-037', to: 'region-180', exit: 'Swamp Palace' },
  { from: 'region-037', to: 'region-041', exit: 'Village of Outcasts Heavy Rock' },
  { from: 'region-037', to: 'region-012', exit: 'Maze Race Mirror Spot', connectionId: 'connection-452' },
  { from: 'region-037', to: 'region-009', exit: 'Cave 45 Mirror Spot', connectionId: 'connection-453' },
  { from: 'region-037', to: 'region-034', exit: 'East Dark World Bridge' },
  { from: 'region-037', to: 'region-136', exit: 'Big Bomb Shop', connectionId: 'connection-890' },
  { from: 'region-037', to: 'region-137', exit: 'Archery Game', connectionId: 'connection-870' },
  { from: 'region-037', to: 'region-078', exit: 'Bonk Fairy (Dark)', connectionId: 'connection-864' },
  { from: 'region-037', to: 'region-143', exit: 'Dark Lake Hylia Shop' },
  { from: 'region-037', to: 'region-030', exit: 'Bombos Tablet Mirror Spot', connectionId: 'connection-454' },
  { from: 'region-038', to: 'region-011', exit: 'Lake Hylia Island Mirror Spot', connectionId: 'connection-437' },
  { from: 'region-038', to: 'region-034', exit: 'East Dark World Pier' },
  { from: 'region-038', to: 'region-040', exit: 'Dark Lake Hylia Ledge' },
  { from: 'region-039', to: 'region-197', exit: 'Ice Palace' },
  { from: 'region-039', to: 'region-004', exit: 'Lake Hylia Central Island Mirror Spot', connectionId: 'connection-438' },
  { from: 'region-040', to: 'region-038', exit: 'Dark Lake Hylia Ledge Drop' },
  { from: 'region-040', to: 'region-083', exit: 'Dark Lake Hylia Ledge Fairy', connectionId: 'connection-866' },
  { from: 'region-040', to: 'region-138', exit: 'Dark Lake Hylia Ledge Hint', connectionId: 'connection-876' },
  { from: 'region-040', to: 'region-139', exit: 'Dark Lake Hylia Ledge Spike Cave', connectionId: 'connection-856' },
  { from: 'region-041', to: 'region-037', exit: 'Village of Outcasts Drop' },
  { from: 'region-041', to: 'region-034', exit: 'East Dark World River Pier' },
  { from: 'region-041', to: 'region-148', exit: 'Brewery', connectionId: 'connection-878' },
  { from: 'region-041', to: 'region-149', exit: 'C-Shaped House', connectionId: 'connection-873' },
  { from: 'region-041', to: 'region-150', exit: 'Chest Game', connectionId: 'connection-869' },
  { from: 'region-041', to: 'region-186', exit: 'Thieves Town', connectionId: 'connection-676' },
  { from: 'region-041', to: 'region-010', exit: 'Graveyard Ledge Mirror Spot', connectionId: 'connection-467' },
  { from: 'region-041', to: 'region-006', exit: 'Kings Grave Mirror Spot', connectionId: 'connection-468' },
  { from: 'region-041', to: 'region-044', exit: 'Bumper Cave Entrance Rock' },
  { from: 'region-041', to: 'region-046', exit: 'Skull Woods Forest' },
  { from: 'region-041', to: 'region-042', exit: 'Village of Outcasts Pegs' },
  { from: 'region-041', to: 'region-043', exit: 'Village of Outcasts Eastern Rocks' },
  { from: 'region-041', to: 'region-151', exit: 'Red Shield Shop', connectionId: 'connection-889' },
  { from: 'region-041', to: 'region-152', exit: 'Dark Sanctuary Hint' },
  { from: 'region-041', to: 'region-141', exit: 'Fortune Teller (Dark)', connectionId: 'connection-872' },
  { from: 'region-041', to: 'region-144', exit: 'Dark World Lumberjack Shop', connectionId: 'connection-887' },
  { from: 'region-042', to: 'region-041', exit: 'Grassy Lawn Pegs' },
  { from: 'region-042', to: 'region-142', exit: 'Village of Outcasts Shop' },
  { from: 'region-043', to: 'region-007', exit: 'Bat Cave Drop Ledge Mirror Spot' },
  { from: 'region-043', to: 'region-146', exit: 'Dark World Hammer Peg Cave', connectionId: 'connection-852' },
  { from: 'region-043', to: 'region-041', exit: 'Peg Area Rocks' },
  { from: 'region-044', to: 'region-153', exit: 'Bumper Cave (Bottom)', connectionId: 'connection-853' },
  { from: 'region-044', to: 'region-003', exit: 'Bumper Cave Entrance Mirror Spot' },
  { from: 'region-044', to: 'region-041', exit: 'Bumper Cave Entrance Drop' },
  { from: 'region-045', to: 'region-041', exit: 'Bumper Cave Ledge Drop' },
  { from: 'region-045', to: 'region-153', exit: 'Bumper Cave (Top)', connectionId: 'connection-854' },
  { from: 'region-045', to: 'region-022', exit: 'Bumper Cave Ledge Mirror Spot', connectionId: 'connection-469' },
  { from: 'region-046', to: 'region-190', exit: 'Skull Woods First Section Hole (East)', connectionId: 'connection-1028' },
  { from: 'region-046', to: 'region-191', exit: 'Skull Woods First Section Hole (West)' },
  { from: 'region-046', to: 'region-192', exit: 'Skull Woods First Section Hole (North)' },
  { from: 'region-046', to: 'region-189', exit: 'Skull Woods First Section Door', connectionId: 'connection-657' },
  { from: 'region-046', to: 'region-194', exit: 'Skull Woods Second Section Door (East)' },
  { from: 'region-047', to: 'region-193', exit: 'Skull Woods Second Section Hole' },
  { from: 'region-047', to: 'region-194', exit: 'Skull Woods Second Section Door (West)' },
  { from: 'region-047', to: 'region-195', exit: 'Skull Woods Final Section' },
  { from: 'region-048', to: 'region-203', exit: 'Misery Mire' },
  { from: 'region-048', to: 'region-154', exit: 'Mire Shed', connectionId: 'connection-877' },
  { from: 'region-048', to: 'region-014', exit: 'Desert Ledge (Northeast) Mirror Spot' },
  { from: 'region-048', to: 'region-013', exit: 'Desert Ledge Mirror Spot', connectionId: 'connection-439' },
  { from: 'region-048', to: 'region-015', exit: 'Desert Palace Stairs Mirror Spot' },
  { from: 'region-048', to: 'region-017', exit: 'Desert Palace Entrance (North) Mirror Spot' },
  { from: 'region-048', to: 'region-155', exit: 'Dark Desert Hint', connectionId: 'connection-871' },
  { from: 'region-048', to: 'region-084', exit: 'Dark Desert Fairy', connectionId: 'connection-867' },
  { from: 'region-049', to: 'region-158', exit: 'Spike Cave', connectionId: 'connection-857' },
  { from: 'region-049', to: 'region-029', exit: 'Spectacle Rock Mirror Spot' },
  { from: 'region-049', to: 'region-085', exit: 'Dark Death Mountain Fairy', connectionId: 'connection-868' },
  { from: 'region-050', to: 'region-053', exit: 'Dark Death Mountain Drop (East)', connectionId: 'connection-410' },
  { from: 'region-050', to: 'region-049', exit: 'Dark Death Mountain Drop (West)', connectionId: 'connection-409' },
  { from: 'region-050', to: 'region-228', exit: 'Ganons Tower' },
  { from: 'region-050', to: 'region-156', exit: 'Superbunny Cave (Top)', connectionId: 'connection-881' },
  { from: 'region-050', to: 'region-159', exit: 'Hookshot Cave', connectionId: 'connection-858' },
  { from: 'region-050', to: 'region-024', exit: 'East Death Mountain (Top) Mirror Spot', connectionId: 'connection-423' },
  { from: 'region-050', to: 'region-208', exit: 'Turtle Rock' },
  { from: 'region-051', to: 'region-214', exit: 'Dark Death Mountain Ledge (East)' },
  { from: 'region-051', to: 'region-212', exit: 'Dark Death Mountain Ledge (West)' },
  { from: 'region-051', to: 'region-032', exit: 'Mimic Cave Mirror Spot' },
  { from: 'region-051', to: 'region-025', exit: 'Spiral Cave Mirror Spot' },
  { from: 'region-052', to: 'region-027', exit: 'Isolated Ledge Mirror Spot', connectionId: 'connection-421' },
  { from: 'region-052', to: 'region-218', exit: 'Turtle Rock Isolated Ledge Entrance' },
  { from: 'region-053', to: 'region-157', exit: 'Superbunny Cave (Bottom)', connectionId: 'connection-882' },
  { from: 'region-053', to: 'region-108', exit: 'Cave Shop (Dark Death Mountain)' },
  { from: 'region-053', to: 'region-026', exit: 'Fairy Ascension Mirror Spot' },
  { from: 'region-054', to: 'region-050', exit: 'Floating Island Drop', connectionId: 'connection-416' },
  { from: 'region-054', to: 'region-160', exit: 'Hookshot Cave Back Entrance', connectionId: 'connection-904' },
  { from: 'region-054', to: 'region-031', exit: 'Floating Island Mirror Spot', connectionId: 'connection-422' },
  { from: 'region-055', to: 'region-050', exit: 'Turtle Rock Drop', connectionId: 'connection-1142' },
  { from: 'region-056', to: 'region-163', exit: 'Pyramid Entrance' },
  { from: 'region-056', to: 'region-034', exit: 'Pyramid Drop' },
];

export { DARK_REGION_GRAPH };
