/* @layer shared-game @kind data */
/**
 * The reachability graph of the first world: one row per passage out of a region.
 *
 * A row is a RULE, not a place. The exit name is the key the rule tables hang their
 * requirement off, and `connectionId` names the crossing the map draws for it when exactly
 * one crossing of the record collection joins the same pair of regions. Where none does, or
 * where several do, the row carries none: a mirror spot, a retry from the menu and a wing
 * boundary inside one room cross no tile at all, and a pair joined by two doors cannot say
 * which of them this passage is.
 *
 * Folded from Archipelago worlds/alttp/Regions.py (create_regions, the exits of each region)
 * and EntranceShuffle.py (mandatory_connections, default_connections,
 * default_dungeon_connections), open mode with entrance shuffle off.
 */
import type { RegionGraphRow } from '../../region.type';

const LIGHT_REGION_GRAPH: readonly RegionGraphRow[] = [
  { from: 'region-001', to: 'region-064', exit: 'Links House S&Q' },
  { from: 'region-001', to: 'region-174', exit: 'Sanctuary S&Q' },
  { from: 'region-001', to: 'region-118', exit: 'Old Man S&Q' },
  { from: 'region-001', to: 'region-059', exit: 'Uncle S&Q' },
  { from: 'region-002', to: 'region-058', exit: 'Blinds Hideout', connectionId: 'connection-353' },
  { from: 'region-002', to: 'region-059', exit: 'Hyrule Castle Secret Entrance Drop', connectionId: 'connection-376' },
  { from: 'region-002', to: 'region-005', exit: 'Zoras River' },
  { from: 'region-002', to: 'region-006', exit: 'Kings Grave Outer Rocks' },
  { from: 'region-002', to: 'region-063', exit: 'Dam', connectionId: 'connection-367' },
  { from: 'region-002', to: 'region-064', exit: 'Links House' },
  { from: 'region-002', to: 'region-066', exit: 'Tavern North', connectionId: 'connection-360' },
  { from: 'region-002', to: 'region-086', exit: 'Chicken House', connectionId: 'connection-361' },
  { from: 'region-002', to: 'region-087', exit: 'Aginahs Cave', connectionId: 'connection-306' },
  { from: 'region-002', to: 'region-088', exit: 'Sahasrahlas Hut', connectionId: 'connection-368' },
  { from: 'region-002', to: 'region-089', exit: 'Kakariko Well Drop', connectionId: 'connection-404' },
  { from: 'region-002', to: 'region-090', exit: 'Kakariko Well Cave', connectionId: 'connection-405' },
  { from: 'region-002', to: 'region-091', exit: 'Blacksmiths Hut', connectionId: 'connection-363' },
  { from: 'region-002', to: 'region-007', exit: 'Bat Cave Drop Ledge', connectionId: 'connection-182' },
  { from: 'region-002', to: 'region-093', exit: 'Bat Cave Cave', connectionId: 'connection-1293' },
  { from: 'region-002', to: 'region-094', exit: 'Sick Kids House', connectionId: 'connection-362' },
  { from: 'region-002', to: 'region-008', exit: 'Hobo Bridge' },
  { from: 'region-002', to: 'region-095', exit: 'Lost Woods Hideout Drop', connectionId: 'connection-322' },
  { from: 'region-002', to: 'region-096', exit: 'Lost Woods Hideout Stump', connectionId: 'connection-323' },
  { from: 'region-002', to: 'region-097', exit: 'Lumberjack Tree Tree', connectionId: 'connection-324' },
  { from: 'region-002', to: 'region-098', exit: 'Lumberjack Tree Cave', connectionId: 'connection-325' },
  { from: 'region-002', to: 'region-103', exit: 'Mini Moldorm Cave', connectionId: 'connection-316' },
  { from: 'region-002', to: 'region-104', exit: 'Ice Rod Cave', connectionId: 'connection-317' },
  { from: 'region-002', to: 'region-004', exit: 'Lake Hylia Central Island Pier' },
  { from: 'region-002', to: 'region-109', exit: 'Bonk Rock Cave', connectionId: 'connection-308' },
  { from: 'region-002', to: 'region-110', exit: 'Library', connectionId: 'connection-364' },
  { from: 'region-002', to: 'region-112', exit: 'Potion Shop', connectionId: 'connection-403' },
  { from: 'region-002', to: 'region-114', exit: 'Two Brothers House (East)' },
  { from: 'region-002', to: 'region-015', exit: 'Desert Palace Stairs', connectionId: 'connection-025' },
  { from: 'region-002', to: 'region-168', exit: 'Eastern Palace', connectionId: 'connection-258' },
  { from: 'region-002', to: 'region-018', exit: 'Master Sword Meadow' },
  { from: 'region-002', to: 'region-174', exit: 'Sanctuary', connectionId: 'connection-195' },
  { from: 'region-002', to: 'region-170', exit: 'Sanctuary Grave', connectionId: 'connection-200' },
  { from: 'region-002', to: 'region-003', exit: 'Death Mountain Entrance Rock' },
  { from: 'region-002', to: 'region-021', exit: 'Flute Spot 1' },
  { from: 'region-002', to: 'region-048', exit: 'Dark Desert Teleporter', connectionId: 'connection-051' },
  { from: 'region-002', to: 'region-034', exit: 'East Hyrule Teleporter', connectionId: 'connection-048' },
  { from: 'region-002', to: 'region-037', exit: 'South Hyrule Teleporter', connectionId: 'connection-049' },
  { from: 'region-002', to: 'region-041', exit: 'Kakariko Teleporter', connectionId: 'connection-050' },
  { from: 'region-002', to: 'region-067', exit: 'Elder House (East)' },
  { from: 'region-002', to: 'region-067', exit: 'Elder House (West)' },
  { from: 'region-002', to: 'region-062', exit: 'North Fairy Cave' },
  { from: 'region-002', to: 'region-062', exit: 'North Fairy Cave Drop' },
  { from: 'region-002', to: 'region-116', exit: 'Lost Woods Gamble', connectionId: 'connection-350' },
  { from: 'region-002', to: 'region-068', exit: 'Snitch Lady (East)', connectionId: 'connection-355' },
  { from: 'region-002', to: 'region-069', exit: 'Snitch Lady (West)', connectionId: 'connection-356' },
  { from: 'region-002', to: 'region-071', exit: 'Tavern (Front)', connectionId: 'connection-358' },
  { from: 'region-002', to: 'region-070', exit: 'Bush Covered House', connectionId: 'connection-357' },
  { from: 'region-002', to: 'region-072', exit: 'Light World Bomb Hut', connectionId: 'connection-359' },
  { from: 'region-002', to: 'region-073', exit: 'Kakariko Shop', connectionId: 'connection-400' },
  { from: 'region-002', to: 'region-102', exit: 'Long Fairy Cave', connectionId: 'connection-347' },
  { from: 'region-002', to: 'region-105', exit: 'Good Bee Cave', connectionId: 'connection-318' },
  { from: 'region-002', to: 'region-106', exit: '20 Rupee Cave', connectionId: 'connection-319' },
  { from: 'region-002', to: 'region-107', exit: 'Cave Shop (Lake Hylia)', connectionId: 'connection-401' },
  { from: 'region-002', to: 'region-060', exit: 'Waterfall of Wishing', connectionId: 'connection-340' },
  { from: 'region-002', to: 'region-019', exit: 'Hyrule Castle Main Gate' },
  { from: 'region-002', to: 'region-077', exit: 'Bonk Fairy (Light)', connectionId: 'connection-338' },
  { from: 'region-002', to: 'region-115', exit: '50 Rupee Cave', connectionId: 'connection-320' },
  { from: 'region-002', to: 'region-074', exit: 'Fortune Teller (Light)', connectionId: 'connection-351' },
  { from: 'region-002', to: 'region-079', exit: 'Lake Hylia Fairy', connectionId: 'connection-344' },
  { from: 'region-002', to: 'region-080', exit: 'Light Hype Fairy', connectionId: 'connection-345' },
  { from: 'region-002', to: 'region-081', exit: 'Desert Fairy', connectionId: 'connection-346' },
  { from: 'region-002', to: 'region-076', exit: 'Lumberjack House', connectionId: 'connection-369' },
  { from: 'region-002', to: 'region-075', exit: 'Lake Hylia Fortune Teller', connectionId: 'connection-352' },
  { from: 'region-002', to: 'region-111', exit: 'Kakariko Gamble Game', connectionId: 'connection-349' },
  { from: 'region-002', to: 'region-034', exit: 'Top of Pyramid', connectionId: 'connection-048' },
  { from: 'region-003', to: 'region-117', exit: 'Old Man Cave (West)', connectionId: 'connection-380' },
  { from: 'region-003', to: 'region-002', exit: 'Death Mountain Entrance Drop', connectionId: 'connection-1450' },
  { from: 'region-004', to: 'region-113', exit: 'Capacity Upgrade', connectionId: 'connection-339' },
  { from: 'region-004', to: 'region-039', exit: 'Lake Hylia Central Island Teleporter' },
  { from: 'region-006', to: 'region-061', exit: 'Kings Grave', connectionId: 'connection-313' },
  { from: 'region-006', to: 'region-002', exit: 'Kings Grave Inner Rocks' },
  { from: 'region-007', to: 'region-092', exit: 'Bat Cave Drop', connectionId: 'connection-310' },
  { from: 'region-009', to: 'region-099', exit: 'Cave 45', connectionId: 'connection-321' },
  { from: 'region-010', to: 'region-100', exit: 'Graveyard Cave', connectionId: 'connection-315' },
  { from: 'region-012', to: 'region-114', exit: 'Two Brothers House (West)' },
  { from: 'region-013', to: 'region-017', exit: 'Desert Palace Entrance (North) Rocks' },
  { from: 'region-013', to: 'region-164', exit: 'Desert Palace Entrance (West)' },
  { from: 'region-014', to: 'region-101', exit: 'Checkerboard Cave' },
  { from: 'region-015', to: 'region-165', exit: 'Desert Palace Entrance (South)' },
  { from: 'region-016', to: 'region-002', exit: 'Desert Palace Stairs Drop', connectionId: 'connection-1501' },
  { from: 'region-016', to: 'region-164', exit: 'Desert Palace Entrance (East)' },
  { from: 'region-017', to: 'region-167', exit: 'Desert Palace Entrance (North)' },
  { from: 'region-017', to: 'region-013', exit: 'Desert Ledge Return Rocks' },
  { from: 'region-019', to: 'region-059', exit: 'Hyrule Castle Secret Entrance Stairs', connectionId: 'connection-378' },
  { from: 'region-019', to: 'region-169', exit: 'Hyrule Castle Entrance (South)' },
  { from: 'region-020', to: 'region-169', exit: 'Hyrule Castle Entrance (East)' },
  { from: 'region-020', to: 'region-169', exit: 'Hyrule Castle Entrance (West)' },
  { from: 'region-020', to: 'region-175', exit: 'Agahnims Tower' },
  { from: 'region-020', to: 'region-019', exit: 'Hyrule Castle Ledge Courtyard Drop', connectionId: 'connection-039' },
  { from: 'region-021', to: 'region-117', exit: 'Old Man Cave (East)' },
  { from: 'region-021', to: 'region-118', exit: 'Old Man House (Bottom)', connectionId: 'connection-370' },
  { from: 'region-021', to: 'region-119', exit: 'Old Man House (Top)' },
  { from: 'region-021', to: 'region-120', exit: 'Death Mountain Return Cave (East)', connectionId: 'connection-1629' },
  { from: 'region-021', to: 'region-121', exit: 'Spectacle Rock Cave', connectionId: 'connection-330' },
  { from: 'region-021', to: 'region-123', exit: 'Spectacle Rock Cave Peak' },
  { from: 'region-021', to: 'region-122', exit: 'Spectacle Rock Cave (Bottom)', connectionId: 'connection-385' },
  { from: 'region-021', to: 'region-023', exit: 'Broken Bridge (West)' },
  { from: 'region-021', to: 'region-049', exit: 'Death Mountain Teleporter' },
  { from: 'region-022', to: 'region-002', exit: 'Death Mountain Return Ledge Drop', connectionId: 'connection-1476' },
  { from: 'region-022', to: 'region-120', exit: 'Death Mountain Return Cave (West)', connectionId: 'connection-390' },
  { from: 'region-023', to: 'region-021', exit: 'Broken Bridge (East)' },
  { from: 'region-023', to: 'region-125', exit: 'Paradox Cave (Bottom)', connectionId: 'connection-331' },
  { from: 'region-023', to: 'region-127', exit: 'Paradox Cave (Middle)' },
  { from: 'region-023', to: 'region-053', exit: 'East Death Mountain Teleporter' },
  { from: 'region-023', to: 'region-124', exit: 'Hookshot Fairy', connectionId: 'connection-348' },
  { from: 'region-023', to: 'region-026', exit: 'Fairy Ascension Rocks', connectionId: 'connection-012' },
  { from: 'region-023', to: 'region-130', exit: 'Spiral Cave (Bottom)', connectionId: 'connection-392' },
  { from: 'region-024', to: 'region-127', exit: 'Paradox Cave (Top)', connectionId: 'connection-332' },
  { from: 'region-024', to: 'region-028', exit: 'Death Mountain (Top)', connectionId: 'connection-1442' },
  { from: 'region-024', to: 'region-025', exit: 'Spiral Cave Ledge Access', connectionId: 'connection-014' },
  { from: 'region-024', to: 'region-023', exit: 'East Death Mountain Drop', connectionId: 'connection-016' },
  { from: 'region-024', to: 'region-055', exit: 'Turtle Rock Teleporter' },
  { from: 'region-024', to: 'region-027', exit: 'Fairy Ascension Ledge' },
  { from: 'region-025', to: 'region-129', exit: 'Spiral Cave', connectionId: 'connection-333' },
  { from: 'region-025', to: 'region-023', exit: 'Spiral Cave Ledge Drop', connectionId: 'connection-017' },
  { from: 'region-026', to: 'region-023', exit: 'Fairy Ascension Drop', connectionId: 'connection-018' },
  { from: 'region-026', to: 'region-131', exit: 'Fairy Ascension Cave (Bottom)', connectionId: 'connection-395' },
  { from: 'region-027', to: 'region-026', exit: 'Fairy Ascension Ledge Drop', connectionId: 'connection-019' },
  { from: 'region-027', to: 'region-133', exit: 'Fairy Ascension Cave (Top)', connectionId: 'connection-396' },
  { from: 'region-028', to: 'region-024', exit: 'East Death Mountain (Top)', connectionId: 'connection-010' },
  { from: 'region-028', to: 'region-177', exit: 'Tower of Hera' },
  { from: 'region-028', to: 'region-021', exit: 'Death Mountain Drop', connectionId: 'connection-009' },
  { from: 'region-029', to: 'region-028', exit: 'Spectacle Rock Drop', connectionId: 'connection-011' },
  { from: 'region-032', to: 'region-161', exit: 'Mimic Cave', connectionId: 'connection-862' },
];

export { LIGHT_REGION_GRAPH };
