import type { Requirement } from '../../types';
import {
  hasSword,
  canLiftRocks, canLiftHeavyRocks,
  canUseBombs,
  hasMiseryMireMedallion, hasTurtleRockMedallion,
  hasCrystals,
} from '../helpers';

/** Region entrance rules for Dark World locations. */
const DARK_WORLD_REGION_RULES: Record<string, Requirement> = {
  // Dark World overworld connections
  'Dark Lake Hylia Drop (East)': {
    or: [{ and: ['Moon Pearl', 'Flippers'] }, 'Magic Mirror'],
  },
  'Dark Lake Hylia Drop (South)': { and: ['Moon Pearl', 'Flippers'] },
  'Dark Lake Hylia Ledge Fairy': { and: ['Moon Pearl', canUseBombs] },
  'Dark Lake Hylia Ledge Spike Cave': canLiftRocks,
  'Thieves Town': 'Moon Pearl',
  'Skull Woods First Section Hole (North)': 'Moon Pearl',
  'Skull Woods Second Section Hole': 'Moon Pearl',
  'Skull Woods Final Section': 'Fire Rod',
  'Skull Woods First Section Bomb Jump': canUseBombs,
  'East Dark World Bridge': 'Hammer',
  'West Dark World Gap': 'Hookshot',
  'Village of Outcasts Heavy Rock': canLiftHeavyRocks,
  'Village of Outcasts Eastern Rocks': canLiftHeavyRocks,
  'Village of Outcasts Pegs': { and: ['Moon Pearl', 'Hammer'] },
  'Peg Area Rocks': { and: ['Moon Pearl', canLiftHeavyRocks] },
  'Bumper Cave Entrance Rock': canLiftRocks,
  'Bumper Cave Exit (Top)': 'Cape',
  'Bumper Cave Exit (Bottom)': { or: ['Cape', 'Hookshot'] },
  'Hookshot Cave': canLiftRocks,
  'Hype Cave': canUseBombs,
  'Brewery': canUseBombs,
  'East Dark World River Pier': 'Flippers',
  'Dark Lake Hylia Teleporter': 'Flippers',
  'Catfish Entrance Rock': canLiftRocks,
  'Pyramid Hole': 'Beat Agahnim 2',
  'Northeast Dark World Hammer Bridge': 'Hammer',
  'Dark Grassy Lawn Pegs': { and: ['Moon Pearl', 'Hammer'] },

  // Dungeon entrances from Dark World
  'Misery Mire': { and: [hasSword, hasMiseryMireMedallion] },
  'Turtle Rock': { and: [hasSword, hasTurtleRockMedallion, 'Moon Pearl'] },
  'Ganons Tower': hasCrystals(7),

  // Mirror spots (DW → LW)
  'Bumper Cave Entrance Mirror Spot': 'Magic Mirror',
  'Maze Race Mirror Spot': 'Magic Mirror',
  'Cave 45 Mirror Spot': 'Magic Mirror',
  'Bombos Tablet Mirror Spot': 'Magic Mirror',
  'Kings Grave Mirror Spot': { and: ['Moon Pearl', 'Magic Mirror'] },
  'Graveyard Ledge Mirror Spot': { and: ['Moon Pearl', 'Magic Mirror'] },
  'Hyrule Castle Ledge Mirror Spot': 'Magic Mirror',
  'East Death Mountain (Top) Mirror Spot': 'Magic Mirror',
  'Lake Hylia Island Mirror Spot': 'Magic Mirror',
  'Spectacle Rock Mirror Spot': 'Magic Mirror',
  'Desert Ledge Mirror Spot': 'Magic Mirror',
  'Desert Palace Stairs Mirror Spot': 'Magic Mirror',
  'Desert Palace Entrance (North) Mirror Spot': 'Magic Mirror',
  'Floating Island Mirror Spot': 'Magic Mirror',
  'Mimic Cave Mirror Spot': 'Magic Mirror',
  'East Dark World Mirror Spot': 'Magic Mirror',
  'South Dark World Mirror Spot': 'Magic Mirror',
  'West Dark World Mirror Spot': 'Magic Mirror',
  'Dark Lake Hylia Mirror Spot': 'Magic Mirror',
  'Northeast Dark World Mirror Spot': 'Magic Mirror',
  'Skull Woods Mirror Spot': 'Magic Mirror',
  'Skull Woods Forest Mirror Spot': 'Magic Mirror',
  'Dark Desert Mirror Spot': 'Magic Mirror',
  'Dark Desert North Mirror Spot': 'Magic Mirror',
  'Dark Desert Lone Stairs Mirror Spot': 'Magic Mirror',
  'Bumper Cave Ledge Mirror Spot': 'Magic Mirror',
  'Dark Death Mountain (West Bottom) Mirror Spot': 'Magic Mirror',
  'Dark Death Mountain (East Bottom) Mirror Spot': 'Magic Mirror',
  'Dark Death Mountain Ledge Mirror Spot': 'Magic Mirror',
  'Dark Death Mountain Isolated Ledge Mirror Spot': 'Magic Mirror',
  'Death Mountain Floating Island Mirror Spot': 'Magic Mirror',
  'Dark Lake Hylia Central Island Mirror Spot': 'Magic Mirror',
};

export { DARK_WORLD_REGION_RULES };
