/* @layer shared-game @kind logic */
/**
 * Validates the raw `Connected.slot_data` object into RotpSlotData. 'malformed' when a
 * required field is missing or has the wrong type; 'version' when the slot was generated by a
 * world package of another version than this app's (AP_WORLD_VERSION), since its ids, options
 * and rules are not the ones this app reads, so the slot is refused instead of being half read.
 */
import { AP_WORLD_VERSION } from './ap-game';
import type { RotpPreRolled, RotpSlotData } from './slot-data.type';

type ParsedSlotData =
  | { kind: 'ok'; slotData: RotpSlotData }
  | { kind: 'malformed' }
  | { kind: 'version'; message: string };

const versionMessage = (worldVersion: string): string =>
  `World package version ${worldVersion} does not match this app (${AP_WORLD_VERSION}). `
  + 'Regenerate the game with the package this app saves.';

type OptionValue = string | number | boolean;

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const isOptionValue = (value: unknown): value is OptionValue =>
  typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean';

const parseOptions = (raw: unknown): Record<string, OptionValue> | null => {
  if (!isRecord(raw)) return null;
  const options: Record<string, OptionValue> = {};
  for (const [key, value] of Object.entries(raw)) {
    if (!isOptionValue(value)) return null;
    options[key] = value;
  }
  return options;
};

const parseMedallions = (raw: unknown): RotpSlotData['medallions'] | null => {
  if (!isRecord(raw)) return null;
  const { mire, turtleRock } = raw;
  if (typeof mire !== 'string' || typeof turtleRock !== 'string') return null;
  return { mire, turtleRock };
};

/** The rolled values travel as they came; a later wave reads each one. */
const parsePreRolled = (raw: unknown): RotpPreRolled | undefined => {
  if (!isRecord(raw)) return undefined;
  const { pondDemands, shopPrices, capacity, deliverable } = raw;
  return {
    ...(pondDemands !== undefined ? { pondDemands } : {}),
    ...(shopPrices !== undefined ? { shopPrices } : {}),
    ...(capacity !== undefined ? { capacity } : {}),
    ...(deliverable !== undefined ? { deliverable } : {}),
  };
};

const MALFORMED: ParsedSlotData = { kind: 'malformed' };

const parseSlotData = (raw: unknown): ParsedSlotData => {
  if (!isRecord(raw)) return MALFORMED;
  const { worldVersion, deathLink } = raw;
  if (typeof worldVersion !== 'string') return MALFORMED;
  if (worldVersion !== AP_WORLD_VERSION) return { kind: 'version', message: versionMessage(worldVersion) };
  const options = parseOptions(raw.options);
  const medallions = parseMedallions(raw.medallions);
  if (options === null || medallions === null) return MALFORMED;
  const preRolled = parsePreRolled(raw.preRolled);
  return {
    kind: 'ok',
    slotData: {
      worldVersion,
      ...(typeof raw.seed === 'string' ? { seed: raw.seed } : {}),
      options,
      medallions,
      deathLink: deathLink === true || deathLink === 1,
      ...(preRolled !== undefined ? { preRolled } : {}),
    },
  };
};

export { parseSlotData };
export type { ParsedSlotData };
