/* @layer shared-types @kind logic */
/**
 * The ONLY join tables between the renderer's friendly `window.api` method names
 * and the namespaced IPC channels. Every value is `satisfies`-checked to be a real
 * channel, and the friendly API types are derived from these (see ./api.ts), so a
 * method's signature is never hand-written twice. Nested namespaces (updater,
 * shadowCasting, screenEditor) are wired explicitly in the preload, not here.
 */
import type { InvokeContract } from './invoke-contract';
import type { SendContract } from './send-contract';
import type { EventContract } from './event-contract';

const INVOKE_MAP = {
  getUserDataPath: 'app:getUserDataPath',
  getSystemDiagnostics: 'diagnostics:getSystem',
  getDataLocation: 'storage:getLocation',
  revealDataFolder: 'storage:reveal',
  revealProfileFolder: 'storage:revealProfile',
  getStorageSummary: 'storage:getSummary',
  fileReadBytes: 'file:readBytes',
  fileReadText: 'file:readText',
  fileWriteBytes: 'file:writeBytes',
  fileWriteText: 'file:writeText',
  fileList: 'file:list',
  fileRemove: 'file:remove',
  fileExists: 'file:exists',
  fileMkdir: 'file:mkdir',
  fileStat: 'file:stat',
  readWasmBytes: 'wasm:readBytes',
  isMaximized: 'window:isMaximized',
  setAlwaysOnTop: 'window:setAlwaysOnTop',
  setAudioMuted: 'window:setAudioMuted',
  isAudioMuted: 'window:isAudioMuted',
  isFullscreen: 'window:isFullscreen',
  getRefreshRate: 'display:getRefreshRate',
  getSyncedRateStatus: 'display:getSyncedRateStatus',
  setSyncedRatePreference: 'display:setSyncedRatePreference',
  applyRefreshRate: 'display:applyRefreshRate',
  openRomDialog: 'dialog:openRom',
  pickFile: 'dialog:pickFile',
  saveFile: 'dialog:saveFile',
  listProfiles: 'profiles:list',
  createProfile: 'profiles:create',
  deleteProfile: 'profiles:delete',
  setLastProfile: 'profiles:setLast',
  getAppState: 'profiles:getAppState',
  updateLastPlayed: 'profiles:updateLastPlayed',
  updateProfile: 'profiles:update',
  listRoms: 'roms:list',
  listRomsWithStatus: 'roms:listWithStatus',
  importRom: 'roms:import',
  importRomUrl: 'roms:importUrl',
  deleteRom: 'roms:delete',
  getRomInfo: 'roms:getInfo',
  checkAssets: 'assets:check',
  loadAssets: 'assets:load',
  extractAssets: 'assets:extract',
  writeSram: 'saves:writeSram',
  readSram: 'saves:readSram',
  writeState: 'saves:writeState',
  readState: 'saves:readState',
  listStates: 'saves:listStates',
  writeScreenshot: 'saves:writeScreenshot',
  readScreenshot: 'saves:readScreenshot',
  getSlotInfos: 'saves:getSlotInfos',
  createNormalSave: 'saves:normal:create',
  listNormalSaves: 'saves:normal:list',
  loadNormalSave: 'saves:normal:load',
  loadNormalScreenshot: 'saves:normal:screenshot',
  overwriteNormalSave: 'saves:normal:overwrite',
  deleteNormalSave: 'saves:normal:delete',
  renameNormalSave: 'saves:normal:rename',
  createAutoSave: 'saves:auto:create',
  listAutoSaves: 'saves:auto:list',
  loadAutoSave: 'saves:auto:load',
  loadAutoScreenshot: 'saves:auto:screenshot',
  deleteAutoSave: 'saves:auto:delete',
  pruneAutoSaves: 'saves:auto:prune',
  readConfig: 'config:read',
  writeConfig: 'config:write',
  importMsu: 'msu:import',
  importMsuFile: 'msu:importFile',
  listMsuPacks: 'msu:listPacks',
  getMsuPackFiles: 'msu:getPackFiles',
  deleteMsuPack: 'msu:deletePack',
  getMsuTrackList: 'msu:getTrackList',
  readMsuTrackFile: 'msu:readTrackFile',
  readMsulFile: 'msu:readMsulFile',
  listMsuAudioFiles: 'msu:listAudioFiles',
  readMsuManifest: 'msu:readManifest',
  writeMsuManifest: 'msu:writeManifest',
  createMsuPack: 'msu:createPack',
  renameMsuPack: 'msu:renamePack',
  renameMsuTrackFile: 'msu:renameTrackFile',
  deleteMsuTrackFile: 'msu:deleteTrackFile',
  writeMsuTrackFile: 'msu:writeTrackFile',
  analyzeMsuOptimize: 'msu:optimize:analyze',
  runMsuOptimize: 'msu:optimize:run',
  readMsuResume: 'msu:readResume',
  writeMsuResume: 'msu:writeResume',
  deleteMsuResume: 'msu:deleteResume',
  getFfmpegState: 'ffmpeg:getState',
  installFfmpeg: 'ffmpeg:install',
  probeAudioFile: 'ffmpeg:probeAudio',
  listLanguages: 'languages:list',
  extractLanguage: 'languages:extract',
  extractLanguageFromFile: 'languages:extractFromFile',
  extractLanguageFromUrl: 'languages:extractFromUrl',
  deleteLanguage: 'languages:delete',
  getLanguage: 'languages:getLanguage',
  listSessions: 'sessions:list',
  saveSession: 'sessions:save',
  saveTrackerState: 'tracker:save',
  loadTrackerState: 'tracker:load',
  readInputProfiles: 'inputProfiles:read',
  writeInputProfiles: 'inputProfiles:write',
  readStickCalibration: 'stickCalibration:read',
  writeStickCalibration: 'stickCalibration:write',
  readTriggerCalibration: 'triggerCalibration:read',
  writeTriggerCalibration: 'triggerCalibration:write',
  listControllers: 'controller:list',
  listHidDevices: 'controller:list-hid-devices',
  rescanControllers: 'controller:rescan',
  rumbleController: 'controller:rumble',
  vibratePattern: 'controller:vibrate-pattern',
  addControllerMapping: 'controller:add-mapping',
  writeHidDebugFile: 'controller:write-debug-capture',
  startControllerRawCapture: 'controller:start-raw-capture',
  stopControllerRawCapture: 'controller:stop-raw-capture',
  startJoystickCapture: 'controller:start-joystick-capture',
  stopJoystickCapture: 'controller:stop-joystick-capture',
  listJoysticks: 'controller:list-joysticks',
  mappingForGuid: 'controller:mapping-for-guid',
  sdlVersion: 'controller:sdl-version',
  releaseControllerHold: 'controller:release-hold',
  restoreControllerHold: 'controller:restore-hold',
  extractSprites: 'sprites:extract',
  checkSpritesExtracted: 'sprites:check',
  deleteSprites: 'sprites:delete',
  getSpritePath: 'sprites:getPath',
  loadSpriteDebug: 'spriteDebug:load',
  saveSpriteDebug: 'spriteDebug:save',
  loadSpriteReview: 'spriteReview:load',
  saveSpriteReview: 'spriteReview:save',
  loadConnectionReview: 'connectionReview:load',
  saveConnectionReview: 'connectionReview:save',
  loadNavReview: 'navReview:load',
  saveNavReview: 'navReview:save',
  loadReview: 'review:load',
  saveReview: 'review:save',
  loadRecommendations: 'recommendations:load',
  applyRecommendationPass: 'recommendations:applyPass',
  decideRecommendation: 'recommendations:decide',
  getTestArgs: 'test:getArgs',
  takeScreenshot: 'test:screenshot',
  getDumpLayersSlot: 'debug:getDumpLayersSlot',
  getHoverTile: 'debug:getHoverTile',
  writeDumpLayers: 'debug:dumpLayers',
  getDumpNavSlot: 'debug:getDumpNavSlot',
  writeDumpNav: 'debug:dumpNav',
  getSimRunConfig: 'debug:getSimRunConfig',
  writeSimRun: 'debug:writeSimRun',
  appendSimLog: 'sim:appendLog',
  openSimLog: 'sim:openLog',
  createGithubIssue: 'github:createIssue',
} as const satisfies Record<string, keyof InvokeContract>;

const SEND_MAP = {
  minimize: 'window:minimize',
  maximize: 'window:maximize',
  close: 'window:close',
  openDevTools: 'window:openDevTools',
  toggleFullscreen: 'window:toggleFullscreen',
  setFullscreen: 'window:setFullscreen',
  setAspectRatioLock: 'window:setAspectRatioLock',
  shellReady: 'window:shellReady',
} as const satisfies Record<string, keyof SendContract>;

const EVENT_MAP = {
  onMaximizedChange: 'window:maximized',
  onFullscreenChange: 'window:fullscreen',
  onLogEntry: 'log:entry',
  onImportProgress: 'import:progress',
  onMsuOpenPack: 'msu:openPack',
  onMsuOptimizeProgress: 'msu:optimize:progress',
  onFfmpegProgress: 'ffmpeg:progress',
  onControllerAdded: 'controller:added',
  onControllerState: 'controller:state',
  onControllerRemoved: 'controller:removed',
  onControllerDevices: 'controller:devices',
  onControllerRaw: 'controller:raw',
  onControllerJoystick: 'controller:joystick',
  onControllerHoldChanged: 'controller:hold-changed',
} as const satisfies Record<string, keyof EventContract>;

export { INVOKE_MAP, SEND_MAP, EVENT_MAP };
