/* @layer tooling-scripts @kind logic */
/**
 * The paths a safety snapshot captures: everything git does NOT already protect.
 *
 * Tracked files need no help — they are in the object store the moment they are
 * committed, and recoverable from any clone. What is irreplaceable is the gitignored
 * material a checkout carries: the agent's own instructions, the record dataset the
 * private vault supplies, the save-state fixtures the baselines pin to, and the ROMs
 * the user provided. Losing any of those costs anything from minutes (a bootstrap
 * re-render) to everything (a ROM nobody else has).
 *
 * Deliberately NOT here: node_modules, dist, release and apps/web/public/wasm. All are
 * regenerated by a build, all are large, and snapshotting them would turn a cheap
 * safety net into gigabytes per operation.
 */
const PROTECTED_ROOTS = [
  '.claude',
  'shared/game/data/records',
  'tests/fixtures/save-states',
  'test-roms',
  'assets',
  'CLAUDE.md',
  'AGENTS.md',
  '.ai-config.json',
  '.mcp.json',
];

/**
 * Snapshots live in their own ref namespace, NOT under refs/heads.
 *
 * This is what stops them ever leaving the machine. `git push`, `git push --all` and
 * `git push --tags` only ever send refs/heads/* and refs/tags/*, so a ref parked here is
 * invisible to all of them — no per-branch remote config to get out of step, and no hook
 * that has to fire. That matters because these snapshots carry ROMs and save data, and
 * the project repo is public.
 *
 * They remain ordinary commits: `git log refs/safety/<name>`, `git show`, `git archive`
 * and `git diff` all work on them exactly as on a branch. `git branch` does not list
 * them, which is what `npm run safety -- list` is for.
 *
 * The one command that would still carry them is `git push --mirror`, which pushes every
 * ref by definition. Do not run that against this repo.
 */
const SAFETY_NAMESPACE = 'refs/safety';

/**
 * Retention: age alone is not allowed to leave us with nothing. Whatever their age, the
 * newest few snapshots always survive, so a series of operations in one sitting cannot
 * prune away the state from before the sitting began.
 */
const KEEP_MIN = 2;
const KEEP_DAYS = 7;

export { KEEP_DAYS, KEEP_MIN, PROTECTED_ROOTS, SAFETY_NAMESPACE };
