/* @layer tooling-scripts @kind logic */
/**
 * The gitignored paths a safety snapshot captures: the agent's instructions, the vault
 * dataset, the save-state fixtures, the user's ROMs. Not node_modules, dist, release or
 * apps/web/public/wasm: regenerated by a build, and gigabytes per operation.
 */
const PROTECTED_ROOTS = [
  '.claude',
  'shared/game/data/records',
  'tests/fixtures/save-states',
  'test-roms',
  'assets',
  'CLAUDE.md',
  'AGENTS.md',
  '.ai-config.json',
  '.mcp.json',
];

/**
 * Snapshots live outside refs/heads so `git push`, `--all` and `--tags` never send
 * them: they carry ROMs and save data, and the repo is public. They are ordinary
 * commits for log/show/diff; `npm run safety -- list` lists them. `git push --mirror`
 * would still carry them. Do not run that against this repo.
 */
const SAFETY_NAMESPACE = 'refs/safety';

// Retention: the newest KEEP_MIN always survive, whatever their age.
const KEEP_MIN = 2;
const KEEP_DAYS = 7;

export { KEEP_DAYS, KEEP_MIN, PROTECTED_ROOTS, SAFETY_NAMESPACE };
