/* @layer shared-game @kind data */
/**
 * Glyphs the dialogue fonts lack, drawn in the game's own style, so any name another game sends
 * shows as it was typed. The core writes each one into a spare slot of the active font
 * (core/game-hooks/dialog_extra_glyphs.c) and the composer encodes the character to that slot.
 *
 * Every glyph is the font's own cell: 8 columns by 16 rows, the top 8 rows one tile and the bottom
 * 8 the next. In the rows, ' ' is the transparent ground, '.' the dark edge (palette entry 1) and
 * '#' the letter's body (entry 2). The body is one pixel wide like the game's letters, starts on
 * column 1, and sits on the same lines: capitals from row 2, the baseline on row 12, descenders to
 * row 14. The edge rings the body on every side, the way every glyph in the sheet has it. The
 * width is the pen advance, body plus one edge column on each side, and every edge pixel lies
 * inside it because the engine draws only that many columns.
 *
 * The list is in priority order. A font with fewer spare slots than missing characters takes them
 * from the top, so the characters that turn up most in player and item names come first.
 */

interface ExtraGlyph {
  char: string;
  /** Pen advance in pixels, 1..8, as the font's width table stores it. */
  width: number;
  /** 16 rows of 8 pixels: ' ' ground, '.' edge, '#' body. */
  rows: readonly string[];
}

const EXTRA_GLYPHS: readonly ExtraGlyph[] = [
  // underscore
  {
    char: '_',
    width: 6,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '......  ',
      '.####.  ',
      '......  ',
      '        ',
    ],
  },
  // colon
  {
    char: ':',
    width: 4,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '....    ',
      '.##.    ',
      '.##.    ',
      '....    ',
      '        ',
      '....    ',
      '.##.    ',
      '.##.    ',
      '....    ',
      '        ',
      '        ',
    ],
  },
  // ampersand
  {
    char: '&',
    width: 7,
    rows: [
      '        ',
      ' ....   ',
      '..##..  ',
      '.#..#.  ',
      '.#..#.  ',
      '.#..#.  ',
      '..##... ',
      '..##.#. ',
      '.#..#.. ',
      '.#..#.  ',
      '.#..#.  ',
      '.#..#.. ',
      '..##.#. ',
      ' ...... ',
      '        ',
      '        ',
    ],
  },
  // hyphen
  {
    char: '-',
    width: 6,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '......  ',
      '.####.  ',
      '......  ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // apostrophe
  {
    char: "'",
    width: 4,
    rows: [
      '....    ',
      '.##.    ',
      '.##.    ',
      '..#.    ',
      '.#..    ',
      '...     ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // slash
  {
    char: '/',
    width: 6,
    rows: [
      '        ',
      '   ...  ',
      '   .#.  ',
      '  ..#.  ',
      '  .#..  ',
      '  .#.   ',
      ' ..#.   ',
      ' .#..   ',
      ' .#.    ',
      '..#.    ',
      '.#..    ',
      '.#.     ',
      '.#.     ',
      '...     ',
      '        ',
      '        ',
    ],
  },
  // plus
  {
    char: '+',
    width: 7,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '  ...   ',
      '  .#.   ',
      '  .#.   ',
      '...#... ',
      '.#####. ',
      '...#... ',
      '  .#.   ',
      '  .#.   ',
      '  ...   ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // number sign
  {
    char: '#',
    width: 7,
    rows: [
      '        ',
      '        ',
      ' .....  ',
      ' .#.#.  ',
      '..#.#.. ',
      '.#####. ',
      '..#.#.. ',
      ' .#.#.  ',
      '..#.#.. ',
      '.#####. ',
      '..#.#.. ',
      ' .#.#.  ',
      ' .....  ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // asterisk
  {
    char: '*',
    width: 7,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '  ...   ',
      '...#... ',
      '.#.#.#. ',
      '..###.. ',
      '.#.#.#. ',
      '...#... ',
      '  ...   ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // percent
  {
    char: '%',
    width: 7,
    rows: [
      '        ',
      '....... ',
      '.##..#. ',
      '.##..#. ',
      '....#.. ',
      '  ..#.  ',
      '  .#..  ',
      '  .#.   ',
      ' ..#.   ',
      ' .#..   ',
      '..#.... ',
      '.#..##. ',
      '.#..##. ',
      '....... ',
      '        ',
      '        ',
    ],
  },
  // semicolon
  {
    char: ';',
    width: 4,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '....    ',
      '.##.    ',
      '.##.    ',
      '....    ',
      '        ',
      '....    ',
      '.##.    ',
      '.##.    ',
      '..#.    ',
      '.#..    ',
      '...     ',
    ],
  },
  // equals
  {
    char: '=',
    width: 6,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '......  ',
      '.####.  ',
      '......  ',
      '......  ',
      '.####.  ',
      '......  ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // left bracket
  {
    char: '[',
    width: 5,
    rows: [
      '.....   ',
      '.###.   ',
      '.##..   ',
      '.##.    ',
      '.##.    ',
      '.##.    ',
      '.##.    ',
      '.##.    ',
      '.##.    ',
      '.##.    ',
      '.##.    ',
      '.##.    ',
      '.##..   ',
      '.###.   ',
      '.....   ',
      '        ',
    ],
  },
  // right bracket
  {
    char: ']',
    width: 5,
    rows: [
      '.....   ',
      '.###.   ',
      '..##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##.   ',
      '..##.   ',
      '.###.   ',
      '.....   ',
      '        ',
    ],
  },
  // left pointer, drawn as the US font's own
  {
    char: '<',
    width: 8,
    rows: [
      '        ',
      '        ',
      '        ',
      '   ...  ',
      '  ..#.  ',
      ' ..##.  ',
      '..###.  ',
      '.####.  ',
      '..###.  ',
      ' ..##.  ',
      '  ..#.  ',
      '   ...  ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // right pointer, drawn as the US font's own
  {
    char: '>',
    width: 8,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '...     ',
      '.#..    ',
      '.##..   ',
      '.###..  ',
      '.####.  ',
      '.###..  ',
      '.##..   ',
      '.#..    ',
      '...     ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // tilde
  {
    char: '~',
    width: 7,
    rows: [
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      ' ...... ',
      '..#..#. ',
      '.#.##.. ',
      '......  ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // at sign
  {
    char: '@',
    width: 7,
    rows: [
      '        ',
      '        ',
      ' .....  ',
      '..###.. ',
      '.#...#. ',
      '.#...#. ',
      '.#.###. ',
      '.#.#.#. ',
      '.#.#.#. ',
      '.#.###. ',
      '.#..... ',
      '.#..... ',
      '..####. ',
      ' ...... ',
      '        ',
      '        ',
    ],
  },
  // caret
  {
    char: '^',
    width: 7,
    rows: [
      '        ',
      '  ...   ',
      ' ..#..  ',
      '..#.#.. ',
      '.#...#. ',
      '... ... ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // grave accent
  {
    char: '`',
    width: 4,
    rows: [
      '...     ',
      '.#..    ',
      '..#.    ',
      ' ...    ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
      '        ',
    ],
  },
  // left brace
  {
    char: '{',
    width: 6,
    rows: [
      '  ....  ',
      ' ..##.  ',
      ' .##..  ',
      ' .##.   ',
      ' .##.   ',
      '..##.   ',
      '.##..   ',
      '.#..    ',
      '.##..   ',
      '..##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##..  ',
      ' ..##.  ',
      '  ....  ',
      '        ',
    ],
  },
  // right brace
  {
    char: '}',
    width: 6,
    rows: [
      '....    ',
      '.##..   ',
      '..##.   ',
      ' .##.   ',
      ' .##.   ',
      ' .##..  ',
      ' ..##.  ',
      '  ..#.  ',
      ' ..##.  ',
      ' .##..  ',
      ' .##.   ',
      ' .##.   ',
      '..##.   ',
      '.##..   ',
      '....    ',
      '        ',
    ],
  },
  // vertical bar
  {
    char: '|',
    width: 3,
    rows: [
      '...     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '.#.     ',
      '...     ',
    ],
  },
  // backslash
  {
    char: '\\',
    width: 6,
    rows: [
      '        ',
      '...     ',
      '.#.     ',
      '.#..    ',
      '..#.    ',
      ' .#.    ',
      ' .#..   ',
      ' ..#.   ',
      '  .#.   ',
      '  .#..  ',
      '  ..#.  ',
      '   .#.  ',
      '   .#.  ',
      '   ...  ',
      '        ',
      '        ',
    ],
  },
  // dollar sign
  {
    char: '$',
    width: 7,
    rows: [
      '  ...   ',
      ' ..#..  ',
      '..###.. ',
      '.#.#.#. ',
      '.#.#... ',
      '.#.#.   ',
      '.#.#..  ',
      '..###.. ',
      ' ..#.#. ',
      '  .#.#. ',
      '...#.#. ',
      '.#.#.#. ',
      '..###.. ',
      ' ..#..  ',
      '  ...   ',
      '        ',
    ],
  },
];

export { EXTRA_GLYPHS };
export type { ExtraGlyph };
