import type { RegionConnection } from '../../../types';

export const DW_GANONS_TOWER_CONNECTIONS: RegionConnection[] = [
  { from: 'overworld', to: 'gt-0x9b', entrance: 'Tower Entrance', tags: ['transit:door', 'dir:two-way', 'ctx:dungeon-enter', 'barrier:crystals'] },
  { from: 'gt-0x05', to: 'gt-0xa5', entrance: 'Wizzrobe Return', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x0c', to: 'gt-0x0d', entrance: 'East to Agahnim', tags: ['transit:walk', 'dir:two-way', 'ctx:boss'] },
  { from: 'gt-0x0c', to: 'gt-0x1c', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x0d', to: 'gt-0x1d', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x1c', to: 'gt-0x1d', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x1c', to: 'gt-0x3c', entrance: 'Descent Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x1d', to: 'gt-0x3d', entrance: 'Descent Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x3c', to: 'gt-0x3d', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x3c', to: 'gt-0x4c', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x3d', to: 'gt-0x4d', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x4c', to: 'gt-0x4d', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x4c', to: 'gt-0x5c', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x4d', to: 'gt-0x5d', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x5b', to: 'gt-0x5c', entrance: 'East to Tile Room', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x5b', to: 'gt-0x6b', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x5c', to: 'gt-0x5d', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x5c', to: 'gt-0x6c', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x5d', to: 'gt-0x6d', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x6b', to: 'gt-0x6c', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x6b', to: 'gt-0x7b', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x6c', to: 'gt-0x6d', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x6c', to: 'gt-0x7c', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x6d', to: 'gt-0x7d', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x7b', to: 'gt-0x7c', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x7b', to: 'gt-0x8b', entrance: 'South to Hub', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x7c', to: 'gt-0x7d', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x7c', to: 'gt-0x8c', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x7d', to: 'gt-0x8d', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x8b', to: 'gt-0x8c', entrance: 'East to Hope Left', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x8b', to: 'gt-0x9b', entrance: 'South to Entrance', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x8c', to: 'gt-0x8d', entrance: 'East to Hope Right', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x8c', to: 'gt-0x9c', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x8d', to: 'gt-0x9d', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x95', to: 'gt-0x96', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x95', to: 'gt-0xa5', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x96', to: 'gt-0xa6', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9b', to: 'gt-0x9c', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9b', to: 'gt-0x95', entrance: 'Basement Stairs West', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9c', to: 'gt-0x9d', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9d', to: 'gt-0x96', entrance: 'Basement Stairs East', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0xa5', to: 'gt-0xa6', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0xa5', to: 'gt-0x05', entrance: 'Wizzrobe Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0xa6', to: 'gt-0x96', entrance: 'Big Key Return', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x8b', to: 'gt-0x0c', entrance: 'Ascent Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal', 'barrier:big-key'] },
  { from: 'gt-0x5b', to: 'gt-0x3c', entrance: 'Gauntlet Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9b', to: 'gt-0x8b', entrance: 'Hub Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal', 'barrier:small-key'] },
  { from: 'gt-0x7b', to: 'gt-0x5b', entrance: 'Gauntlet Entry', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9b', to: 'dw-43', entrance: 'Tower Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
  { from: 'gt-0x0c', to: 'dw-43', entrance: 'Ganon Warp', tags: ['transit:warp', 'dir:one-way', 'ctx:exit'] },
  { from: 'gt-0x3c', to: 'gt-0x1c', entrance: 'Ascent Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x6b', to: 'gt-0x5b', entrance: 'Gauntlet Entry 2', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9c', to: 'gt-0x8c', entrance: 'Left Path Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x9d', to: 'gt-0x8d', entrance: 'Right Path Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x4c', to: 'gt-0x5c', entrance: 'Tile Room Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x4d', to: 'gt-0x5d', entrance: 'Compass Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x7c', to: 'gt-0x6c', entrance: 'Mimics Return', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x7d', to: 'gt-0x6d', entrance: 'Conveyor Return', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'gt-0x8b', to: 'gt-0x7b', entrance: 'Gauntlet Access', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
];
