import type { RegionConnection } from '../../../types';

export const DW_ICE_PALACE_CONNECTIONS: RegionConnection[] = [
  { from: 'overworld', to: 'ip-0x9e', entrance: 'Palace Entrance', tags: ['transit:door', 'dir:two-way', 'ctx:dungeon-enter'] },
  { from: 'ip-0x0e', to: 'ip-0x1e', entrance: 'Boss Return', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x1e', to: 'ip-0x1f', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x1e', to: 'ip-0x2e', entrance: 'Slide Up', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x1f', to: 'ip-0x2e', entrance: 'Slide Room Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x2e', to: 'ip-0x3e', entrance: 'Up Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x3e', to: 'ip-0x3f', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x3e', to: 'ip-0x4e', entrance: 'Up Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x3f', to: 'ip-0x4f', entrance: 'Up Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x4e', to: 'ip-0x4f', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x4e', to: 'ip-0x5e', entrance: 'Up Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x4f', to: 'ip-0x5f', entrance: 'Up Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x5e', to: 'ip-0x5f', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x5e', to: 'ip-0x6e', entrance: 'Up to Compass', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x5f', to: 'ip-0x9f', entrance: 'Return Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x6e', to: 'ip-0x7e', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x7e', to: 'ip-0x7f', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x7e', to: 'ip-0x8e', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x7f', to: 'ip-0x9f', entrance: 'South Return', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x8e', to: 'ip-0x9e', entrance: 'South to Entrance', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x9e', to: 'ip-0x9f', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x9e', to: 'ip-0xae', entrance: 'South Descent', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x9f', to: 'ip-0xaf', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xae', to: 'ip-0xaf', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xae', to: 'ip-0xbe', entrance: 'South to Switch', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xaf', to: 'ip-0xbf', entrance: 'South to Big Chest', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xbe', to: 'ip-0xbf', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xbe', to: 'ip-0xce', entrance: 'South Descent', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xbf', to: 'ip-0xbe', entrance: 'West Return', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xce', to: 'ip-0xde', entrance: 'South to Big Key', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0xce', to: 'ip-0x1e', entrance: 'Drop to B6', tags: ['transit:hole', 'dir:one-way', 'ctx:internal'] },
  { from: 'ip-0xde', to: 'ip-0xce', entrance: 'North Return', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'ip-0x9e', to: 'ip-0x8e', entrance: 'Big Key Door', tags: ['transit:walk', 'dir:two-way', 'ctx:internal', 'barrier:big-key'] },
  { from: 'ip-0x6e', to: 'ip-0x0e', entrance: 'Boss Door', tags: ['transit:walk', 'dir:two-way', 'ctx:boss', 'barrier:big-key'] },
  { from: 'ip-0x9e', to: 'dw-75', entrance: 'Palace Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
  { from: 'ip-0x5e', to: 'ip-0x4e', entrance: 'Bomb Floor Drop', tags: ['transit:hole', 'dir:one-way', 'ctx:internal'] },
  { from: 'ip-0x4f', to: 'ip-0x3f', entrance: 'Spike Drop', tags: ['transit:hole', 'dir:one-way', 'ctx:internal'] },
];
