import type { RegionConnection } from '../../../types';

export const DW_PALACE_OF_DARKNESS_CONNECTIONS: RegionConnection[] = [
  { from: 'overworld', to: 'pod-0x4a', entrance: 'Palace Entrance', tags: ['transit:door', 'dir:two-way', 'ctx:dungeon-enter'] },
  { from: 'pod-0x09', to: 'pod-0x4b', entrance: 'Dark Maze Stairs Up', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x09', to: 'pod-0x4a', entrance: 'Entrance Hall Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x09', to: 'pod-0x19', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x09', to: 'pod-0x0a', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x0a', to: 'pod-0x3a', entrance: 'Compass Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x0a', to: 'pod-0x1a', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x0a', to: 'pod-0x0b', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x0b', to: 'pod-0x6a', entrance: 'Boss Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:boss', 'barrier:big-key'] },
  { from: 'pod-0x0b', to: 'pod-0x1b', entrance: 'Map Room Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x19', to: 'pod-0x1a', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x1a', to: 'pod-0x6a', entrance: 'Boss Shortcut', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x1a', to: 'pod-0x2a', entrance: 'South to Hub', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x1a', to: 'pod-0x1b', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x1b', to: 'pod-0x2b', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x2a', to: 'pod-0x2b', entrance: 'Conveyor Bridge Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x2a', to: 'pod-0x3a', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x2b', to: 'pod-0x3b', entrance: 'Pit Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x2b', to: 'pod-0x0b', entrance: 'Turtle Drop', tags: ['transit:hole', 'dir:one-way', 'ctx:internal'] },
  { from: 'pod-0x3a', to: 'pod-0x4a', entrance: 'South to Entrance', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x3a', to: 'pod-0x3b', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x3b', to: 'pod-0x4b', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x4a', to: 'pod-0x5a', entrance: 'South to Bridge', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x4a', to: 'pod-0x4b', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x4b', to: 'pod-0x1a', entrance: 'Warps Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x5a', to: 'pod-0x0a', entrance: 'Return Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x5a', to: 'pod-0x6a', entrance: 'South to Boss', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'pod-0x4a', to: 'dw-4a', entrance: 'Palace Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
  { from: 'pod-0x6a', to: 'dw-4a', entrance: 'Boss Reward Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
];
