import type { RegionConnection } from '../../../types';

export const DW_TURTLE_ROCK_CONNECTIONS: RegionConnection[] = [
  { from: 'overworld', to: 'tr-0xd5', entrance: 'Main Entrance', tags: ['transit:door', 'dir:two-way', 'ctx:dungeon-enter', 'barrier:medallion'] },
  { from: 'overworld', to: 'tr-0xc5', entrance: 'Middle Entrance', tags: ['transit:door', 'dir:two-way', 'ctx:dungeon-enter'] },
  { from: 'overworld', to: 'tr-0xc7', entrance: 'East Entrance', tags: ['transit:door', 'dir:two-way', 'ctx:dungeon-enter'] },
  { from: 'overworld', to: 'tr-0xc4', entrance: 'West Entrance', tags: ['transit:door', 'dir:two-way', 'ctx:dungeon-enter'] },
  { from: 'tr-0x04', to: 'tr-0x14', entrance: 'Boss Return', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0x13', to: 'tr-0x14', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0x13', to: 'tr-0x23', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0x14', to: 'tr-0x15', entrance: 'East to Big Key', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0x14', to: 'tr-0x24', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0x15', to: 'tr-0x14', entrance: 'West Return', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0x23', to: 'tr-0x24', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0x24', to: 'tr-0x04', entrance: 'Boss Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:boss', 'barrier:big-key'] },
  { from: 'tr-0xa4', to: 'tr-0xb4', entrance: 'South to Maze', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xb4', to: 'tr-0xb5', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal', 'barrier:dark'] },
  { from: 'tr-0xb5', to: 'tr-0xb6', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xb5', to: 'tr-0xc5', entrance: 'South to Hub', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xb6', to: 'tr-0xb7', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xb6', to: 'tr-0xc6', entrance: 'South to Compass', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xb7', to: 'tr-0xc7', entrance: 'South Exit Stairs', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xc4', to: 'tr-0xc5', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xc5', to: 'tr-0xc6', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xc5', to: 'tr-0xd5', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xc6', to: 'tr-0xc7', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xc6', to: 'tr-0xd6', entrance: 'South Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xd5', to: 'tr-0xd6', entrance: 'East Passage', tags: ['transit:walk', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xc5', to: 'tr-0xa4', entrance: 'Crystaroller Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal'] },
  { from: 'tr-0xc5', to: 'tr-0x13', entrance: 'Deep Descent Stairs', tags: ['transit:stairs', 'dir:two-way', 'ctx:internal', 'barrier:small-key'] },
  { from: 'tr-0xd5', to: 'dw-47', entrance: 'Main Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
  { from: 'tr-0xc4', to: 'dw-47', entrance: 'West Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
  { from: 'tr-0xc5', to: 'dw-47', entrance: 'Middle Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
  { from: 'tr-0xc7', to: 'dw-47', entrance: 'East Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
  { from: 'tr-0x04', to: 'dw-47', entrance: 'Boss Reward Exit', tags: ['transit:door', 'dir:two-way', 'ctx:exit'] },
];
