export { Widget } from './Widget';
export { WidgetManager } from './WidgetManager';
export { WidgetSettings } from './sub-components/WidgetSettings';
export type { WidgetState, WidgetLayout, WidgetDefinition, SnapSide, WidgetMode, WidgetVisibility } from './types';
export { WIDGET_DEFINITIONS, TITLEBAR_HEIGHT } from './constants';
export { createDefaultLayout, getWidgetDefinition, createDefaultWidgetState } from './behavior/createWidgetState';
export { computeDockedStyles } from './behavior/computeDockedStyles';
export { loadLayoutLocal, saveLayoutLocal, loadLayoutForProfile, saveLayoutForProfile, updateWidget, getWidgetState } from './behavior/widgetStore';
export { useWidgetLayout } from './behavior/useWidgetLayout';
export { useWidgetDrag } from './behavior/useWidgetDrag';
export { useWidgetResize, getDockedResizeEdge } from './behavior/useWidgetResize';
import './widgets.css';
