/* @layer shared-game @kind data */
/**
 * Ported from Archipelago worlds/alttp/EntranceShuffle.py — default_connections
 * (vanilla overworld↔interior wiring, entrance shuffle off).
 */
import type { ApConnection } from './region.type';

const DEFAULT_CONNECTIONS: readonly ApConnection[] = [
  ['Waterfall of Wishing', 'Waterfall of Wishing'],
  ['Blinds Hideout', 'Blinds Hideout'],
  ['Dam', 'Dam'],
  ['Lumberjack House', 'Lumberjack House'],
  ['Hyrule Castle Secret Entrance Drop', 'Hyrule Castle Secret Entrance'],
  ['Hyrule Castle Secret Entrance Stairs', 'Hyrule Castle Secret Entrance'],
  ['Hyrule Castle Secret Entrance Exit', 'Hyrule Castle Courtyard'],
  ['Bonk Fairy (Light)', 'Bonk Fairy (Light)'],
  ['Lake Hylia Fairy', 'Lake Hylia Healer Fairy'],
  ['Lake Hylia Fortune Teller', 'Lake Hylia Fortune Teller'],
  ['Light Hype Fairy', 'Swamp Healer Fairy'],
  ['Desert Fairy', 'Desert Healer Fairy'],
  ['Kings Grave', 'Kings Grave'],
  ['Tavern North', 'Tavern'],
  ['Chicken House', 'Chicken House'],
  ['Aginahs Cave', 'Aginahs Cave'],
  ['Sahasrahlas Hut', 'Sahasrahlas Hut'],
  ['Cave Shop (Lake Hylia)', 'Cave Shop (Lake Hylia)'],
  ['Capacity Upgrade', 'Capacity Upgrade'],
  ['Kakariko Well Drop', 'Kakariko Well (top)'],
  ['Kakariko Well Cave', 'Kakariko Well (bottom)'],
  ['Kakariko Well Exit', 'Light World'],
  ['Blacksmiths Hut', 'Blacksmiths Hut'],
  ['Bat Cave Drop', 'Bat Cave (right)'],
  ['Bat Cave Cave', 'Bat Cave (left)'],
  ['Bat Cave Exit', 'Light World'],
  ['Sick Kids House', 'Sick Kids House'],
  ['Elder House (East)', 'Elder House'],
  ['Elder House (West)', 'Elder House'],
  ['Elder House Exit (East)', 'Light World'],
  ['Elder House Exit (West)', 'Light World'],
  ['North Fairy Cave Drop', 'North Fairy Cave'],
  ['North Fairy Cave', 'North Fairy Cave'],
  ['North Fairy Cave Exit', 'Light World'],
  ['Lost Woods Gamble', 'Lost Woods Gamble'],
  ['Fortune Teller (Light)', 'Fortune Teller (Light)'],
  ['Snitch Lady (East)', 'Snitch Lady (East)'],
  ['Snitch Lady (West)', 'Snitch Lady (West)'],
  ['Bush Covered House', 'Bush Covered House'],
  ['Tavern (Front)', 'Tavern (Front)'],
  ['Light World Bomb Hut', 'Light World Bomb Hut'],
  ['Kakariko Shop', 'Kakariko Shop'],
  ['Lost Woods Hideout Drop', 'Lost Woods Hideout (top)'],
  ['Lost Woods Hideout Stump', 'Lost Woods Hideout (bottom)'],
  ['Lost Woods Hideout Exit', 'Light World'],
  ['Lumberjack Tree Tree', 'Lumberjack Tree (top)'],
  ['Lumberjack Tree Cave', 'Lumberjack Tree (bottom)'],
  ['Lumberjack Tree Exit', 'Light World'],
  ['Cave 45', 'Cave 45'],
  ['Graveyard Cave', 'Graveyard Cave'],
  ['Checkerboard Cave', 'Checkerboard Cave'],
  ['Mini Moldorm Cave', 'Mini Moldorm Cave'],
  ['Long Fairy Cave', 'Long Fairy Cave'],
  ['Good Bee Cave', 'Good Bee Cave'],
  ['20 Rupee Cave', '20 Rupee Cave'],
  ['50 Rupee Cave', '50 Rupee Cave'],
  ['Ice Rod Cave', 'Ice Rod Cave'],
  ['Bonk Rock Cave', 'Bonk Rock Cave'],
  ['Library', 'Library'],
  ['Kakariko Gamble Game', 'Kakariko Gamble Game'],
  ['Potion Shop', 'Potion Shop'],
  ['Two Brothers House (East)', 'Two Brothers House'],
  ['Two Brothers House (West)', 'Two Brothers House'],
  ['Two Brothers House Exit (East)', 'Light World'],
  ['Two Brothers House Exit (West)', 'Maze Race Ledge'],
  ['Sanctuary', 'Sanctuary'],
  ['Sanctuary Grave', 'Sewer Drop'],
  ['Sanctuary Exit', 'Light World'],
  ['Old Man Cave (West)', 'Old Man Cave'],
  ['Old Man Cave (East)', 'Old Man Cave'],
  ['Old Man Cave Exit (West)', 'Light World'],
  ['Old Man Cave Exit (East)', 'Death Mountain'],
  ['Old Man House (Bottom)', 'Old Man House'],
  ['Old Man House Exit (Bottom)', 'Death Mountain'],
  ['Old Man House (Top)', 'Old Man House Back'],
  ['Old Man House Exit (Top)', 'Death Mountain'],
  ['Death Mountain Return Cave (East)', 'Death Mountain Return Cave'],
  ['Death Mountain Return Cave (West)', 'Death Mountain Return Cave'],
  ['Death Mountain Return Cave Exit (West)', 'Death Mountain Return Ledge'],
  ['Death Mountain Return Cave Exit (East)', 'Death Mountain'],
  ['Spectacle Rock Cave Peak', 'Spectacle Rock Cave (Peak)'],
  ['Spectacle Rock Cave (Bottom)', 'Spectacle Rock Cave (Bottom)'],
  ['Spectacle Rock Cave', 'Spectacle Rock Cave (Top)'],
  ['Spectacle Rock Cave Exit', 'Death Mountain'],
  ['Spectacle Rock Cave Exit (Top)', 'Death Mountain'],
  ['Spectacle Rock Cave Exit (Peak)', 'Death Mountain'],
  ['Paradox Cave (Bottom)', 'Paradox Cave Front'],
  ['Paradox Cave (Middle)', 'Paradox Cave'],
  ['Paradox Cave (Top)', 'Paradox Cave'],
  ['Paradox Cave Exit (Bottom)', 'East Death Mountain (Bottom)'],
  ['Paradox Cave Exit (Middle)', 'East Death Mountain (Bottom)'],
  ['Paradox Cave Exit (Top)', 'East Death Mountain (Top)'],
  ['Hookshot Fairy', 'Hookshot Fairy'],
  ['Fairy Ascension Cave (Bottom)', 'Fairy Ascension Cave (Bottom)'],
  ['Fairy Ascension Cave (Top)', 'Fairy Ascension Cave (Top)'],
  ['Fairy Ascension Cave Exit (Bottom)', 'Fairy Ascension Plateau'],
  ['Fairy Ascension Cave Exit (Top)', 'Fairy Ascension Ledge'],
  ['Spiral Cave', 'Spiral Cave (Top)'],
  ['Spiral Cave (Bottom)', 'Spiral Cave (Bottom)'],
  ['Spiral Cave Exit', 'East Death Mountain (Bottom)'],
  ['Spiral Cave Exit (Top)', 'Spiral Cave Ledge'],
  ['Pyramid Fairy', 'Pyramid Fairy'],
  ['East Dark World Hint', 'East Dark World Hint'],
  ['Palace of Darkness Hint', 'Palace of Darkness Hint'],
  ['Big Bomb Shop', 'Big Bomb Shop'],
  ['Dark Lake Hylia Shop', 'Dark Lake Hylia Shop'],
  ['Dark Lake Hylia Fairy', 'Dark Lake Hylia Healer Fairy'],
  ['Dark Lake Hylia Ledge Fairy', 'Dark Lake Hylia Ledge Healer Fairy'],
  ['Dark Lake Hylia Ledge Spike Cave', 'Dark Lake Hylia Ledge Spike Cave'],
  ['Dark Lake Hylia Ledge Hint', 'Dark Lake Hylia Ledge Hint'],
  ['Hype Cave', 'Hype Cave'],
  ['Bonk Fairy (Dark)', 'Bonk Fairy (Dark)'],
  ['Brewery', 'Brewery'],
  ['C-Shaped House', 'C-Shaped House'],
  ['Chest Game', 'Chest Game'],
  ['Dark World Hammer Peg Cave', 'Dark World Hammer Peg Cave'],
  ['Bumper Cave (Bottom)', 'Bumper Cave'],
  ['Bumper Cave (Top)', 'Bumper Cave'],
  ['Red Shield Shop', 'Red Shield Shop'],
  ['Dark Sanctuary Hint', 'Dark Sanctuary Hint'],
  ['Fortune Teller (Dark)', 'Fortune Teller (Dark)'],
  ['Village of Outcasts Shop', 'Village of Outcasts Shop'],
  ['Dark World Lumberjack Shop', 'Dark World Lumberjack Shop'],
  ['Dark World Potion Shop', 'Dark World Potion Shop'],
  ['Archery Game', 'Archery Game'],
  ['Bumper Cave Exit (Top)', 'Bumper Cave Ledge'],
  ['Bumper Cave Exit (Bottom)', 'West Dark World'],
  ['Mire Shed', 'Mire Shed'],
  ['Dark Desert Hint', 'Dark Desert Hint'],
  ['Dark Desert Fairy', 'Dark Desert Healer Fairy'],
  ['Spike Cave', 'Spike Cave'],
  ['Hookshot Cave', 'Hookshot Cave'],
  ['Superbunny Cave (Top)', 'Superbunny Cave (Top)'],
  ['Cave Shop (Dark Death Mountain)', 'Cave Shop (Dark Death Mountain)'],
  ['Dark Death Mountain Fairy', 'Dark Death Mountain Healer Fairy'],
  ['Superbunny Cave (Bottom)', 'Superbunny Cave (Bottom)'],
  ['Superbunny Cave Exit (Top)', 'Dark Death Mountain (Top)'],
  ['Superbunny Cave Exit (Bottom)', 'Dark Death Mountain (East Bottom)'],
  ['Hookshot Cave Exit (South)', 'Dark Death Mountain (Top)'],
  ['Hookshot Cave Exit (North)', 'Death Mountain Floating Island (Dark World)'],
  ['Hookshot Cave Back Entrance', 'Hookshot Cave (Upper)'],
  ['Mimic Cave', 'Mimic Cave'],
  ['Pyramid Hole', 'Pyramid'],
  ['Pyramid Exit', 'Pyramid Ledge'],
  ['Pyramid Entrance', 'Bottom of Pyramid'],
];

export { DEFAULT_CONNECTIONS };
