/* @layer shared-game @kind data */
/**
 * Dungeon interior regions (python create_dungeon_region calls).
 * Ported 1:1 from tests/fixtures/ap-source/Regions.py (create_regions, open
 * mode). Names are the AP originals — this is transcribed game data.
 */
import type { ApRegionDef } from './region.type';

const DUNGEON_REGIONS: readonly ApRegionDef[] = [
  { name: 'Desert Palace Main (Outer)', type: 'dungeon', locations: ['Desert Palace - Big Chest', 'Desert Palace - Torch', 'Desert Palace - Map Chest'], exits: ['Desert Palace Pots (Outer)', 'Desert Palace Exit (West)', 'Desert Palace Exit (East)', 'Desert Palace East Wing'] },
  { name: 'Desert Palace Main (Inner)', type: 'dungeon', locations: [], exits: ['Desert Palace Exit (South)', 'Desert Palace Pots (Inner)'] },
  { name: 'Desert Palace East', type: 'dungeon', locations: ['Desert Palace - Compass Chest', 'Desert Palace - Big Key Chest'], exits: [] },
  { name: 'Desert Palace North', type: 'dungeon', locations: ['Desert Palace - Desert Tiles 1 Pot Key', 'Desert Palace - Beamos Hall Pot Key', 'Desert Palace - Desert Tiles 2 Pot Key', 'Desert Palace - Boss', 'Desert Palace - Prize'], exits: ['Desert Palace Exit (North)'] },
  { name: 'Eastern Palace', type: 'dungeon', locations: ['Eastern Palace - Compass Chest', 'Eastern Palace - Big Chest', 'Eastern Palace - Cannonball Chest', 'Eastern Palace - Dark Square Pot Key', 'Eastern Palace - Dark Eyegore Key Drop', 'Eastern Palace - Big Key Chest', 'Eastern Palace - Map Chest', 'Eastern Palace - Boss', 'Eastern Palace - Prize'], exits: ['Eastern Palace Exit'] },
  { name: 'Hyrule Castle', type: 'dungeon', locations: ['Hyrule Castle - Boomerang Chest', 'Hyrule Castle - Map Chest', 'Hyrule Castle - Zelda\'s Chest', 'Hyrule Castle - Map Guard Key Drop', 'Hyrule Castle - Boomerang Guard Key Drop', 'Hyrule Castle - Big Key Drop'], exits: ['Hyrule Castle Exit (East)', 'Hyrule Castle Exit (West)', 'Hyrule Castle Exit (South)', 'Throne Room'] },
  { name: 'Sewer Drop', type: 'dungeon', locations: [], exits: ['Sewer Drop'] },
  { name: 'Sewers (Dark)', type: 'dungeon', locations: ['Sewers - Dark Cross', 'Sewers - Key Rat Key Drop'], exits: ['Sewers Door'] },
  { name: 'Sewers', type: 'dungeon', locations: [], exits: ['Sanctuary Push Door', 'Sewers Back Door', 'Sewers Secret Room'] },
  { name: 'Sewers Secret Room', type: 'dungeon', locations: ['Sewers - Secret Room - Left', 'Sewers - Secret Room - Middle', 'Sewers - Secret Room - Right'], exits: [] },
  { name: 'Sanctuary', type: 'dungeon', locations: ['Sanctuary'], exits: ['Sanctuary Exit'] },
  { name: 'Agahnims Tower', type: 'dungeon', locations: ['Castle Tower - Room 03', 'Castle Tower - Dark Maze', 'Castle Tower - Dark Archer Key Drop', 'Castle Tower - Circle of Pots Key Drop'], exits: ['Agahnim 1', 'Agahnims Tower Exit'] },
  { name: 'Agahnim 1', type: 'dungeon', locations: ['Agahnim 1'], exits: [] },
  { name: 'Tower of Hera (Bottom)', type: 'dungeon', locations: ['Tower of Hera - Basement Cage', 'Tower of Hera - Map Chest'], exits: ['Tower of Hera Small Key Door', 'Tower of Hera Big Key Door', 'Tower of Hera Exit'] },
  { name: 'Tower of Hera (Basement)', type: 'dungeon', locations: ['Tower of Hera - Big Key Chest'], exits: [] },
  { name: 'Tower of Hera (Top)', type: 'dungeon', locations: ['Tower of Hera - Compass Chest', 'Tower of Hera - Big Chest', 'Tower of Hera - Boss', 'Tower of Hera - Prize'], exits: [] },
  { name: 'Swamp Palace (Entrance)', type: 'dungeon', locations: [], exits: ['Swamp Palace Moat', 'Swamp Palace Exit'] },
  { name: 'Swamp Palace (First Room)', type: 'dungeon', locations: ['Swamp Palace - Entrance'], exits: ['Swamp Palace Small Key Door'] },
  { name: 'Swamp Palace (Starting Area)', type: 'dungeon', locations: ['Swamp Palace - Map Chest', 'Swamp Palace - Pot Row Pot Key', 'Swamp Palace - Trench 1 Pot Key'], exits: ['Swamp Palace (Center)'] },
  { name: 'Swamp Palace (Center)', type: 'dungeon', locations: ['Swamp Palace - Big Chest', 'Swamp Palace - Compass Chest', 'Swamp Palace - Hookshot Pot Key', 'Swamp Palace - Trench 2 Pot Key'], exits: ['Swamp Palace (North)', 'Swamp Palace (West)'] },
  { name: 'Swamp Palace (West)', type: 'dungeon', locations: ['Swamp Palace - Big Key Chest', 'Swamp Palace - West Chest'], exits: [] },
  { name: 'Swamp Palace (North)', type: 'dungeon', locations: ['Swamp Palace - Flooded Room - Left', 'Swamp Palace - Flooded Room - Right', 'Swamp Palace - Waterway Pot Key', 'Swamp Palace - Waterfall Room', 'Swamp Palace - Boss', 'Swamp Palace - Prize'], exits: [] },
  { name: 'Thieves Town (Entrance)', type: 'dungeon', locations: ['Thieves\' Town - Big Key Chest', 'Thieves\' Town - Map Chest', 'Thieves\' Town - Compass Chest', 'Thieves\' Town - Ambush Chest'], exits: ['Thieves Town Big Key Door', 'Thieves Town Exit'] },
  { name: 'Thieves Town (Deep)', type: 'dungeon', locations: ['Thieves\' Town - Attic', 'Thieves\' Town - Big Chest', 'Thieves\' Town - Hallway Pot Key', 'Thieves\' Town - Spike Switch Pot Key', 'Thieves\' Town - Blind\'s Cell'], exits: ['Blind Fight'] },
  { name: 'Blind Fight', type: 'dungeon', locations: ['Thieves\' Town - Boss', 'Thieves\' Town - Prize'], exits: [] },
  { name: 'Skull Woods First Section', type: 'dungeon', locations: ['Skull Woods - Map Chest'], exits: ['Skull Woods First Section Exit', 'Skull Woods First Section Bomb Jump', 'Skull Woods First Section South Door', 'Skull Woods First Section West Door'] },
  { name: 'Skull Woods First Section (Right)', type: 'dungeon', locations: ['Skull Woods - Pinball Room'], exits: ['Skull Woods First Section (Right) North Door'] },
  { name: 'Skull Woods First Section (Left)', type: 'dungeon', locations: ['Skull Woods - Compass Chest', 'Skull Woods - Pot Prison'], exits: ['Skull Woods First Section (Left) Door to Exit', 'Skull Woods First Section (Left) Door to Right'] },
  { name: 'Skull Woods First Section (Top)', type: 'dungeon', locations: ['Skull Woods - Big Chest'], exits: ['Skull Woods First Section (Top) One-Way Path'] },
  { name: 'Skull Woods Second Section (Drop)', type: 'dungeon', locations: [], exits: ['Skull Woods Second Section (Drop)'] },
  { name: 'Skull Woods Second Section', type: 'dungeon', locations: ['Skull Woods - Big Key Chest', 'Skull Woods - West Lobby Pot Key'], exits: ['Skull Woods Second Section Exit (East)', 'Skull Woods Second Section Exit (West)'] },
  { name: 'Skull Woods Final Section (Entrance)', type: 'dungeon', locations: ['Skull Woods - Bridge Room'], exits: ['Skull Woods Torch Room', 'Skull Woods Final Section Exit'] },
  { name: 'Skull Woods Final Section (Mothula)', type: 'dungeon', locations: ['Skull Woods - Spike Corner Key Drop', 'Skull Woods - Boss', 'Skull Woods - Prize'], exits: [] },
  { name: 'Ice Palace (Entrance)', type: 'dungeon', locations: ['Ice Palace - Jelly Key Drop', 'Ice Palace - Compass Chest'], exits: ['Ice Palace (Second Section)', 'Ice Palace Exit'] },
  { name: 'Ice Palace (Second Section)', type: 'dungeon', locations: ['Ice Palace - Conveyor Key Drop'], exits: ['Ice Palace (Main)'] },
  { name: 'Ice Palace (Main)', type: 'dungeon', locations: ['Ice Palace - Freezor Chest', 'Ice Palace - Many Pots Pot Key', 'Ice Palace - Big Chest', 'Ice Palace - Iced T Room'], exits: ['Ice Palace (East)', 'Ice Palace (Kholdstare)'] },
  { name: 'Ice Palace (East)', type: 'dungeon', locations: ['Ice Palace - Spike Room'], exits: ['Ice Palace (East Top)'] },
  { name: 'Ice Palace (East Top)', type: 'dungeon', locations: ['Ice Palace - Big Key Chest', 'Ice Palace - Map Chest', 'Ice Palace - Hammer Block Key Drop'], exits: [] },
  { name: 'Ice Palace (Kholdstare)', type: 'dungeon', locations: ['Ice Palace - Boss', 'Ice Palace - Prize'], exits: [] },
  { name: 'Misery Mire (Entrance)', type: 'dungeon', locations: [], exits: ['Misery Mire Entrance Gap', 'Misery Mire Exit'] },
  { name: 'Misery Mire (Main)', type: 'dungeon', locations: ['Misery Mire - Big Chest', 'Misery Mire - Map Chest', 'Misery Mire - Main Lobby', 'Misery Mire - Bridge Chest', 'Misery Mire - Spike Chest', 'Misery Mire - Spikes Pot Key', 'Misery Mire - Fishbone Pot Key', 'Misery Mire - Conveyor Crystal Key Drop'], exits: ['Misery Mire (West)', 'Misery Mire Big Key Door'] },
  { name: 'Misery Mire (West)', type: 'dungeon', locations: ['Misery Mire - Compass Chest', 'Misery Mire - Big Key Chest'], exits: [] },
  { name: 'Misery Mire (Final Area)', type: 'dungeon', locations: [], exits: ['Misery Mire (Vitreous)'] },
  { name: 'Misery Mire (Vitreous)', type: 'dungeon', locations: ['Misery Mire - Boss', 'Misery Mire - Prize'], exits: [] },
  { name: 'Turtle Rock (Entrance)', type: 'dungeon', locations: [], exits: ['Turtle Rock Entrance Gap', 'Turtle Rock Exit (Front)'] },
  { name: 'Turtle Rock (First Section)', type: 'dungeon', locations: ['Turtle Rock - Compass Chest', 'Turtle Rock - Roller Room - Left', 'Turtle Rock - Roller Room - Right'], exits: ['Turtle Rock Entrance to Pokey Room', 'Turtle Rock Entrance Gap Reverse'] },
  { name: 'Turtle Rock (Pokey Room)', type: 'dungeon', locations: ['Turtle Rock - Pokey 1 Key Drop'], exits: ['Turtle Rock (Pokey Room) (North)', 'Turtle Rock (Pokey Room) (South)'] },
  { name: 'Turtle Rock (Chain Chomp Room)', type: 'dungeon', locations: ['Turtle Rock - Chain Chomps'], exits: ['Turtle Rock (Chain Chomp Room) (North)', 'Turtle Rock (Chain Chomp Room) (South)'] },
  { name: 'Turtle Rock (Second Section)', type: 'dungeon', locations: ['Turtle Rock - Big Key Chest', 'Turtle Rock - Pokey 2 Key Drop'], exits: ['Turtle Rock Chain Chomp Staircase', 'Turtle Rock Big Key Door', 'Turtle Rock Second Section Bomb Wall'] },
  { name: 'Turtle Rock (Second Section Bomb Wall)', type: 'dungeon', locations: [], exits: ['Turtle Rock Ledge Exit (West)', 'Turtle Rock Second Section from Bomb Wall'] },
  { name: 'Turtle Rock (Big Chest)', type: 'dungeon', locations: ['Turtle Rock - Big Chest'], exits: ['Turtle Rock (Big Chest) (North)', 'Turtle Rock Ledge Exit (East)'] },
  { name: 'Turtle Rock (Crystaroller Room)', type: 'dungeon', locations: ['Turtle Rock - Crystaroller Room'], exits: ['Turtle Rock Dark Room Staircase', 'Turtle Rock Big Key Door Reverse'] },
  { name: 'Turtle Rock (Dark Room)', type: 'dungeon', locations: [], exits: ['Turtle Rock (Dark Room) (North)', 'Turtle Rock (Dark Room) (South)'] },
  { name: 'Turtle Rock (Eye Bridge Bomb Wall)', type: 'dungeon', locations: [], exits: ['Turtle Rock Isolated Ledge Exit', 'Turtle Rock Eye Bridge from Bomb Wall'] },
  { name: 'Turtle Rock (Eye Bridge)', type: 'dungeon', locations: ['Turtle Rock - Eye Bridge - Bottom Left', 'Turtle Rock - Eye Bridge - Bottom Right', 'Turtle Rock - Eye Bridge - Top Left', 'Turtle Rock - Eye Bridge - Top Right'], exits: ['Turtle Rock Dark Room (South)', 'Turtle Rock (Trinexx)', 'Turtle Rock Eye Bridge Bomb Wall'] },
  { name: 'Turtle Rock (Trinexx)', type: 'dungeon', locations: ['Turtle Rock - Boss', 'Turtle Rock - Prize'], exits: [] },
  { name: 'Palace of Darkness (Entrance)', type: 'dungeon', locations: ['Palace of Darkness - Shooter Room'], exits: ['Palace of Darkness Bridge Room', 'Palace of Darkness Bonk Wall', 'Palace of Darkness Exit'] },
  { name: 'Palace of Darkness (Center)', type: 'dungeon', locations: ['Palace of Darkness - The Arena - Bridge', 'Palace of Darkness - Stalfos Basement'], exits: ['Palace of Darkness Big Key Chest Staircase', 'Palace of Darkness (North)', 'Palace of Darkness Big Key Door'] },
  { name: 'Palace of Darkness (Big Key Chest)', type: 'dungeon', locations: ['Palace of Darkness - Big Key Chest'], exits: [] },
  { name: 'Palace of Darkness (Bonk Section)', type: 'dungeon', locations: ['Palace of Darkness - The Arena - Ledge', 'Palace of Darkness - Map Chest'], exits: ['Palace of Darkness Hammer Peg Drop'] },
  { name: 'Palace of Darkness (North)', type: 'dungeon', locations: ['Palace of Darkness - Compass Chest', 'Palace of Darkness - Dark Basement - Left', 'Palace of Darkness - Dark Basement - Right'], exits: ['Palace of Darkness Spike Statue Room Door', 'Palace of Darkness Maze Door'] },
  { name: 'Palace of Darkness (Maze)', type: 'dungeon', locations: ['Palace of Darkness - Dark Maze - Top', 'Palace of Darkness - Dark Maze - Bottom', 'Palace of Darkness - Big Chest'], exits: [] },
  { name: 'Palace of Darkness (Harmless Hellway)', type: 'dungeon', locations: ['Palace of Darkness - Harmless Hellway'], exits: [] },
  { name: 'Palace of Darkness (Final Section)', type: 'dungeon', locations: ['Palace of Darkness - Boss', 'Palace of Darkness - Prize'], exits: [] },
  { name: 'Ganons Tower (Entrance)', type: 'dungeon', locations: ['Ganons Tower - Bob\'s Torch', 'Ganons Tower - Hope Room - Left', 'Ganons Tower - Hope Room - Right', 'Ganons Tower - Conveyor Cross Pot Key'], exits: ['Ganons Tower (Tile Room)', 'Ganons Tower (Hookshot Room)', 'Ganons Tower Big Key Door', 'Ganons Tower Exit'] },
  { name: 'Ganons Tower (Tile Room)', type: 'dungeon', locations: ['Ganons Tower - Tile Room'], exits: ['Ganons Tower (Tile Room) Key Door'] },
  { name: 'Ganons Tower (Compass Room)', type: 'dungeon', locations: ['Ganons Tower - Compass Room - Top Left', 'Ganons Tower - Compass Room - Top Right', 'Ganons Tower - Compass Room - Bottom Left', 'Ganons Tower - Compass Room - Bottom Right', 'Ganons Tower - Conveyor Star Pits Pot Key'], exits: ['Ganons Tower (Bottom) (East)'] },
  { name: 'Ganons Tower (Hookshot Room)', type: 'dungeon', locations: ['Ganons Tower - DMs Room - Top Left', 'Ganons Tower - DMs Room - Top Right', 'Ganons Tower - DMs Room - Bottom Left', 'Ganons Tower - DMs Room - Bottom Right', 'Ganons Tower - Double Switch Pot Key'], exits: ['Ganons Tower (Map Room)', 'Ganons Tower (Double Switch Room)'] },
  { name: 'Ganons Tower (Map Room)', type: 'dungeon', locations: ['Ganons Tower - Map Chest'], exits: [] },
  { name: 'Ganons Tower (Firesnake Room)', type: 'dungeon', locations: ['Ganons Tower - Firesnake Room'], exits: ['Ganons Tower (Firesnake Room)'] },
  { name: 'Ganons Tower (Teleport Room)', type: 'dungeon', locations: ['Ganons Tower - Randomizer Room - Top Left', 'Ganons Tower - Randomizer Room - Top Right', 'Ganons Tower - Randomizer Room - Bottom Left', 'Ganons Tower - Randomizer Room - Bottom Right'], exits: ['Ganons Tower (Bottom) (West)'] },
  { name: 'Ganons Tower (Bottom)', type: 'dungeon', locations: ['Ganons Tower - Bob\'s Chest', 'Ganons Tower - Big Chest', 'Ganons Tower - Big Key Room - Left', 'Ganons Tower - Big Key Room - Right', 'Ganons Tower - Big Key Chest'], exits: [] },
  { name: 'Ganons Tower (Top)', type: 'dungeon', locations: [], exits: ['Ganons Tower Torch Rooms'] },
  { name: 'Ganons Tower (Before Moldorm)', type: 'dungeon', locations: ['Ganons Tower - Mini Helmasaur Room - Left', 'Ganons Tower - Mini Helmasaur Room - Right', 'Ganons Tower - Pre-Moldorm Chest', 'Ganons Tower - Mini Helmasaur Key Drop'], exits: ['Ganons Tower Moldorm Door'] },
  { name: 'Ganons Tower (Moldorm)', type: 'dungeon', locations: [], exits: ['Ganons Tower Moldorm Gap'] },
  { name: 'Agahnim 2', type: 'dungeon', locations: ['Ganons Tower - Validation Chest', 'Agahnim 2'], exits: [] },
];

export { DUNGEON_REGIONS };
