/* @layer shared-game @kind data */
/**
 * Cave and house interior regions (python create_cave_region calls).
 * Ported 1:1 from Archipelago worlds/alttp/Regions.py (create_regions, open
 * mode). Names are the AP originals, since this is transcribed game data.
 */
import { POND_PRIZE_LOCATIONS } from './pond/pond-locations.data';
import type { ApRegionDef } from './region.type';

const CAVE_REGIONS: readonly ApRegionDef[] = [
  { name: 'Blinds Hideout', type: 'cave', locations: ['Blind\'s Hideout - Top', 'Blind\'s Hideout - Left', 'Blind\'s Hideout - Right', 'Blind\'s Hideout - Far Left', 'Blind\'s Hideout - Far Right'], exits: [] },
  { name: 'Hyrule Castle Secret Entrance', type: 'cave', locations: ['Link\'s Uncle', 'Secret Passage'], exits: ['Hyrule Castle Secret Entrance Exit'] },
  { name: 'Waterfall of Wishing', type: 'cave', locations: ['Waterfall Fairy - Left', 'Waterfall Fairy - Right'], exits: [] },
  { name: 'Kings Grave', type: 'cave', locations: ['King\'s Tomb'], exits: [] },
  { name: 'North Fairy Cave', type: 'cave', locations: [], exits: ['North Fairy Cave Exit'] },
  { name: 'Dam', type: 'cave', locations: ['Floodgate', 'Floodgate Chest'], exits: [] },
  { name: 'Links House', type: 'cave', locations: ['Link\'s House'], exits: ['Links House Exit'] },
  { name: 'Chris Houlihan Room', type: 'cave', locations: [], exits: ['Chris Houlihan Room Exit'] },
  { name: 'Tavern', type: 'cave', locations: ['Kakariko Tavern'], exits: [] },
  { name: 'Elder House', type: 'cave', locations: [], exits: ['Elder House Exit (East)', 'Elder House Exit (West)'] },
  { name: 'Snitch Lady (East)', type: 'cave', locations: [], exits: [] },
  { name: 'Snitch Lady (West)', type: 'cave', locations: [], exits: [] },
  { name: 'Bush Covered House', type: 'cave', locations: [], exits: [] },
  { name: 'Tavern (Front)', type: 'cave', locations: [], exits: [] },
  { name: 'Light World Bomb Hut', type: 'cave', locations: [], exits: [] },
  { name: 'Kakariko Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Fortune Teller (Light)', type: 'cave', locations: [], exits: [] },
  { name: 'Lake Hylia Fortune Teller', type: 'cave', locations: [], exits: [] },
  { name: 'Lumberjack House', type: 'cave', locations: [], exits: [] },
  { name: 'Bonk Fairy (Light)', type: 'cave', locations: [], exits: [] },
  { name: 'Bonk Fairy (Dark)', type: 'cave', locations: [], exits: [] },
  { name: 'Lake Hylia Healer Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Swamp Healer Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Desert Healer Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Lake Hylia Healer Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Lake Hylia Ledge Healer Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Desert Healer Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Death Mountain Healer Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Chicken House', type: 'cave', locations: ['Chicken House'], exits: [] },
  { name: 'Aginahs Cave', type: 'cave', locations: ['Aginah\'s Cave'], exits: [] },
  { name: 'Sahasrahlas Hut', type: 'cave', locations: ['Sahasrahla\'s Hut - Left', 'Sahasrahla\'s Hut - Middle', 'Sahasrahla\'s Hut - Right', 'Sahasrahla'], exits: [] },
  { name: 'Kakariko Well (top)', type: 'cave', locations: ['Kakariko Well - Top', 'Kakariko Well - Left', 'Kakariko Well - Middle', 'Kakariko Well - Right', 'Kakariko Well - Bottom'], exits: ['Kakariko Well (top to bottom)'] },
  { name: 'Kakariko Well (bottom)', type: 'cave', locations: [], exits: ['Kakariko Well Exit'] },
  { name: 'Blacksmiths Hut', type: 'cave', locations: ['Blacksmith', 'Missing Smith'], exits: [] },
  { name: 'Bat Cave (right)', type: 'cave', locations: ['Magic Bat'], exits: ['Bat Cave Door'] },
  { name: 'Bat Cave (left)', type: 'cave', locations: [], exits: ['Bat Cave Exit'] },
  { name: 'Sick Kids House', type: 'cave', locations: ['Sick Kid'], exits: [] },
  { name: 'Lost Woods Hideout (top)', type: 'cave', locations: ['Lost Woods Hideout'], exits: ['Lost Woods Hideout (top to bottom)'] },
  { name: 'Lost Woods Hideout (bottom)', type: 'cave', locations: [], exits: ['Lost Woods Hideout Exit'] },
  { name: 'Lumberjack Tree (top)', type: 'cave', locations: ['Lumberjack Tree'], exits: ['Lumberjack Tree (top to bottom)'] },
  { name: 'Lumberjack Tree (bottom)', type: 'cave', locations: [], exits: ['Lumberjack Tree Exit'] },
  { name: 'Cave 45', type: 'cave', locations: ['Cave 45'], exits: [] },
  { name: 'Graveyard Cave', type: 'cave', locations: ['Graveyard Cave'], exits: [] },
  { name: 'Checkerboard Cave', type: 'cave', locations: ['Checkerboard Cave'], exits: [] },
  { name: 'Long Fairy Cave', type: 'cave', locations: [], exits: [] },
  { name: 'Mini Moldorm Cave', type: 'cave', locations: ['Mini Moldorm Cave - Far Left', 'Mini Moldorm Cave - Left', 'Mini Moldorm Cave - Right', 'Mini Moldorm Cave - Far Right', 'Mini Moldorm Cave - Generous Guy'], exits: [] },
  { name: 'Ice Rod Cave', type: 'cave', locations: ['Ice Rod Cave'], exits: [] },
  { name: 'Good Bee Cave', type: 'cave', locations: [], exits: [] },
  { name: '20 Rupee Cave', type: 'cave', locations: [], exits: [] },
  { name: 'Cave Shop (Lake Hylia)', type: 'cave', locations: [], exits: [] },
  { name: 'Cave Shop (Dark Death Mountain)', type: 'cave', locations: [], exits: [] },
  { name: 'Bonk Rock Cave', type: 'cave', locations: ['Bonk Rock Cave'], exits: [] },
  { name: 'Library', type: 'cave', locations: ['Library'], exits: [] },
  { name: 'Kakariko Gamble Game', type: 'cave', locations: [], exits: [] },
  { name: 'Potion Shop', type: 'cave', locations: ['Potion Shop'], exits: [] },
  {
    name: 'Capacity Upgrade',
    type: 'cave',
    // The pond's prize slots past the reference's two exist only while a
    // non-legacy pond mode carries that many (pond/pond-spots.ts).
    locations: ['Capacity Upgrade Shop', ...POND_PRIZE_LOCATIONS],
    exits: [],
  },
  { name: 'Two Brothers House', type: 'cave', locations: [], exits: ['Two Brothers House Exit (East)', 'Two Brothers House Exit (West)'] },
  { name: '50 Rupee Cave', type: 'cave', locations: [], exits: [] },
  { name: 'Lost Woods Gamble', type: 'cave', locations: [], exits: [] },
  { name: 'Old Man Cave', type: 'cave', locations: ['Old Man'], exits: ['Old Man Cave Exit (East)', 'Old Man Cave Exit (West)'] },
  { name: 'Old Man House', type: 'cave', locations: [], exits: ['Old Man House Exit (Bottom)', 'Old Man House Front to Back'] },
  { name: 'Old Man House Back', type: 'cave', locations: [], exits: ['Old Man House Exit (Top)', 'Old Man House Back to Front'] },
  { name: 'Death Mountain Return Cave', type: 'cave', locations: [], exits: ['Death Mountain Return Cave Exit (West)', 'Death Mountain Return Cave Exit (East)'] },
  { name: 'Spectacle Rock Cave (Top)', type: 'cave', locations: ['Spectacle Rock Cave'], exits: ['Spectacle Rock Cave Drop', 'Spectacle Rock Cave Exit (Top)'] },
  { name: 'Spectacle Rock Cave (Bottom)', type: 'cave', locations: [], exits: ['Spectacle Rock Cave Exit'] },
  { name: 'Spectacle Rock Cave (Peak)', type: 'cave', locations: [], exits: ['Spectacle Rock Cave Peak Drop', 'Spectacle Rock Cave Exit (Peak)'] },
  { name: 'Hookshot Fairy', type: 'cave', locations: [], exits: [] },
  { name: 'Paradox Cave Front', type: 'cave', locations: [], exits: ['Paradox Cave Push Block Reverse', 'Paradox Cave Exit (Bottom)', 'Light World Death Mountain Shop'] },
  { name: 'Paradox Cave Chest Area', type: 'cave', locations: ['Paradox Cave Lower - Far Left', 'Paradox Cave Lower - Left', 'Paradox Cave Lower - Right', 'Paradox Cave Lower - Far Right', 'Paradox Cave Lower - Middle', 'Paradox Cave Upper - Left', 'Paradox Cave Upper - Right'], exits: ['Paradox Cave Push Block', 'Paradox Cave Bomb Jump'] },
  { name: 'Paradox Cave', type: 'cave', locations: [], exits: ['Paradox Cave Exit (Middle)', 'Paradox Cave Exit (Top)', 'Paradox Cave Drop'] },
  { name: 'Light World Death Mountain Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Spiral Cave (Top)', type: 'cave', locations: ['Spiral Cave'], exits: ['Spiral Cave (top to bottom)', 'Spiral Cave Exit (Top)'] },
  { name: 'Spiral Cave (Bottom)', type: 'cave', locations: [], exits: ['Spiral Cave Exit'] },
  { name: 'Fairy Ascension Cave (Bottom)', type: 'cave', locations: [], exits: ['Fairy Ascension Cave Climb', 'Fairy Ascension Cave Exit (Bottom)'] },
  { name: 'Fairy Ascension Cave (Drop)', type: 'cave', locations: [], exits: ['Fairy Ascension Cave Pots'] },
  { name: 'Fairy Ascension Cave (Top)', type: 'cave', locations: [], exits: ['Fairy Ascension Cave Exit (Top)', 'Fairy Ascension Cave Drop'] },
  { name: 'Palace of Darkness Hint', type: 'cave', locations: [], exits: [] },
  { name: 'East Dark World Hint', type: 'cave', locations: [], exits: [] },
  { name: 'Big Bomb Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Archery Game', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Lake Hylia Ledge Hint', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Lake Hylia Ledge Spike Cave', type: 'cave', locations: [], exits: [] },
  { name: 'Hype Cave', type: 'cave', locations: ['Hype Cave - Top', 'Hype Cave - Middle Right', 'Hype Cave - Middle Left', 'Hype Cave - Bottom', 'Hype Cave - Generous Guy'], exits: [] },
  { name: 'Fortune Teller (Dark)', type: 'cave', locations: [], exits: [] },
  { name: 'Village of Outcasts Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Lake Hylia Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Dark World Lumberjack Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Dark World Potion Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Dark World Hammer Peg Cave', type: 'cave', locations: ['Peg Cave'], exits: [] },
  { name: 'Pyramid Fairy', type: 'cave', locations: ['Pyramid Fairy - Left', 'Pyramid Fairy - Right'], exits: [] },
  { name: 'Brewery', type: 'cave', locations: ['Brewery'], exits: [] },
  { name: 'C-Shaped House', type: 'cave', locations: ['C-Shaped House'], exits: [] },
  { name: 'Chest Game', type: 'cave', locations: ['Chest Game'], exits: [] },
  { name: 'Red Shield Shop', type: 'cave', locations: [], exits: [] },
  { name: 'Dark Sanctuary Hint', type: 'cave', locations: [], exits: [] },
  { name: 'Bumper Cave', type: 'cave', locations: [], exits: ['Bumper Cave Exit (Bottom)', 'Bumper Cave Exit (Top)'] },
  { name: 'Mire Shed', type: 'cave', locations: ['Mire Shed - Left', 'Mire Shed - Right'], exits: [] },
  { name: 'Dark Desert Hint', type: 'cave', locations: [], exits: [] },
  { name: 'Superbunny Cave (Top)', type: 'cave', locations: ['Superbunny Cave - Top', 'Superbunny Cave - Bottom'], exits: ['Superbunny Cave Exit (Top)'] },
  { name: 'Superbunny Cave (Bottom)', type: 'cave', locations: [], exits: ['Superbunny Cave Climb', 'Superbunny Cave Exit (Bottom)'] },
  { name: 'Spike Cave', type: 'cave', locations: ['Spike Cave'], exits: [] },
  { name: 'Hookshot Cave', type: 'cave', locations: ['Hookshot Cave - Top Right', 'Hookshot Cave - Top Left', 'Hookshot Cave - Bottom Right', 'Hookshot Cave - Bottom Left'], exits: ['Hookshot Cave Exit (South)', 'Hookshot Cave Bomb Wall (South)'] },
  { name: 'Hookshot Cave (Upper)', type: 'cave', locations: [], exits: ['Hookshot Cave Exit (North)', 'Hookshot Cave Bomb Wall (North)'] },
  { name: 'Mimic Cave', type: 'cave', locations: ['Mimic Cave'], exits: [] },
  { name: 'Pyramid', type: 'cave', locations: ['Ganon'], exits: ['Ganon Drop'] },
  { name: 'Bottom of Pyramid', type: 'cave', locations: [], exits: ['Pyramid Exit'] },
];

export { CAVE_REGIONS };
