/* @layer renderer-components @kind style */
import type React from 'react';

const S: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: '#111118',
    zIndex: 9999,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    fontFamily: "'JetBrains Mono', monospace",
    // @ts-expect-error Electron-specific CSS property
    WebkitAppRegion: 'no-drag',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    padding: '8px 20px',
    borderBottom: '2px solid #444',
    flexShrink: 0,
    background: '#0d0d12',
  },
  modeToggle: {
    display: 'flex',
    gap: 0,
    borderRadius: 6,
    overflow: 'hidden',
    border: '2px solid rgba(100,160,255,0.3)',
  },
  modeBtn: {
    padding: '5px 16px',
    background: 'rgba(255,255,255,0.03)',
    border: 'none',
    color: '#888',
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.15s',
  },
  modeBtnActive: {
    background: 'rgba(100,160,255,0.2)',
    color: '#b8d4ff',
  },
  modeHint: {
    fontSize: 11,
    color: '#666',
    fontStyle: 'italic',
  },
  closeBtn: {
    padding: '3px 8px',
    background: 'none',
    border: '1px solid #555',
    borderRadius: 4,
    color: '#ccc',
    fontSize: 14,
    cursor: 'pointer',
    marginLeft: 'auto',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '8px 20px',
    borderBottom: '1px solid #333',
    flexShrink: 0,
    flexWrap: 'wrap',
  },
  tabGroup: {
    display: 'flex',
    gap: 0,
    borderRadius: 4,
    overflow: 'hidden',
    border: '1px solid rgba(255,255,255,0.12)',
  },
  catTab: {
    padding: '3px 10px',
    background: 'rgba(255,255,255,0.04)',
    border: 'none',
    color: '#999',
    fontSize: 11,
    cursor: 'pointer',
    fontFamily: 'inherit',
    transition: 'all 0.1s',
  },
  catTabActive: {
    background: 'rgba(100,160,255,0.2)',
    color: '#b8d4ff',
  },
  stats: {
    display: 'flex',
    gap: 10,
    fontSize: 12,
  },
  headerButtons: {
    display: 'flex',
    gap: 4,
    marginLeft: 'auto',
  },
  filterBtn: {
    padding: '3px 10px',
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(255,255,255,0.12)',
    borderRadius: 4,
    color: '#999',
    fontSize: 11,
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  filterBtnActive: {
    background: 'rgba(100,160,255,0.15)',
    borderColor: 'rgba(100,160,255,0.5)',
    color: '#b8d4ff',
  },
  resetBtn: {
    padding: '3px 10px',
    background: 'rgba(255,100,100,0.1)',
    border: '1px solid rgba(255,100,100,0.25)',
    borderRadius: 4,
    color: '#ff9090',
    fontSize: 11,
    cursor: 'pointer',
    fontFamily: 'inherit',
    marginLeft: 8,
  },
  grid: {
    flex: 1,
    overflowY: 'auto' as const,
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: 6,
    padding: 12,
    alignContent: 'start',
  },
  card: {
    display: 'flex',
    flexDirection: 'column',
    padding: '6px 8px',
    borderRadius: 6,
    border: '2px solid rgba(255,255,255,0.08)',
    transition: 'border-color 0.15s, background 0.15s',
  },
  cardTop: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  spriteWrap: {
    width: 40,
    height: 40,
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#000',
    borderRadius: 4,
  },
  sprite: {
    maxWidth: 32,
    maxHeight: 32,
    objectFit: 'contain' as const,
    imageRendering: 'pixelated' as const,
  },
  cardInfo: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  itemName: {
    fontSize: 12,
    color: '#e0e0e0',
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  fileName: {
    fontSize: 10,
    color: '#666',
  },
  statusBtns: {
    display: 'flex',
    gap: 3,
    flexShrink: 0,
  },
  statusBtn: {
    width: 24,
    height: 24,
    borderRadius: 4,
    border: '1px solid rgba(255,255,255,0.15)',
    background: 'transparent',
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 700,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    fontFamily: 'inherit',
    transition: 'all 0.1s',
  },
  commentInput: {
    marginTop: 4,
    padding: '4px 6px',
    background: 'rgba(255,255,255,0.04)',
    border: '1px solid rgba(244,67,54,0.3)',
    borderRadius: 3,
    color: '#e0e0e0',
    fontSize: 11,
    fontFamily: 'inherit',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
  },
};

export { S };
