import type { RegionConnection } from '../../../types';
import { DW_OVERWORLD_DARK_DEATH_MOUNTAIN_CONNECTIONS } from './dark-death-mountain';
import { DW_OVERWORLD_DARK_EAST_CONNECTIONS } from './dark-east';
import { DW_OVERWORLD_DARK_LAKE_HYLIA_CONNECTIONS } from './dark-lake-hylia';
import { DW_OVERWORLD_DARK_MIRE_CONNECTIONS } from './dark-mire';
import { DW_OVERWORLD_DARK_NORTH_CONNECTIONS } from './dark-north';
import { DW_OVERWORLD_DARK_SOUTH_CONNECTIONS } from './dark-south';
import { DW_OVERWORLD_SKULL_WOODS_AREA_CONNECTIONS } from './skull-woods-area';
import { DW_OVERWORLD_VILLAGE_CONNECTIONS } from './village-of-outcasts';

export const DW_OVERWORLD_CONNECTIONS: RegionConnection[] = [
  ...DW_OVERWORLD_DARK_DEATH_MOUNTAIN_CONNECTIONS,
  ...DW_OVERWORLD_DARK_EAST_CONNECTIONS,
  ...DW_OVERWORLD_DARK_LAKE_HYLIA_CONNECTIONS,
  ...DW_OVERWORLD_DARK_MIRE_CONNECTIONS,
  ...DW_OVERWORLD_DARK_NORTH_CONNECTIONS,
  ...DW_OVERWORLD_DARK_SOUTH_CONNECTIONS,
  ...DW_OVERWORLD_SKULL_WOODS_AREA_CONNECTIONS,
  ...DW_OVERWORLD_VILLAGE_CONNECTIONS,
];
