import type { RegionConnection } from '../../../types';

/**
 * Dark World overworld screen-to-screen adjacency connections.
 * Auto-generated from grid layout. Every adjacent screen pair is connected.
 */
export const DW_SCREEN_ADJACENCY_CONNECTIONS: RegionConnection[] = [
  { from: 'dw-00', to: 'dw-01', entrance: 'Skull Woods NW East to Skull Woods NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-00', to: 'dw-08', entrance: 'Skull Woods NW South to Skull Woods SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-01', to: 'dw-02', entrance: 'Skull Woods NE East to Eastern Skull Clearing', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-01', to: 'dw-09', entrance: 'Skull Woods NE South to Skull Woods SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-02', to: 'dw-03', entrance: 'Eastern Skull Clearing East to Ganon\'s Tower NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-02', to: 'dw-0a', entrance: 'Eastern Skull Clearing South to Bungie Cave Fun Zone', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-03', to: 'dw-04', entrance: 'Ganon\'s Tower NW East to Ganon\'s Tower NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-03', to: 'dw-0b', entrance: 'Ganon\'s Tower NW South to Ganon\'s Tower SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-04', to: 'dw-05', entrance: 'Ganon\'s Tower NE East to DW Death Mountain Bridge NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-04', to: 'dw-0c', entrance: 'Ganon\'s Tower NE South to Ganon\'s Tower SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-05', to: 'dw-06', entrance: 'DW Death Mountain Bridge NW East to DW Death Mountain Bridge NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-05', to: 'dw-0d', entrance: 'DW Death Mountain Bridge NW South to DW Death Mountain Bridge SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-06', to: 'dw-07', entrance: 'DW Death Mountain Bridge NE East to Turtle Rock', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-06', to: 'dw-0e', entrance: 'DW Death Mountain Bridge NE South to DW Death Mountain Bridge SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-07', to: 'dw-0f', entrance: 'Turtle Rock South to Falls of Ill Omen', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-08', to: 'dw-09', entrance: 'Skull Woods SW East to Skull Woods SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-08', to: 'dw-10', entrance: 'Skull Woods SW South to Skull Woods Outskirts', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-09', to: 'dw-0a', entrance: 'Skull Woods SE East to Bungie Cave Fun Zone', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-09', to: 'dw-11', entrance: 'Skull Woods SE South to VoO Psychics', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0a', to: 'dw-0b', entrance: 'Bungie Cave Fun Zone East to Ganon\'s Tower SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0a', to: 'dw-12', entrance: 'Bungie Cave Fun Zone South to Northern Pond (Evil)', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0b', to: 'dw-0c', entrance: 'Ganon\'s Tower SW East to Ganon\'s Tower SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0b', to: 'dw-13', entrance: 'Ganon\'s Tower SW South to Unctuary Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0c', to: 'dw-0d', entrance: 'Ganon\'s Tower SE East to DW Death Mountain Bridge SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0c', to: 'dw-14', entrance: 'Ganon\'s Tower SE South to Garden of Very Bad Things', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0d', to: 'dw-0e', entrance: 'DW Death Mountain Bridge SW East to DW Death Mountain Bridge SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0d', to: 'dw-15', entrance: 'DW Death Mountain Bridge SW South to South Bend', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0e', to: 'dw-0f', entrance: 'DW Death Mountain Bridge SE East to Falls of Ill Omen', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0e', to: 'dw-16', entrance: 'DW Death Mountain Bridge SE South to Riverside Commerce', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-0f', to: 'dw-17', entrance: 'Falls of Ill Omen South to Ridge of Ill Omen', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-10', to: 'dw-11', entrance: 'Skull Woods Outskirts East to VoO Psychics', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-10', to: 'dw-18', entrance: 'Skull Woods Outskirts South to Village of Outcasts NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-11', to: 'dw-12', entrance: 'VoO Psychics East to Northern Pond (Evil)', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-11', to: 'dw-19', entrance: 'VoO Psychics South to Village of Outcasts NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-12', to: 'dw-13', entrance: 'Northern Pond (Evil) East to Unctuary Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-12', to: 'dw-1a', entrance: 'Northern Pond (Evil) South to West Woods', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-13', to: 'dw-14', entrance: 'Unctuary Grounds East to Garden of Very Bad Things', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-13', to: 'dw-1b', entrance: 'Unctuary Grounds South to Pyramid of Power NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-14', to: 'dw-15', entrance: 'Garden of Very Bad Things East to South Bend', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-14', to: 'dw-1c', entrance: 'Garden of Very Bad Things South to Pyramid of Power NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-15', to: 'dw-16', entrance: 'South Bend East to Riverside Commerce', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-15', to: 'dw-1d', entrance: 'South Bend South to Pyramid East', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-16', to: 'dw-17', entrance: 'Riverside Commerce East to Ridge of Ill Omen', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-16', to: 'dw-1e', entrance: 'Riverside Commerce South to Maze of Darkness NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-17', to: 'dw-1f', entrance: 'Ridge of Ill Omen South to Maze of Darkness NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-18', to: 'dw-19', entrance: 'Village of Outcasts NW East to Village of Outcasts NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-18', to: 'dw-20', entrance: 'Village of Outcasts NW South to Village of Outcasts SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-19', to: 'dw-1a', entrance: 'Village of Outcasts NE East to West Woods', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-19', to: 'dw-21', entrance: 'Village of Outcasts NE South to Village of Outcasts SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1a', to: 'dw-1b', entrance: 'West Woods East to Pyramid of Power NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1a', to: 'dw-22', entrance: 'West Woods South to Gossip Shop', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1b', to: 'dw-1c', entrance: 'Pyramid of Power NW East to Pyramid of Power NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1b', to: 'dw-23', entrance: 'Pyramid of Power NW South to Pyramid of Power SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1c', to: 'dw-1d', entrance: 'Pyramid of Power NE East to Pyramid East', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1c', to: 'dw-24', entrance: 'Pyramid of Power NE South to Pyramid of Power SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1d', to: 'dw-1e', entrance: 'Pyramid East East to Maze of Darkness NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1d', to: 'dw-25', entrance: 'Pyramid East South to Moundlands', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1e', to: 'dw-1f', entrance: 'Maze of Darkness NW East to Maze of Darkness NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1e', to: 'dw-26', entrance: 'Maze of Darkness NW South to Maze of Darkness SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-1f', to: 'dw-27', entrance: 'Maze of Darkness NE South to Maze of Darkness SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-20', to: 'dw-21', entrance: 'Village of Outcasts SW East to Village of Outcasts SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-20', to: 'dw-28', entrance: 'Village of Outcasts SW South to Digging Game Field', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-21', to: 'dw-22', entrance: 'Village of Outcasts SE East to Gossip Shop', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-21', to: 'dw-29', entrance: 'Village of Outcasts SE South to Archery Shop Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-22', to: 'dw-23', entrance: 'Gossip Shop East to Pyramid of Power SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-22', to: 'dw-2a', entrance: 'Gossip Shop South to Depressing Grove', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-23', to: 'dw-24', entrance: 'Pyramid of Power SW East to Pyramid of Power SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-23', to: 'dw-2b', entrance: 'Pyramid of Power SW South to Bomb Shop Grounds West', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-24', to: 'dw-25', entrance: 'Pyramid of Power SE East to Moundlands', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-24', to: 'dw-2c', entrance: 'Pyramid of Power SE South to Bomb Shop Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-25', to: 'dw-26', entrance: 'Moundlands East to Maze of Darkness SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-25', to: 'dw-2d', entrance: 'Moundlands South to Hammer Time Bridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-26', to: 'dw-27', entrance: 'Maze of Darkness SW East to Maze of Darkness SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-26', to: 'dw-2e', entrance: 'Maze of Darkness SW South to Terrace of Darkness', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-27', to: 'dw-2f', entrance: 'Maze of Darkness SE South to Cul-de-sac of Darkness', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-28', to: 'dw-29', entrance: 'Digging Game Field East to Archery Shop Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-28', to: 'dw-30', entrance: 'Digging Game Field South to Swamp of Evil NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-29', to: 'dw-2a', entrance: 'Archery Shop Grounds East to Depressing Grove', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-29', to: 'dw-31', entrance: 'Archery Shop Grounds South to Swamp of Evil NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2a', to: 'dw-2b', entrance: 'Depressing Grove East to Bomb Shop Grounds West', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2a', to: 'dw-32', entrance: 'Depressing Grove South to Depressing Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2b', to: 'dw-2c', entrance: 'Bomb Shop Grounds West East to Bomb Shop Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2b', to: 'dw-33', entrance: 'Bomb Shop Grounds West South to Wilted Wetlands NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2c', to: 'dw-2d', entrance: 'Bomb Shop Grounds East to Hammer Time Bridge', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2c', to: 'dw-34', entrance: 'Bomb Shop Grounds South to Wilted Wetlands NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2d', to: 'dw-2e', entrance: 'Hammer Time Bridge East to Terrace of Darkness', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2d', to: 'dw-35', entrance: 'Hammer Time Bridge South to Lake Dielia NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2e', to: 'dw-2f', entrance: 'Terrace of Darkness East to Cul-de-sac of Darkness', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2e', to: 'dw-36', entrance: 'Terrace of Darkness South to Lake Dielia NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-2f', to: 'dw-37', entrance: 'Cul-de-sac of Darkness South to Info Hub', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-30', to: 'dw-31', entrance: 'Swamp of Evil NW East to Swamp of Evil NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-30', to: 'dw-38', entrance: 'Swamp of Evil NW South to Swamp of Evil SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-31', to: 'dw-32', entrance: 'Swamp of Evil NE East to Depressing Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-31', to: 'dw-39', entrance: 'Swamp of Evil NE South to Swamp of Evil SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-32', to: 'dw-33', entrance: 'Depressing Terrace East to Wilted Wetlands NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-32', to: 'dw-3a', entrance: 'Depressing Terrace South to Via To Nowhere', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-33', to: 'dw-34', entrance: 'Wilted Wetlands NW East to Wilted Wetlands NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-33', to: 'dw-3b', entrance: 'Wilted Wetlands NW South to Swamp Palace Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-34', to: 'dw-35', entrance: 'Wilted Wetlands NE East to Lake Dielia NW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-34', to: 'dw-3c', entrance: 'Wilted Wetlands NE South to Wilted Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-35', to: 'dw-36', entrance: 'Lake Dielia NW East to Lake Dielia NE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-35', to: 'dw-3d', entrance: 'Lake Dielia NW South to Lake Dielia SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-36', to: 'dw-37', entrance: 'Lake Dielia NE East to Info Hub', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-36', to: 'dw-3e', entrance: 'Lake Dielia NE South to Lake Dielia SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-37', to: 'dw-3f', entrance: 'Info Hub South to A Terrible Vacation Spot', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-38', to: 'dw-39', entrance: 'Swamp of Evil SW East to Swamp of Evil SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-39', to: 'dw-3a', entrance: 'Swamp of Evil SE East to Via To Nowhere', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-3a', to: 'dw-3b', entrance: 'Via To Nowhere East to Swamp Palace Grounds', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-3b', to: 'dw-3c', entrance: 'Swamp Palace Grounds East to Wilted Terrace', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-3c', to: 'dw-3d', entrance: 'Wilted Terrace East to Lake Dielia SW', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-3d', to: 'dw-3e', entrance: 'Lake Dielia SW East to Lake Dielia SE', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
  { from: 'dw-3e', to: 'dw-3f', entrance: 'Lake Dielia SE East to A Terrible Vacation Spot', tags: ['transit:walk', 'dir:two-way', 'ctx:overworld'] },
];
