"""The JSON the package is built from, read once at import.

Every file under data/ is generated by scripts/build/build-apworld.mjs from the
TypeScript world (shared/randomizer/archipelago/export/). Nothing here is
written by hand, and the package holds no game data of its own.
"""
import json
import pkgutil


def _load(name: str):
    raw = pkgutil.get_data(__name__, f"data/{name}")
    if raw is None:
        raise FileNotFoundError(f"relic_of_the_past: data/{name} is missing from the package")
    return json.loads(raw.decode("utf-8"))


GAME_DATA = _load("game.json")
LOCATIONS = _load("locations.json")
REGIONS = _load("regions.json")
ITEMS = _load("items.json")
RULES = _load("rules.json")
OPTIONS = _load("options.json")

GAME: str = GAME_DATA["game"]
WORLD_VERSION: str = GAME_DATA["worldVersion"]
VICTORY_ITEM: str = GAME_DATA["victoryItem"]
