// @layer core-wasm-build @kind build
/**
 * Computes the save state format id and writes the generated module the app imports.
 *
 * Compiles state-layout-probe.c against the same headers and the same compiler the real
 * build uses, so the region sizes it reports carry the real wasm32 ABI rather than the
 * host's. Runs it, hashes the region sequence, and writes
 * shared/game/save-state/current-format.generated.ts.
 *
 * That generated file is COMMITTED. `npm run ci` does not build wasm, so a gitignored
 * module would break typecheck on a fresh clone — and committing it means a change to the
 * save state layout shows up as a reviewable one-line diff rather than a surprise at
 * release time.
 *
 * Prerequisite: emcc on PATH (emsdk activated), same as build.mjs.
 * Idempotent: re-running with an unchanged layout rewrites identical bytes.
 */
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

const here = import.meta.dirname;
const zelda3 = resolve(here, '..', 'zelda3');
const hooks = resolve(here, '..', 'game-hooks');
const generatedPath = resolve(
  here, '..', '..', 'shared', 'game', 'save-state', 'current-format.generated.ts',
);

/** Only the translation units that own a region walk. The rest of the core is irrelevant. */
const probeSrcs = [
  join(here, 'state-layout-probe.c'),
  join(zelda3, 'snes', 'dsp.c'),
  join(zelda3, 'snes', 'dma.c'),
  join(zelda3, 'snes', 'ppu.c'),
];

/**
 * Those three units reference symbols that live in the rest of the core, none of which
 * the probe's single call path reaches. Letting them stay undefined is what keeps this a
 * four-file compile instead of a whole-core link.
 */
const emflags = [
  '-O0',
  '-I', zelda3,
  '-I', hooks,
  '-DSYSTEM_VOLUME_MIXER_AVAILABLE=0',
  '-Wno-unused-function',
  '-Wno-unused-variable',
  '-sERROR_ON_UNDEFINED_SYMBOLS=0',
  '-sALLOW_MEMORY_GROWTH=1',
  '-sNODERAWFS=0',
];

const runEmcc = (outFile) => {
  const args = [...emflags, ...probeSrcs, '-o', outFile];
  const isWin = process.platform === 'win32';
  const cmd = isWin ? process.env.COMSPEC || 'cmd.exe' : 'emcc';
  const spawnArgs = isWin ? ['/c', 'emcc', ...args] : args;
  return spawnSync(cmd, spawnArgs, { encoding: 'utf8' });
};

/** Runs the compiled probe and parses its two lines into a sequence + total. */
const readLayout = (probeJs) => {
  const run = spawnSync(process.execPath, [probeJs], { encoding: 'utf8' });
  if (run.status !== 0) {
    throw new Error(`probe exited ${run.status}\n${run.stderr || run.stdout}`);
  }
  const lines = run.stdout.trim().split(/\r?\n/);
  const regions = lines[0].split(',').map((n) => parseInt(n, 10));
  const total = parseInt((lines[1] || '').replace('total=', ''), 10);
  if (!regions.length || regions.some(Number.isNaN) || Number.isNaN(total)) {
    throw new Error(`probe printed something unparseable:\n${run.stdout}`);
  }
  return { regions, total };
};

/** The id: first 12 hex of sha256 over the comma-joined sequence. Short enough to read. */
const idFor = (regions) =>
  createHash('sha256').update(regions.join(',')).digest('hex').slice(0, 12);

const renderModule = ({ id, regions, total }) => `/* @layer shared-game @kind generated */
/**
 * GENERATED by core/wasm-build/layout-probe.mjs. Do not edit by hand.
 *
 * The save state layout this build produces, as the ordered sequence of snapshot region
 * lengths and the id derived from it. Committed on purpose: it is what lets typecheck and
 * the release gate see the layout without building wasm, and it makes a layout change show
 * up as a reviewable diff.
 */
const CURRENT_STATE_FORMAT = {
  id: '${id}',
  regions: [${regions.join(', ')}],
  totalBytes: ${total},
} as const;

export { CURRENT_STATE_FORMAT };
`;

const run = () => {
  const workDir = mkdtempSync(join(tmpdir(), 'rotp-layout-probe-'));
  const probeJs = join(workDir, 'probe.js');
  try {
    const compile = runEmcc(probeJs);
    if (compile.status !== 0 || !existsSync(probeJs)) {
      console.error(compile.stderr || compile.stdout);
      throw new Error('emcc failed to build the layout probe');
    }

    const { regions, total } = readLayout(probeJs);
    const id = idFor(regions);
    const next = renderModule({ id, regions, total });
    const prev = existsSync(generatedPath) ? readFileSync(generatedPath, 'utf8') : null;

    if (prev === next) {
      console.log(`[layout-probe] unchanged — format ${id} (${total} bytes)`);
      return;
    }

    mkdirSync(dirname(generatedPath), { recursive: true });
    writeFileSync(generatedPath, next);

    // Only an id change is a layout change. Rewording the header of this file is not,
    // and saying so would train everyone to ignore the line that actually matters.
    const prevId = prev?.match(/id: '([0-9a-f]+)'/)?.[1] ?? null;
    console.log(`[layout-probe] ${prevId ? 'rewritten' : 'created'} — format ${id} (${total} bytes)`);
    if (prevId && prevId !== id) {
      console.log(`[layout-probe] LAYOUT CHANGED: ${prevId} -> ${id}.`);
      console.log('[layout-probe] Add a KNOWN_FORMATS row saying what moved, or the release will refuse to publish.');
    }
  } finally {
    rmSync(workDir, { recursive: true, force: true });
  }
};

run();
