import type { GridProvider } from './grid-provider';

/**
 * GridProvider backed by pre-computed grid data files.
 * Used in tests to avoid needing a ROM file or running WASM.
 *
 * Expects a lookup function that returns a flat Uint8Array for a given key.
 * Cache files can be generated by running RomGridProvider or WasmGridProvider
 * and saving the output.
 */
export class CachedGridProvider implements GridProvider {
  constructor(
    private overworldGrids: Map<number, Uint8Array>,
    private roomGrids: Map<number, Uint8Array>,
  ) {}

  getOverworldRawAttr(screenIndex: number): Uint8Array {
    const grid = this.overworldGrids.get(screenIndex);
    if (!grid) {
      throw new Error(`CachedGridProvider: no cached grid for overworld screen ${screenIndex}`);
    }
    return grid;
  }

  getRoomRawAttr(roomId: number): Uint8Array {
    const grid = this.roomGrids.get(roomId);
    if (!grid) {
      throw new Error(`CachedGridProvider: no cached grid for room ${roomId}`);
    }
    return grid;
  }

  /** Create from a directory of .bin files (screen-NN.bin, room-NN.bin). */
  static fromBuffers(entries: { type: 'overworld' | 'room'; id: number; data: Uint8Array }[]): CachedGridProvider {
    const ow = new Map<number, Uint8Array>();
    const rooms = new Map<number, Uint8Array>();
    for (const e of entries) {
      if (e.type === 'overworld') ow.set(e.id, e.data);
      else rooms.set(e.id, e.data);
    }
    return new CachedGridProvider(ow, rooms);
  }
}
