import type { RegionDefinition } from '../types';

export const LW_CAVES: RegionDefinition[] = [
  { id: 'aginahs-cave', name: 'Aginahs Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:desert', 'role:treasure'] },
  { id: 'bat-cave-right', name: 'Bat Cave (right)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:kakariko', 'role:treasure'] },
  { id: 'bat-cave-left', name: 'Bat Cave (left)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:kakariko', 'role:connector'] },
  { id: 'kings-grave', name: 'Kings Grave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:east_hyrule', 'role:treasure'] },
  { id: 'mini-moldorm-cave', name: 'Mini Moldorm Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:south_hyrule', 'role:treasure'] },
  { id: 'ice-rod-cave', name: 'Ice Rod Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:south_hyrule', 'role:treasure'] },
  { id: 'good-bee-cave', name: 'Good Bee Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:lake_hylia'] },
  { id: '20-rupee-cave', name: '20 Rupee Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:lake_hylia', 'role:treasure'] },
  { id: 'bonk-rock-cave', name: 'Bonk Rock Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:south_hyrule', 'role:treasure'] },
  { id: '50-rupee-cave', name: '50 Rupee Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:south_hyrule', 'role:treasure'] },
  { id: 'cave-45', name: 'Cave 45', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:south_hyrule', 'role:treasure'] },
  { id: 'graveyard-cave', name: 'Graveyard Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:east_hyrule', 'role:treasure'] },
  { id: 'checkerboard-cave', name: 'Checkerboard Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:desert', 'role:treasure'] },
  { id: 'lost-woods-hideout-top', name: 'Lost Woods Hideout (top)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:lost_woods', 'role:drop_zone'] },
  { id: 'lost-woods-hideout-bottom', name: 'Lost Woods Hideout (bottom)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:lost_woods', 'role:treasure'] },
  { id: 'lumberjack-tree-top', name: 'Lumberjack Tree (top)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:lost_woods', 'role:drop_zone'] },
  { id: 'lumberjack-tree-bottom', name: 'Lumberjack Tree (bottom)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:lost_woods', 'role:treasure'] },
  { id: 'spectacle-rock-cave-top', name: 'Spectacle Rock Cave (Top)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:death_mountain', 'role:treasure'] },
  { id: 'paradox-cave-front', name: 'Paradox Cave Front', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:death_mountain', 'role:connector'] },
  { id: 'paradox-cave-chest-area', name: 'Paradox Cave Chest Area', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:death_mountain', 'role:treasure'] },
  { id: 'paradox-cave', name: 'Paradox Cave', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:death_mountain', 'role:connector'] },
  { id: 'spiral-cave-top', name: 'Spiral Cave (Top)', type: 'cave', tags: ['world:light', 'env:underground', 'type:cave', 'area:death_mountain', 'role:treasure'] },
];
